// Generated by scripts/generate-native-group-definitions.mts.
// JSON parity oracle only: batteries/templates/structures/districts/ZoneNesting/ZoneNesting.json
// @scene-id definition:batteries.templates.structures.districts.zone-nesting.zone-nesting.nested.0
const zoneNestingTemplateTileAssetName = defineGroup(
  {
    id: "scene.template.zone-nesting.nested.0",
    version: "1.0.0",
    inputs: {
      input0: { type: Scene, runtimeType: "scene", runtimePort: "in_0", access: "item" },
      input1: { type: StringValue, runtimeType: "string", runtimePort: "in_1", access: "tree" },
    },
    outputs: {
      output0: { type: Scene, runtimeType: "scene", runtimePort: "out_0", access: "item" },
    },
  },
  ({ input0, input1 }) => {
    // @scene-id tz_tp_name
    const textPanel1 = textPanel({
        "$params": {"text":"asset_name","_nodeWidth":180,"_nodeHeight":67},
      })

    // @scene-id tz_tp_type
    const textPanel2 = textPanel({
        "$params": {"text":"asset_type","_nodeWidth":181,"_nodeHeight":60},
      })

    // @scene-id tz_tp_tile
    const textPanel3 = textPanel({
        "$params": {"text":"tile","_nodeWidth":181,"_nodeHeight":60},
      })

    // @scene-id tz_str
    const stringValue4 = stringValue({
        "value": input1,
      })

    // @scene-id tz_set1
    const sceneSetAttribute5 = sceneSetAttribute({
        "scene": input0,
        "key": textPanel1.output,
        "value": stringValue4.value,
      })

    // @scene-id tz_set2
    const sceneSetAttribute6 = sceneSetAttribute({
        "scene": sceneSetAttribute5.scene,
        "key": textPanel2.output,
        "value": textPanel3.output,
      })
    return {
      output0: sceneSetAttribute6.scene,
    }
  },
)

// @scene-id definition:batteries.templates.structures.districts.zone-nesting.zone-nesting
export const zoneNestingTemplate = defineGroup(
  {
    id: "scene.template.zone-nesting",
    version: "1.0.0",
    inputs: {
      input0: { type: Scene, runtimeType: "scene", runtimePort: "in_0", access: "tree" },
      districtAsset: { type: StringValue, runtimeType: "string", runtimePort: "in_1", access: "tree", labelEn: "DistrictAsset" },
      seed: { type: NumberValue, runtimeType: "number", runtimePort: "in_2", access: "tree", labelEn: "Seed" },
      erosionStrength: { type: NumberValue, runtimeType: "number", runtimePort: "in_3", access: "item", labelEn: "ErosionStrength" },
      layers: { type: NumberValue, runtimeType: "number", runtimePort: "in_4", access: "item", labelEn: "Layers" },
      splineSmoothness: { type: NumberValue, runtimeType: "number", runtimePort: "in_5", access: "item", labelEn: "SplineSmoothness" },
      input6: { type: NumberValue, runtimeType: "number", runtimePort: "in_6", access: "item", hidden: true },
      input7: { type: StringValue, runtimeType: "string", runtimePort: "in_7", access: "item", hidden: true },
      input8: { type: StringValue, runtimeType: "string", runtimePort: "in_8", access: "item", hidden: true },
      input9: { type: NumberValue, runtimeType: "number", runtimePort: "in_9", access: "item", hidden: true },
      input10: { type: NumberValue, runtimeType: "number", runtimePort: "in_10", access: "item", hidden: true },
      input11: { type: NumberValue, runtimeType: "number", runtimePort: "in_11", access: "item", hidden: true },
      input12: { type: StringValue, runtimeType: "string", runtimePort: "in_12", access: "item", hidden: true },
      input13: { type: StringValue, runtimeType: "string", runtimePort: "in_13", access: "item", hidden: true },
      input14: { type: NumberList, runtimeType: "number", runtimePort: "in_14", access: "list", hidden: true },
    },
    outputs: {
      scene: { type: Scene, runtimeType: "scene", runtimePort: "out_0", access: "tree", order: 0, labelEn: "Scene" },
      rest: { type: Scene, runtimeType: "scene", runtimePort: "out_1", access: "tree", order: 1, labelEn: "Rest" },
      district: { type: Scene, runtimeType: "scene", runtimePort: "out_2", access: "tree", order: 2, labelEn: "District" },
      districtPath: { type: StringValue, runtimeType: "string", runtimePort: "out_3", access: "tree", order: 3, labelEn: "DistrictPath" },
      restPath: { type: StringValue, runtimeType: "string", runtimePort: "out_4", access: "tree", order: 4, labelEn: "RestPath" },
    },
  },
  ({ input0, districtAsset, seed, erosionStrength, layers, splineSmoothness, input6, input7, input8, input9, input10, input11, input12, input13, input14 }) => {
    // @scene-id zn_in
    const scenePassthrough1 = scenePassthrough({
        "scene": input0,
      })

    // @scene-id zn_explode
    const nodeExplode2 = nodeExplode({
        "scene": scenePassthrough1.scene,
      })

    // @scene-id zn_rgrid
    const rectangularGrid3 = rectangularGrid({
        "fillValue": input10,
        "width": nodeExplode2.width,
        "height": nodeExplode2.height,
      })

    // @scene-id zn_slice
    const voxelSlice4 = voxelSlice({
        "z": input11,
        "voxels": nodeExplode2.voxels,
        "grid": rectangularGrid3.grid,
      })

    // @scene-id zn_seed
    const multiSeed5 = multiSeed({
        "seed": seed,
        "shape": voxelSlice4.slice,
      })

    // @scene-id zn_zone
    const zoneNesting6 = zoneNesting({
        "erosionStrength": erosionStrength,
        "layers": layers,
        "splineSmoothness": splineSmoothness,
        "targetValue": input6,
        "algorithm": input7,
        "splineAlgorithm": input8,
        "splineSeed": input9,
        "inputGrid": voxelSlice4.slice,
        "seed": multiSeed5.seed,
      })

    // @scene-id zn_name
    const stringValue7 = stringValue({
        "value": districtAsset,
      })

    // @scene-id zn_g2n_zone
    const gridSceneNode8 = gridSceneNode({
        "schema": input12,
        "token": input13,
        "zRange": input14,
        "grid": zoneNesting6.outputGrid,
        "name": stringValue7.value,
      })

    // @scene-id zn_tilezone
    const zoneNestingTemplateTileAssetName9 = zoneNestingTemplateTileAssetName({
        "input0": gridSceneNode8.scene,
        "input1": stringValue7.value,
      })

    // @scene-id zn_add_zone
    const addSceneChildren10 = addSceneChildren({
        "nodes": zoneNestingTemplateTileAssetName9.output0,
        "scene": scenePassthrough1.scene,
      })

    // @scene-id zn_subtract
    const algRegionSubtract11 = algRegionSubtract({
        "a": voxelSlice4.slice,
        "b": zoneNesting6.outputGrid,
      })

    // @scene-id zn_rname
    const textPanel12 = textPanel({
        "$params": {"text":"rest","_nodeWidth":172,"_nodeHeight":69},
      })

    // @scene-id zn_g2n_rest
    const gridSceneNode13 = gridSceneNode({
        "grid": algRegionSubtract11.region,
        "name": textPanel12.output,
      })

    // @scene-id zn_add_rest
    const addSceneChildren14 = addSceneChildren({
        "scene": addSceneChildren10.scene,
        "nodes": gridSceneNode13.scene,
      })

    // @scene-id zn_merge
    const sceneMergeSubtrees15 = sceneMergeSubtrees({
        "scenes": addSceneChildren14.scene,
      })

    // @scene-id zn_focus_zone
    const sceneFocusPath16 = sceneFocusPath({
        "scene": sceneMergeSubtrees15.scene,
        "path": addSceneChildren10.childPaths,
      })

    // @scene-id zn_focus_rest
    const sceneFocusPath17 = sceneFocusPath({
        "scene": sceneMergeSubtrees15.scene,
        "path": addSceneChildren14.childPaths,
      })

    // @scene-id zn_out_main
    const scenePassthrough18 = scenePassthrough({
        "scene": sceneMergeSubtrees15.scene,
      })

    // @scene-id zn_out_zone
    const scenePassthrough19 = scenePassthrough({
        "scene": sceneFocusPath16.scene,
      })

    // @scene-id zn_out_rest
    const scenePassthrough20 = scenePassthrough({
        "scene": sceneFocusPath17.scene,
      })

    // @scene-id zn_zpath
    const stringValue21 = stringValue({
        "value": addSceneChildren10.childPaths,
      })

    // @scene-id zn_rpath
    const stringValue22 = stringValue({
        "value": addSceneChildren14.childPaths,
      })
    return {
      scene: scenePassthrough18.scene,
      rest: scenePassthrough20.scene,
      district: scenePassthrough19.scene,
      districtPath: stringValue21.value,
      restPath: stringValue22.value,
    }
  },
)
