// Generated by scripts/generate-native-group-definitions.mts.
// JSON parity oracle only: batteries/groups/test_terrain/random-mountain-terrain/random-mountain-terrain.json
// Inventory status: retired-test-oracle; never loaded by the production Registry.
// @scene-id definition:batteries.groups.test-terrain.random-mountain-terrain.random-mountain-terrain
export const randomMountainTerrain = defineGroup(
  {
    id: "scene.group.test-terrain.random-mountain-terrain.random-mountain-terrain",
    version: "1.0.0",
    inputs: {
      input0: { type: Any, runtimeType: "array", runtimePort: "in__6832__list", label: "名称清单" },
      input1: { type: Any, runtimeType: "array", runtimePort: "in__6832__gridList", label: "网格列表" },
      input2: { type: NumberValue, runtimeType: "number", runtimePort: "in__1368__roughness", label: "粗糙度" },
      input3: { type: NumberValue, runtimeType: "number", runtimePort: "in__1368__initHeight", label: "初始高度" },
      input4: { type: NumberValue, runtimeType: "number", runtimePort: "in__1368__spread", label: "扰动幅度" },
      input5: { type: NumberValue, runtimeType: "number", runtimePort: "in__8354__layers", label: "层数" },
      input6: { type: NumberValue, runtimeType: "number", runtimePort: "in__6282__seed", label: "随机种子" },
    },
    outputs: {
      output0: { type: StringValue, runtimeType: "string", runtimePort: "out__2581__description", label: "说明信息" },
      output1: { type: Any, runtimeType: "array", runtimePort: "out__2581__outputGrids", label: "输出网格列表" },
      output2: { type: Any, runtimeType: "array", runtimePort: "out__2581__outputNameList", label: "名称清单" },
      output3: { type: StringValue, runtimeType: "string", runtimePort: "out__2581__errorMessage", label: "错误信息" },
    },
  },
  ({ input0, input1, input2, input3, input4, input5, input6 }) => {
    // @scene-id node-1774868656832
    const retiredNameListPass1 = retiredNameListPass({
        "list": input0,
        "gridList": input1,
      })

    // @scene-id node-1774868668188
    const retiredSimpleSort2 = retiredSimpleSort({
        "gridList": retiredNameListPass1.gridList,
        "nameListList": retiredNameListPass1.list,
      })

    // @scene-id node-1774868686820
    const retiredNameListFlatten3 = retiredNameListFlatten({
        "nameListList": retiredSimpleSort2.nameListList,
      })

    // @scene-id node-1774868695510
    const retiredMerge4 = retiredMerge({
        "$params": {"portCount":3},
        "item_0": retiredSimpleSort2.gridList,
        "item_1": retiredNameListFlatten3.outputNameList,
      })

    // @scene-id node-1774868705310
    const textPanel5 = textPanel({
        "$params": {"text":"生成随机山脉，输入网格和层数，输出对应层数的山脉地形"},
      })

    // @scene-id node-1774868721885
    const numberValue6 = numberValue({})

    // @scene-id node-1774868716092
    const listGetSingle7 = listGetSingle({
        "list": retiredNameListPass1.gridList,
        "index": numberValue6.value,
      })

    // @scene-id node-1774868759042
    const gridSize8 = gridSize({
        "grid": listGetSingle7.item,
      })

    // @scene-id node-1774870126282
    const seed9 = seed({
        "seed": input6,
      })

    // @scene-id node-1774870326447
    const textPanel10 = textPanel({
        "$params": {"text":"max"},
      })

    // @scene-id node-1774870321906
    const advancedMathOp11 = advancedMathOp({
        "$params": {"op":"max"},
        "op": textPanel10.output,
        "a": gridSize8.width,
        "b": gridSize8.height,
      })

    // @scene-id node-1774870350072
    const textPanel12 = textPanel({
        "$params": {"text":"log"},
      })

    // @scene-id node-1774870371562
    const numberValue13 = numberValue({
        "$params": {"value":2},
      })

    // @scene-id node-1774870345730
    const advancedMathOp14 = advancedMathOp({
        "op": textPanel12.output,
        "a": advancedMathOp11.result,
        "b": numberValue13.value,
      })

    // @scene-id node-1774870390376
    const textPanel15 = textPanel({
        "$params": {"text":"ceil"},
      })

    // @scene-id node-1774870400576
    const numberValue16 = numberValue({})

    // @scene-id node-1774870385534
    const advancedMathOp17 = advancedMathOp({
        "$params": {"op":"ceil"},
        "op": textPanel15.output,
        "a": advancedMathOp14.result,
        "b": numberValue16.value,
      })

    // @scene-id node-1774870121368
    const diamondSquare18 = diamondSquare({
        "roughness": input2,
        "initHeight": input3,
        "spread": input4,
        "seed": seed9.seed,
        "power": advancedMathOp17.result,
      })

    // @scene-id node-1774870946040
    const textPanel19 = textPanel({
        "$params": {"text":"[\"一层\",\"二层\",\"三层\",\"四层\",\"五层\"]"},
      })

    // @scene-id node-1774870976547
    const strToList20 = strToList({
        "str": textPanel19.output,
      })

    // @scene-id node-1774871029046
    const textPanel21 = textPanel({
        "$params": {"text":"tile"},
      })

    // @scene-id node-1774871143299
    const textPanel22 = textPanel({
        "$params": {"text":"bilinear"},
      })

    // @scene-id node-1774871131629
    const gridResize23 = gridResize({
        "method": textPanel22.output,
        "width": gridSize8.width,
        "height": gridSize8.height,
        "grid": diamondSquare18.grid,
      })

    // @scene-id node-1774876403290
    const numberValue24 = numberValue({
        "$params": {"min":0,"max":1,"value":0,"precision":2},
      })

    // @scene-id node-1774876412651-scr2i
    const numberValue25 = numberValue({
        "$params": {"min":0,"max":1,"value":1,"precision":2},
      })

    // @scene-id node-1774876398354
    const retiredGridClassify26 = retiredGridClassify({
        "layers": input5,
        "min": numberValue24.value,
        "max": numberValue25.value,
        "grid": gridResize23.grid,
      })

    // @scene-id node-1774870937224
    const retiredGridLabelMulti27 = retiredGridLabelMulti({
        "names": strToList20.list,
        "inputGrid": retiredGridClassify26.grid,
      })

    // @scene-id node-1774871022576
    const retiredLayerTypeTag28 = retiredLayerTypeTag({
        "layerType": textPanel21.output,
        "nameList": retiredGridLabelMulti27.nameList,
      })

    // @scene-id node-1774871038837
    const retiredMerge29 = retiredMerge({
        "$params": {"portCount":3},
        "item_0": retiredGridLabelMulti27.outputGrid,
        "item_1": retiredLayerTypeTag28.outputNameList,
      })

    // @scene-id node-1774868662581
    const fillSort30 = fillSort({
        "$params": {"portCount":3},
        "item_0": retiredMerge4.list,
        "item_1": retiredMerge29.list,
        "description": textPanel5.output,
      })
    return {
      output0: fillSort30.description,
      output1: fillSort30.outputGrids,
      output2: fillSort30.outputNameList,
      output3: fillSort30.errorMessage,
    }
  },
)
