import { afterEach, describe, expect, test } from 'bun:test';

import {
  fetchAudioGenerationStatus,
  generateCreativeVersions,
  saveCreativeVersionToGame,
} from '../src/creativeAudioApi.ts';
import type { CreativeRequest, CreativeVersion } from '../src/creativeWorkbench.ts';

const originalFetch = globalThis.fetch;

afterEach(() => {
  globalThis.fetch = originalFetch;
});

function voiceRequest(): CreativeRequest {
  return {
    mode: 'voice',
    kind: 'voice',
    sourceMode: 'new',
    prompt: '守卫警告',
    direction: '坚定、克制',
    durationSeconds: 0,
    loop: false,
    instrumental: false,
    variationCount: 1,
    projectId: 'demo',
    voice: {
      script: '前方禁止通行。',
      roleId: 'guard',
      role: '守卫',
      emotion: '严肃',
      language: 'zh',
      speed: 'slow',
    },
  };
}

describe('creative audio host API client', () => {
  test('reads capability status without receiving credentials', async () => {
    globalThis.fetch = (async (input) => {
      expect(String(input)).toBe('/__ce-api__/audio-generation-status');
      return Response.json({
        success: true,
        capabilities: {
          tts: { configured: true, providers: ['litellm'] },
          music: { configured: false, providers: [] },
          sfx: { configured: false, providers: [] },
        },
      });
    }) as typeof fetch;

    const result = await fetchAudioGenerationStatus();
    expect(result.tts.providers).toEqual(['litellm']);
    expect(result.music.configured).toBe(false);
  });

  test('generates a real playable voice version through the host TTS route', async () => {
    let sentBody: Record<string, unknown> = {};
    globalThis.fetch = (async (input, init) => {
      if (String(input) === '/__ce-api__/chat') {
        return Response.json({
          success: true,
          text: JSON.stringify({ prompt: 'Game guard; serious restrained delivery; slow pace; close dry game VO.' }),
        });
      }
      expect(String(input)).toBe('/__ce-api__/reel-tts');
      sentBody = JSON.parse(String(init?.body));
      return Response.json({
        success: true,
        base64: 'AQIDBA==',
        mimeType: 'audio/mpeg',
        provider: 'litellm',
        model: 'doubao-tts',
      });
    }) as typeof fetch;

    const versions = await generateCreativeVersions(voiceRequest(), 'voice-request');
    expect(versions).toHaveLength(1);
    expect(versions[0]?.dataUrl).toBe('data:audio/mpeg;base64,AQIDBA==');
    expect(versions[0]?.provider).toBe('litellm');
    expect(sentBody.text).toBe('前方禁止通行。');
    expect(sentBody.voice).toBe('zh_male_qingshuangnanda_mars_bigtts');
    expect(sentBody.speed).toBe(0.82);
    expect(sentBody.instructions).toContain('Game guard');
  });

  test('keeps successful alternatives when one generation request fails', async () => {
    let calls = 0;
    const progress: string[] = [];
    globalThis.fetch = (async (input) => {
      if (String(input) === '/__ce-api__/chat') {
        return Response.json({
          success: true,
          text: JSON.stringify({ prompt: 'Heavy metal sword impact on armor; short, forceful and dry; avoid music and long reverb.' }),
        });
      }
      calls += 1;
      if (calls === 1) return Response.json({ success: false, error: 'busy' });
      return Response.json({
        success: true,
        base64: 'BQYH',
        mimeType: 'audio/mpeg',
        provider: 'elevenlabs',
      });
    }) as typeof fetch;
    const request: CreativeRequest = {
      ...voiceRequest(),
      mode: 'generate',
      kind: 'sfx',
      prompt: '金属剑命中盔甲',
      direction: '短促',
      durationSeconds: 2,
      variationCount: 2,
      voice: undefined,
    };

    const versions = await generateCreativeVersions(request, 'sfx-request', (done, total) => {
      progress.push(`${done}/${total}`);
    });
    expect(versions).toHaveLength(1);
    expect(versions[0]?.label).toBe('B');
    expect(progress).toEqual(['1/2', '2/2']);
  });

  test('saves the selected generated bytes through the extension tool', async () => {
    let sentBody: Record<string, any> = {};
    globalThis.fetch = (async (input, init) => {
      expect(String(input)).toBe('/api/tools/call');
      sentBody = JSON.parse(String(init?.body));
      return Response.json({ ok: true, result: { slug: 'demo', path: 'audio/generated/voice.mp3' } });
    }) as typeof fetch;
    const version: CreativeVersion = {
      id: 'voice-request:1',
      label: 'A',
      title: '自然演绎',
      summary: '守卫语音',
      tags: ['角色语音'],
      durationSeconds: 2,
      kind: 'voice',
      base64: 'AQIDBA==',
      mimeType: 'audio/mpeg',
      provider: 'litellm',
      model: 'doubao-tts',
    };

    const result = await saveCreativeVersionToGame(version, 'demo');
    expect(result.slug).toBe('demo');
    expect(sentBody.toolId).toBe('save-generated-audio');
    expect(sentBody.args.kind).toBe('voice');
    expect(sentBody.args.base64).toBe('AQIDBA==');
    expect(sentBody.args.provider).toBe('litellm');
  });
});
