#!/usr/bin/env node
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const scriptDir = dirname(fileURLToPath(import.meta.url))
const appRoot = resolve(scriptDir, '..', '..')
const studioRoot = resolve(appRoot, '..', '..', '..', '..', '..', '..')
const projectRoot = resolve(studioRoot, '.forgeax', 'workbench', 'wb-scene-generator', 'projects')
const inventoryPath = resolve(appRoot, 'acceptance', 'inventory', 'scene-script-battery-inventory.json')
const studioUrl = process.env.FORGEAX_STUDIO_URL ?? 'http://localhost:80'
const pluginBase = new URL(
  process.env.WB_SCENE_GENERATOR_URL ?? '/__fx-plugin/wb-scene-generator/',
  studioUrl,
).toString().replace(/\/$/, '')

const BATCHES = [
  'common',
  'basic',
  'Grid',
  'scene',
  'scenealg',
  'special',
  'alg-store',
  'components',
  'scene30',
  'group',
  'template',
] as const
type Batch = typeof BATCHES[number]

const batchOf = (category: string, kind: string): Batch => {
  if (kind === 'group' || kind === 'template') return kind
  if (category.startsWith('common/')) return 'common'
  const family = category.split('/')[1]
  if (family === 'alg_store') return 'alg-store'
  if (family === 'components') return 'components'
  if (family === 'scene30') return 'scene30'
  const candidate = family as Batch
  if (!BATCHES.includes(candidate)) throw new Error(`unsupported visual batch category: ${category}`)
  return candidate
}

const sceneIds = (batch: Batch): Record<string, string> => ({
  a: `visual_${batch.toLowerCase()}_a`,
  b: `visual_${batch.toLowerCase()}_b`,
  representative: `visual_${batch.toLowerCase()}_representative`,
  grid: `visual_${batch.toLowerCase()}_grid`,
  voxel: `visual_${batch.toLowerCase()}_voxel`,
  output: `visual_${batch.toLowerCase()}_output`,
})

function sourceFor(batch: Batch): string {
  const id = sceneIds(batch)
  const representative = {
    common: `// @scene-id ${id.representative}
const representative = basicMathOp({
  a: a,
  b: b,
  op: "+",
})`,
    basic: `// @scene-id ${id.representative}
const representative = pt2Construct({
  x: a,
  y: b,
})

// @scene-id visual_basic_explode
const inspected = pt2Explode({
  point: representative.point,
})`,
    Grid: `// @scene-id ${id.representative}
const representative = gridSize({
  grid: grid.grid,
})`,
    scene: `// @scene-id ${id.representative}
const root = emptyScene({})

// @scene-id visual_scene_add_child
const representative = addSceneChildren({
  scene: root.scene,
  nodes: [voxel.scene],
})`,
    scenealg: `// @scene-id ${id.representative}
const representative = algFieldNoise({
  region: grid.grid,
  seed: 143,
  scale: 0.25,
})`,
    special: `// @scene-id ${id.representative}
const representative = passThrough({
  input_0: a,
  input_1: b,
})`,
    'alg-store': `// @scene-id ${id.representative}
const representative = perlinNoise({
  width: a,
  height: b,
  frequency: 0.08,
  seed: 143,
})`,
    components: `// @scene-id ${id.representative}
const representative = randomRectZoneGen({
  inputGrid: grid.grid,
  count: 4,
  minSize: 2,
  maxSize: 3,
  minDistance: 1,
  seed: 143,
})`,
    scene30: `// @scene-id ${id.representative}
const representative = awPerlinNoise({
  grid: grid.grid,
  seed: 143,
})`,
    group: `// @scene-id visual_group_root
const nativeRoot = emptyScene({})

// @scene-id visual_group_asset
const nativeAsset = stringValue({ value: "Grass" })

// @scene-id ${id.representative}
const representative = tileAssetName({
  scene: nativeRoot,
  value: nativeAsset,
})`,
    template: `// @scene-id visual_template_root
const nativeRoot = emptyScene({})

// @scene-id visual_template_name
const nativeName = stringValue({ value: "Native template ground" })

// @scene-id visual_template_asset
const nativeAsset = stringValue({ value: "Grass" })

// @scene-id ${id.representative}
const representative = addBaseGrid({
  rootScene: nativeRoot,
  baseName: nativeName,
  width: a,
  height: b,
  baseAsset: nativeAsset,
})`,
  }[batch]
  const renderGrid = {
    scenealg: 'representative.field',
    'alg-store': 'representative.grid',
    components: 'representative.outputGrid',
    scene30: 'representative.grid',
  }[batch] ?? 'grid.grid'
  const renderScene = batch === 'scene'
    ? 'representative.scene'
    : batch === 'template'
      ? 'representative.rootScene'
      : 'voxel.scene'
  return `// Generated by scripts/scene-acceptance/generate-visual-projects.mts.
// The complete batch cell list is stored in ../acceptance.cells.json.

// @scene-id ${id.a}
const a = numberValue({
  value: 12,
})

// @scene-id ${id.b}
const b = numberValue({
  value: 8,
})

// @scene-id ${id.grid}
const grid = rectangularGrid({
  width: a,
  height: b,
  fillValue: 1,
})

${representative}

// @scene-id ${id.voxel}
const voxel = gridSceneNode({
  name: "Visual ${batch} batch",
  grid: ${renderGrid},
  token: "Grass",
})

// @scene-id ${id.output}
sceneOutput({
  scene: ${renderScene},
})
`
}

async function requestJson(url: string, init?: RequestInit): Promise<any> {
  const response = await fetch(url, init)
  const text = await response.text()
  const body = text ? JSON.parse(text) : null
  if (!response.ok) throw new Error(`${init?.method ?? 'GET'} ${url} -> ${response.status}: ${text}`)
  return body
}

async function main(): Promise<void> {
  const inventory = await readFile(inventoryPath, 'utf8').then(JSON.parse)
  const eligible = (inventory.entries ?? []).filter((entry: any) => entry.status !== 'retired-test-oracle')
  const selected = new Set(eligible.map((entry: any) => entry.cellId ?? entry.opId))
  if (selected.size !== 414) throw new Error(`expected all 414 eligible cells, found ${selected.size}`)
  const byBatch = Object.fromEntries(BATCHES.map((batch) => [batch, []])) as Record<Batch, any[]>
  for (const entry of inventory.entries ?? []) {
    if (selected.has(entry.cellId)) {
      const batch = batchOf(entry.category, entry.kind)
      byBatch[batch].push(entry)
    }
  }
  const mapped = BATCHES.reduce((sum, batch) => sum + byBatch[batch].length, 0)
  if (mapped !== selected.size) throw new Error(`visual batch mapping covers ${mapped}/${selected.size} cells`)

  const now = new Date().toISOString()
  const liveProjects = await requestJson(`${pluginBase}/api/v1/projects`)
  const projectIds = {} as Record<Batch, string>
  for (const batch of BATCHES) {
    const name = `Visual 414 · ${batch}`
    const existing = liveProjects.find((project: any) => project.name === name)
    const project = existing ?? await requestJson(`${pluginBase}/api/v1/projects`, {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({
        type: 'scene',
        name,
        description: `Batch visual acceptance for ${byBatch[batch].length} designated cells`,
      }),
    })
    if (!project.id) throw new Error(`project provisioning returned no id for ${batch}`)
    projectIds[batch] = project.id
  }
  const index = await readFile(resolve(projectRoot, 'index.json'), 'utf8').then(JSON.parse)
  const projects = []
  for (const batch of BATCHES) {
    const id = projectIds[batch]
    const name = `Visual 414 · ${batch}`
    const dir = resolve(projectRoot, id)
    const source = sourceFor(batch)
    const manifest = {
      schemaVersion: 1,
      id,
      type: 'scene',
      name,
      description: `Batch visual acceptance for ${byBatch[batch].length} designated cells`,
      createdAt: now,
      updatedAt: now,
      storage: {
        graphFile: `projects/${id}/state/graph.json`,
        historyFile: `projects/${id}/state/history.jsonl`,
        outputsDir: `projects/${id}/state/outputs`,
      },
    }
    await mkdir(resolve(dir, 'scene'), { recursive: true })
    await mkdir(resolve(dir, 'state'), { recursive: true })
    await Promise.all([
      writeFile(resolve(dir, 'manifest.json'), `${JSON.stringify(manifest, null, 2)}\n`),
      writeFile(resolve(dir, 'acceptance.cells.json'), `${JSON.stringify({
        schemaVersion: 1,
        batch,
        projectId: id,
        representativeCell: {
          common: 'atomic:basic_math_op',
          basic: 'atomic:pt2_construct',
          Grid: 'atomic:grid_size',
          scene: 'atomic:empty_scene',
          scenealg: 'atomic:alg_field_noise',
          special: 'atomic:pass_through',
          'alg-store': 'atomic:perlin_noise',
          components: 'atomic:random_rect_zone_gen',
          scene30: 'atomic:aw_perlin_noise',
          group: 'group:apps/wb-scene-generator/batteries/groups/scene/TileAssetName/tile-asset-name.scene.ts',
          template: 'template:apps/wb-scene-generator/batteries/templates/general/grid/AddBaseGrid/add-base-grid.scene.ts',
        }[batch],
        cells: byBatch[batch].map((entry) => ({
          cellId: entry.cellId,
          opId: entry.opId,
          functionName: entry.functionNameSuggestion,
          contractSource: entry.kind === 'atomic'
            ? entry.metaPath.replace(/meta\.json$/, 'scene.contract.ts')
            : entry.source.replace(/\.json$/, '.scene.ts'),
        })),
      }, null, 2)}\n`),
      writeFile(resolve(dir, 'scene', 'main.scene.ts'), source),
      writeFile(resolve(dir, 'state', 'history.jsonl'), ''),
    ])
    const previous = index.projects.find((project: any) => project.id === id)
    const listed = {
      id,
      type: 'scene',
      name,
      description: manifest.description,
      createdAt: previous?.createdAt ?? now,
      updatedAt: now,
    }
    index.projects = [...index.projects.filter((project: any) => project.id !== id), listed]
    projects.push({ id, name, batch, cells: byBatch[batch].map((entry) => entry.cellId), source })
  }
  await writeFile(resolve(projectRoot, 'index.json'), `${JSON.stringify(index, null, 2)}\n`)

  for (const project of projects) {
    const result = await requestJson(`${pluginBase}/api/v1/projects/${project.id}/scene-script`, {
      method: 'PUT',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({
        file: 'main.scene.ts',
        source: project.source,
        label: `Generate visual acceptance batch ${project.batch}`,
      }),
    })
    if (result.status !== 'ok') throw new Error(`compile failed for ${project.id}`)
    const executed = await requestJson(`${pluginBase}/api/v1/projects/${project.id}/execute`, {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({ quietErrors: false }),
    })
    if (executed.status !== 'completed') {
      throw new Error(`execution failed for ${project.id}: ${JSON.stringify(executed.errors ?? executed.status)}`)
    }
  }

  const output = {
    schemaVersion: 1,
    generatedAt: now,
    studioUrl,
    pluginBase,
    inventory: inventoryPath,
    cellCount: selected.size,
    projects: projects.map(({ source: _source, ...project }) => project),
  }
  const outputPath = resolve(appRoot, 'acceptance', 'visual', 'projects.json')
  await mkdir(dirname(outputPath), { recursive: true })
  await writeFile(outputPath, `${JSON.stringify(output, null, 2)}\n`)
  console.log(JSON.stringify(output, null, 2))
}

main().catch((error) => {
  console.error(error instanceof Error ? error.stack : String(error))
  process.exitCode = 1
})
