// Generated by scripts/generate-native-group-definitions.mts.
// JSON parity oracle only: batteries/templates/structures/indoor/AdaptiveRoomFurniturePlacer/AdaptiveRoomFurniturePlacer.json
// @scene-id definition:batteries.templates.structures.indoor.adaptive-room-furniture-placer.adaptive-room-furniture-placer.nested.0
const adaptiveRoomFurniturePlacerTemplateTileAssetName = defineGroup(
  {
    id: "scene.template.adaptive-room-furniture-placer.nested.0",
    version: "1.0.0",
    inputs: {
      input0: { type: Scene, runtimeType: "scene", runtimePort: "in_0", access: "item" },
      input1: { type: StringValue, runtimeType: "string", runtimePort: "in_1", access: "tree" },
    },
    outputs: {
      output0: { type: Scene, runtimeType: "scene", runtimePort: "out_0", access: "item" },
    },
  },
  ({ input0, input1 }) => {
    // @scene-id node-1790000000010-ptt9f
    const textPanel1 = textPanel({
        "$params": {"text":"asset_name","_nodeWidth":180,"_nodeHeight":67},
      })

    // @scene-id node-1790000000010-rm2fy
    const textPanel2 = textPanel({
        "$params": {"text":"asset_type","_nodeWidth":181,"_nodeHeight":60},
      })

    // @scene-id node-1790000000010-obfmb
    const textPanel3 = textPanel({
        "$params": {"text":"tile","_nodeWidth":181,"_nodeHeight":60},
      })

    // @scene-id node-1790000000010-94gxn
    const stringValue4 = stringValue({
        "value": input1,
      })

    // @scene-id node-1790000000010-4twly
    const sceneSetAttribute5 = sceneSetAttribute({
        "scene": input0,
        "key": textPanel1.output,
        "value": stringValue4.value,
      })

    // @scene-id node-1790000000010-0767k
    const sceneSetAttribute6 = sceneSetAttribute({
        "scene": sceneSetAttribute5.scene,
        "key": textPanel2.output,
        "value": textPanel3.output,
      })
    return {
      output0: sceneSetAttribute6.scene,
    }
  },
)

// @scene-id definition:batteries.templates.structures.indoor.adaptive-room-furniture-placer.adaptive-room-furniture-placer
export const adaptiveRoomFurniturePlacerTemplate = defineGroup(
  {
    id: "scene.template.adaptive-room-furniture-placer",
    version: "1.0.0",
    inputs: {
      scene: { type: Scene, runtimeType: "scene", runtimePort: "in_0", access: "tree", labelEn: "Scene" },
      assetName: { type: StringValue, runtimeType: "string", runtimePort: "in_1", labelEn: "AssetName" },
      seed: { type: NumberValue, runtimeType: "number", runtimePort: "in_2", access: "tree", labelEn: "Seed" },
      doorGrid: { type: Grid, runtimeType: "grid", runtimePort: "in_3", access: "item", labelEn: "DoorGrid" },
      furnitureList: { type: Any, runtimeType: "array", runtimePort: "in_4", access: "item", labelEn: "FurnitureList" },
      input5: { type: NumberValue, runtimeType: "number", runtimePort: "in_5", access: "item", hidden: true },
      input6: { type: NumberValue, runtimeType: "number", runtimePort: "in_6", access: "item", hidden: true },
      input7: { type: StringValue, runtimeType: "string", runtimePort: "in_7", access: "item", hidden: true },
      input8: { type: StringValue, runtimeType: "string", runtimePort: "in_8", access: "item", hidden: true },
      input9: { type: NumberList, runtimeType: "number", runtimePort: "in_9", access: "list", hidden: true },
    },
    outputs: {
      scene: { type: Scene, runtimeType: "scene", runtimePort: "out_0", access: "tree", order: 0, labelEn: "Scene" },
      furniture: { type: Scene, runtimeType: "scene", runtimePort: "out_1", access: "tree", order: 1, labelEn: "Furniture" },
      rest: { type: Scene, runtimeType: "scene", runtimePort: "out_2", access: "tree", order: 2, labelEn: "Rest" },
      furniturePath: { type: StringValue, runtimeType: "string", runtimePort: "out_3", access: "tree", order: 3, labelEn: "FurniturePath" },
      restPath: { type: StringValue, runtimeType: "string", runtimePort: "out_4", access: "tree", order: 4, labelEn: "RestPath" },
    },
  },
  ({ scene, assetName, seed, doorGrid, furnitureList, input5, input6, input7, input8, input9 }) => {
    // @scene-id node-1790000000010-c6vfi
    const scenePassthrough1 = scenePassthrough({
        "scene": scene,
      })

    // @scene-id node-1790000000010-du9e8
    const nodeExplode2 = nodeExplode({
        "scene": scenePassthrough1.scene,
      })

    // @scene-id node-1790000000010-6viw4
    const rectangularGrid3 = rectangularGrid({
        "fillValue": input5,
        "width": nodeExplode2.width,
        "height": nodeExplode2.height,
      })

    // @scene-id node-1790000000010-kej41
    const voxelSlice4 = voxelSlice({
        "z": input6,
        "voxels": nodeExplode2.voxels,
        "grid": rectangularGrid3.grid,
      })

    // @scene-id node-1790000000010-k9f8t
    const multiSeed5 = multiSeed({
        "seed": seed,
        "shape": voxelSlice4.slice,
      })

    // @scene-id node-1790000000010-h4vj0
    const adaptiveRoomFurniturePlacer6 = adaptiveRoomFurniturePlacer({
        "doorGrid": doorGrid,
        "furnitureList": furnitureList,
        "roomGrid": voxelSlice4.slice,
        "seed": multiSeed5.seed,
      })

    // @scene-id node-1790000000010-slehw
    const gridSplitByValue7 = gridSplitByValue({
        "grid": adaptiveRoomFurniturePlacer6.outputGrid,
      })

    // @scene-id node-1790000000010-i7rtn
    const strToListBranches8 = strToListBranches({
        "str": assetName,
      })

    // @scene-id node-1790000000010-tkeb1
    const gridSceneNode9 = gridSceneNode({
        "schema": input7,
        "token": input8,
        "zRange": input9,
        "grid": gridSplitByValue7.grids,
        "name": strToListBranches8.items,
      })

    // @scene-id group_1790000000010_hg1xq
    const adaptiveRoomFurniturePlacerTemplateTileAssetName10 = adaptiveRoomFurniturePlacerTemplateTileAssetName({
        "input0": gridSceneNode9.scene,
        "input1": strToListBranches8.items,
      })

    // @scene-id node-1790000000010-3eptq
    const addSceneChildren11 = addSceneChildren({
        "nodes": adaptiveRoomFurniturePlacerTemplateTileAssetName10.output0,
        "scene": scenePassthrough1.scene,
      })

    // @scene-id node-1790000000010-7vrak
    const algRegionSubtract12 = algRegionSubtract({
        "a": voxelSlice4.slice,
        "b": adaptiveRoomFurniturePlacer6.outputGrid,
      })

    // @scene-id node-1790000000010-2kmi6
    const textPanel13 = textPanel({
        "$params": {"text":"rest","_nodeWidth":172,"_nodeHeight":69},
      })

    // @scene-id node-1790000000010-6ldzn
    const gridSceneNode14 = gridSceneNode({
        "grid": algRegionSubtract12.region,
        "name": textPanel13.output,
      })

    // @scene-id node-1790000000010-ynr0v
    const addSceneChildren15 = addSceneChildren({
        "scene": addSceneChildren11.scene,
        "nodes": gridSceneNode14.scene,
      })

    // @scene-id node-1790000000010-xykwm
    const sceneMergeSubtrees16 = sceneMergeSubtrees({
        "scenes": addSceneChildren15.scene,
      })

    // @scene-id node-1790000000010-9l2e4
    const sceneFocusPath17 = sceneFocusPath({
        "scene": sceneMergeSubtrees16.scene,
        "path": addSceneChildren11.childPaths,
      })

    // @scene-id node-1790000000010-7hkpo
    const sceneFocusPath18 = sceneFocusPath({
        "scene": sceneMergeSubtrees16.scene,
        "path": addSceneChildren15.childPaths,
      })

    // @scene-id node-1790000000010-g36ob
    const scenePassthrough19 = scenePassthrough({
        "scene": sceneMergeSubtrees16.scene,
      })

    // @scene-id node-1790000000010-xgreg
    const scenePassthrough20 = scenePassthrough({
        "scene": sceneFocusPath17.scene,
      })

    // @scene-id node-1790000000010-o1ju5
    const scenePassthrough21 = scenePassthrough({
        "scene": sceneFocusPath18.scene,
      })

    // @scene-id node-1790000000010-4djdc
    const stringValue22 = stringValue({
        "value": addSceneChildren11.childPaths,
      })

    // @scene-id node-1790000000010-4kbf3
    const stringValue23 = stringValue({
        "value": addSceneChildren15.childPaths,
      })
    return {
      scene: scenePassthrough19.scene,
      furniture: scenePassthrough20.scene,
      rest: scenePassthrough21.scene,
      furniturePath: stringValue22.value,
      restPath: stringValue23.value,
    }
  },
)
