// Generated by scripts/generate-native-group-definitions.mts.
// JSON parity oracle only: batteries/templates/scene/PlaceOneDecoration/PlaceOneDecoration.json
// @scene-id definition:batteries.templates.scene.place-one-decoration.place-one-decoration.nested.0
const placeOneDecorationObjectAssetName = defineGroup(
  {
    id: "scene.template.place-one-decoration.nested.0",
    version: "1.0.0",
    inputs: {
      input0: { type: Scene, runtimeType: "scene", runtimePort: "in_0", access: "item" },
      input1: { type: StringValue, runtimeType: "string", runtimePort: "in_1", access: "tree" },
    },
    outputs: {
      output0: { type: Scene, runtimeType: "scene", runtimePort: "out_0", access: "item" },
    },
  },
  ({ input0, input1 }) => {
    // @scene-id node-1781805836833-u0n1m
    const textPanel1 = textPanel({
        "$params": {"text":"asset_name","_nodeWidth":180,"_nodeHeight":67},
      })

    // @scene-id node-1781805836833-h5dc1
    const textPanel2 = textPanel({
        "$params": {"text":"asset_type","_nodeWidth":181,"_nodeHeight":60},
      })

    // @scene-id node-1781805836833-xzhe4
    const textPanel3 = textPanel({
        "$params": {"text":"object","_nodeWidth":181,"_nodeHeight":60},
      })

    // @scene-id node-1781805836833-4mlss
    const stringValue4 = stringValue({
        "value": input1,
      })

    // @scene-id node-1781805836833-3ffrb
    const sceneSetAttribute5 = sceneSetAttribute({
        "scene": input0,
        "key": textPanel1.output,
        "value": stringValue4.value,
      })

    // @scene-id node-1781805836833-g4ali
    const sceneSetAttribute6 = sceneSetAttribute({
        "scene": sceneSetAttribute5.scene,
        "key": textPanel2.output,
        "value": textPanel3.output,
      })
    return {
      output0: sceneSetAttribute6.scene,
    }
  },
)

// @scene-id definition:batteries.templates.scene.place-one-decoration.place-one-decoration
export const placeOneDecoration = defineGroup(
  {
    id: "scene.template.place-one-decoration",
    version: "1.0.0",
    inputs: {
      point: { type: Point2d, runtimeType: "point2d", runtimePort: "in_3", access: "item", order: 1, labelEn: "Point" },
      footprintWidth: { type: NumberValue, runtimeType: "number", runtimePort: "in_5", hidden: false, order: 2, labelEn: "FootprintWidth" },
      footprintHeight: { type: NumberValue, runtimeType: "number", runtimePort: "in_6", hidden: false, order: 3, labelEn: "FootprintHeight" },
      scene: { type: Scene, runtimeType: "scene", runtimePort: "in_1", access: "tree", order: 0, labelEn: "Scene" },
      input4: { type: NumberValue, runtimeType: "number", runtimePort: "in_7", access: "item", hidden: true, order: 4 },
      input5: { type: NumberValue, runtimeType: "number", runtimePort: "in_8", access: "item", hidden: true, order: 5 },
      input6: { type: StringValue, runtimeType: "string", runtimePort: "in_9", access: "item", hidden: true, order: 6 },
      input7: { type: StringValue, runtimeType: "string", runtimePort: "in_10", access: "item", hidden: true, order: 7 },
      input8: { type: NumberList, runtimeType: "number", runtimePort: "in_11", access: "list", hidden: true, order: 8 },
      decorationName: { type: StringValue, runtimeType: "string", runtimePort: "in_0", access: "item", order: 10, labelEn: "DecorationName" },
      input10: { type: StringValue, runtimeType: "string", runtimePort: "in_12", access: "item", hidden: true, order: 11 },
      input11: { type: StringValue, runtimeType: "string", runtimePort: "in_13", access: "item", hidden: true, order: 12 },
      decorationAsset: { type: StringValue, runtimeType: "string", runtimePort: "in_4", access: "tree", order: 13, labelEn: "DecorationAsset" },
      input13: { type: StringValue, runtimeType: "string", runtimePort: "in_15", access: "tree", hidden: true, order: 14 },
      decorationHeight: { type: NumberValue, runtimeType: "number", runtimePort: "in_2", access: "tree", order: 9, labelEn: "DecorationHeight" },
      input15: { type: StringValue, runtimeType: "string", runtimePort: "in_16", access: "tree", hidden: true, order: 15 },
      input16: { type: NumberValue, runtimeType: "number", runtimePort: "in_17", access: "item", hidden: true, order: 16 },
      input17: { type: StringValue, runtimeType: "string", runtimePort: "in_18", access: "item", hidden: true, order: 17 },
    },
    outputs: {
      decoration: { type: Scene, runtimeType: "scene", runtimePort: "out_1", access: "tree", order: 1, labelEn: "Decoration" },
      scene: { type: Scene, runtimeType: "scene", runtimePort: "out_0", access: "tree", order: 0, labelEn: "Scene" },
      rest: { type: Scene, runtimeType: "scene", runtimePort: "out_2", access: "tree", order: 3, labelEn: "Rest" },
      decorationPath: { type: StringValue, runtimeType: "string", runtimePort: "out_3", access: "tree", order: 2, labelEn: "DecorationPath" },
      restPath: { type: StringValue, runtimeType: "string", runtimePort: "out_4", access: "tree", order: 4, labelEn: "RestPath" },
    },
  },
  ({ point, footprintWidth, footprintHeight, scene, input4, input5, input6, input7, input8, decorationName, input10, input11, decorationAsset, input13, decorationHeight, input15, input16, input17 }) => {
    // @scene-id node-1781805836833-fu5ot
    const scenePassthrough1 = scenePassthrough({
        "scene": scene,
      })

    // @scene-id node-1781805836833-iy741
    const nodeExplode2 = nodeExplode({
        "scene": scenePassthrough1.scene,
      })

    // @scene-id node-1781805836833-p7d6q
    const rectangularGrid3 = rectangularGrid({
        "fillValue": input4,
        "width": nodeExplode2.width,
        "height": nodeExplode2.height,
      })

    // @scene-id node-1781805836833-whm0s
    const voxelSlice4 = voxelSlice({
        "z": input5,
        "voxels": nodeExplode2.voxels,
        "grid": rectangularGrid3.grid,
      })

    // @scene-id node-1781805836833-hkup3
    const algPoint2rect5 = algPoint2rect({
        "point": point,
        "width": footprintWidth,
        "height": footprintHeight,
        "region": voxelSlice4.slice,
      })

    // @scene-id node-1781805836833-kkd2s
    const algRegionSubtract6 = algRegionSubtract({
        "a": voxelSlice4.slice,
        "b": algPoint2rect5.outputGrid,
      })

    // @scene-id node-1781805836833-c3stp
    const textPanel7 = textPanel({
        "$params": {"text":"rest","_nodeWidth":180,"_nodeHeight":60},
      })

    // @scene-id node-1781805836833-svucq
    const gridSceneNode8 = gridSceneNode({
        "schema": input6,
        "token": input7,
        "zRange": input8,
        "grid": algRegionSubtract6.region,
        "name": textPanel7.output,
      })

    // @scene-id node-1781805995994
    const numberValue9 = numberValue({
        "$params": {"value":1},
      })

    // @scene-id node-1781806015145
    const basicMathOp10 = basicMathOp({
        "$params": {"op":"+"},
        "op": input13,
        "b": numberValue9.value,
        "a": voxelSlice4.z,
      })

    // @scene-id node-1781806132314
    const typeNumber11 = typeNumber({
        "value": decorationHeight,
      })

    // @scene-id node-1781806142682
    const basicMathOp12 = basicMathOp({
        "$params": {"op":"+"},
        "op": input15,
        "b": typeNumber11.value,
        "a": voxelSlice4.z,
      })

    // @scene-id node-1781806760754
    const rangeList13 = rangeList({
        "step": input16,
        "prefix": input17,
        "start": basicMathOp10.result,
        "end": basicMathOp12.result,
      })

    // @scene-id node-1781805836833-foby6
    const gridSceneNode14 = gridSceneNode({
        "name": decorationName,
        "schema": input10,
        "token": input11,
        "zRange": rangeList13.list,
        "grid": algPoint2rect5.outputGrid,
      })

    // @scene-id group_1783000010000_oan1
    const placeOneDecorationObjectAssetName15 = placeOneDecorationObjectAssetName({
        "input1": decorationAsset,
        "input0": gridSceneNode14.scene,
      })

    // @scene-id node-1781805836833-f33b0
    const addSceneChildren16 = addSceneChildren({
        "nodes": placeOneDecorationObjectAssetName15.output0,
        "scene": scenePassthrough1.scene,
      })

    // @scene-id node-1781805836833-mb7dn
    const addSceneChildren17 = addSceneChildren({
        "scene": addSceneChildren16.scene,
        "nodes": gridSceneNode8.scene,
      })

    // @scene-id node-1781805836833-e7154
    const sceneMergeSubtrees18 = sceneMergeSubtrees({
        "scenes": addSceneChildren17.scene,
      })

    // @scene-id node-1781805836833-ryf07
    const scenePassthrough19 = scenePassthrough({
        "scene": sceneMergeSubtrees18.scene,
      })

    // @scene-id node-1781805836833-do9u6
    const scenePassthrough20 = scenePassthrough({
        "scene": sceneMergeSubtrees18.scene,
      })

    // @scene-id node-1781805836833-gc0m6
    const sceneFocusPath21 = sceneFocusPath({
        "path": addSceneChildren17.childPaths,
        "scene": sceneMergeSubtrees18.scene,
      })

    // @scene-id node-1781805836833-vvw0b
    const scenePassthrough22 = scenePassthrough({
        "scene": sceneFocusPath21.scene,
      })

    // @scene-id node-1781805836833-94hcq
    const stringValue23 = stringValue({
        "value": addSceneChildren16.childPaths,
      })

    // @scene-id node-1781805836833-iuc47
    const stringValue24 = stringValue({
        "value": addSceneChildren17.childPaths,
      })
    return {
      decoration: scenePassthrough19.scene,
      scene: scenePassthrough20.scene,
      rest: scenePassthrough22.scene,
      decorationPath: stringValue23.value,
      restPath: stringValue24.value,
    }
  },
)
