/**
 * build-skills.ts (C3)
 * ─────────────────────────────────────────────────────────────────
 * 编译期把 skills/<tier>/presets/*.md 内容 inline 进 ts 索引。
 *
 * 目前 P0 阶段：跑这个脚本会扫描 skills/<tier>/ 下所有 *.skill.ts，
 * 把同目录的 *.md 文件内容（按 ## section）切片填入 stepSkills。
 *
 * 若 .skill.ts 已经手写填好（tier4-presets 的方式），脚本会跳过它。
 *
 * 用法：
 *   npx tsx packages/narrative-studio/scripts/build-skills.ts
 *
 * 设计说明：dev 模式下 ts 索引文件可以直接 import，无需运行此脚本。
 * 该脚本主要服务于：
 *   1. 一次性把作者写的 md 转换为初版 ts skill
 *   2. CI 中确保 md 与 ts 同步
 */
import { readdir, readFile, writeFile, stat } from "node:fs/promises";
import { join, basename } from "node:path";

const SKILLS_ROOT = join(
  import.meta.dirname ?? new URL(".", import.meta.url).pathname,
  "../src/knowledge/game-narrative/skills",
);

interface MarkdownSkill {
  frontmatter: Record<string, unknown>;
  sections: Record<string, string>;
}

function parseMarkdown(content: string): MarkdownSkill {
  const fm: Record<string, unknown> = {};
  const sections: Record<string, string> = {};
  let body = content;

  const fmMatch = content.match(/^---\n([\s\S]*?)\n---\n/);
  if (fmMatch) {
    body = content.slice(fmMatch[0].length);
    for (const line of fmMatch[1].split("\n")) {
      const m = line.match(/^([\w_]+):\s*(.+)$/);
      if (m) {
        const v = m[2].trim();
        if (v.startsWith("[") && v.endsWith("]")) {
          fm[m[1]] = v.slice(1, -1).split(",").map((s) => s.trim().replace(/^["']|["']$/g, ""));
        } else {
          fm[m[1]] = v.replace(/^["']|["']$/g, "");
        }
      }
    }
  }

  let currentSection: string | null = null;
  let buffer: string[] = [];
  for (const line of body.split("\n")) {
    const sec = line.match(/^##\s+(\w+)\s*skill\s*$/i);
    if (sec) {
      if (currentSection) sections[currentSection] = buffer.join("\n").trim();
      currentSection = sec[1];
      buffer = [];
    } else if (currentSection) {
      buffer.push(line);
    }
  }
  if (currentSection) sections[currentSection] = buffer.join("\n").trim();
  return { frontmatter: fm, sections };
}

async function processDirectory(dir: string): Promise<void> {
  let entries;
  try {
    entries = await readdir(dir);
  } catch {
    return;
  }

  for (const name of entries) {
    const fp = join(dir, name);
    const s = await stat(fp);
    if (s.isDirectory()) {
      await processDirectory(fp);
      continue;
    }
    if (!name.endsWith(".md")) continue;
    if (name === "SKILL.md" || name === "pipeline-config.md") continue;

    const tsName = name.replace(/\.md$/, ".skill.ts");
    const tsPath = join(dir, tsName);
    let exists = false;
    try { await stat(tsPath); exists = true; } catch { /* not exist */ }
    if (exists) continue;

    const content = await readFile(fp, "utf-8");
    const parsed = parseMarkdown(content);
    const genreCode = parsed.frontmatter.genreCode ?? basename(name, ".md");
    const tier = parsed.frontmatter.tier ?? "tier1";
    const keywords = parsed.frontmatter.matchKeywords ?? [];
    const enableSteps = parsed.frontmatter.enableSteps ?? [];

    const stepEntries = Object.entries(parsed.sections)
      .map(([step, body]) =>
        `  ${JSON.stringify(step)}: { systemPromptAddition: ${JSON.stringify(body)} },`)
      .join("\n");

    const tsContent = `// AUTO-GENERATED by scripts/build-skills.ts. Edit the .md file instead.
import { registerSkill } from "../../../skill-loader.js";
import type { NarrativeSkill } from "../../../skill-types.js";

export const SKILL: NarrativeSkill = {
  genreCode: ${JSON.stringify(genreCode)},
  tier: ${JSON.stringify(tier)},
  matchKeywords: ${JSON.stringify(keywords)},
  enableSteps: ${JSON.stringify(enableSteps)},
  stepSkills: {
${stepEntries}
  },
};

registerSkill(SKILL);
`;
    await writeFile(tsPath, tsContent, "utf-8");
    console.log(`✓ ${tsPath}`);
  }
}

async function main(): Promise<void> {
  console.log(`[build-skills] Scanning ${SKILLS_ROOT}`);
  await processDirectory(SKILLS_ROOT);
  console.log("[build-skills] done");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
