// Generated by scripts/generate-native-group-definitions.mts.
// JSON parity oracle only: batteries/templates/structures/districts/AreaPartition/AreaPartition.json
// @scene-id definition:batteries.templates.structures.districts.area-partition.area-partition.nested.0
const areaPartitionTileAssetName = defineGroup(
  {
    id: "scene.template.area-partition.nested.0",
    version: "1.0.0",
    inputs: {
      input0: { type: Scene, runtimeType: "scene", runtimePort: "in_0", access: "item" },
      input1: { type: StringValue, runtimeType: "string", runtimePort: "in_1", access: "tree" },
    },
    outputs: {
      output0: { type: Scene, runtimeType: "scene", runtimePort: "out_0", access: "item" },
    },
  },
  ({ input0, input1 }) => {
    // @scene-id aptz_tp_name
    const textPanel1 = textPanel({
        "$params": {"text":"asset_name","_nodeWidth":180,"_nodeHeight":67},
      })

    // @scene-id aptz_tp_type
    const textPanel2 = textPanel({
        "$params": {"text":"asset_type","_nodeWidth":181,"_nodeHeight":60},
      })

    // @scene-id aptz_tp_tile
    const textPanel3 = textPanel({
        "$params": {"text":"tile","_nodeWidth":181,"_nodeHeight":60},
      })

    // @scene-id aptz_str
    const stringValue4 = stringValue({
        "value": input1,
      })

    // @scene-id aptz_set1
    const sceneSetAttribute5 = sceneSetAttribute({
        "scene": input0,
        "key": textPanel1.output,
        "value": stringValue4.value,
      })

    // @scene-id aptz_set2
    const sceneSetAttribute6 = sceneSetAttribute({
        "scene": sceneSetAttribute5.scene,
        "key": textPanel2.output,
        "value": textPanel3.output,
      })
    return {
      output0: sceneSetAttribute6.scene,
    }
  },
)

// @scene-id definition:batteries.templates.structures.districts.area-partition.area-partition
export const areaPartition = defineGroup(
  {
    id: "scene.template.area-partition",
    version: "1.0.0",
    inputs: {
      scene: { type: Scene, runtimeType: "scene", runtimePort: "in_0", access: "tree", labelEn: "Scene" },
      points: { type: Point2d, runtimeType: "point2d", runtimePort: "in_1", access: "list", labelEn: "Points" },
      areas: { type: NumberList, runtimeType: "number", runtimePort: "in_2", access: "list", labelEn: "Areas" },
      zoneNames: { type: StringValue, runtimeType: "string", runtimePort: "in_3", access: "tree", labelEn: "ZoneNames" },
      zoneAssets: { type: StringValue, runtimeType: "string", runtimePort: "in_4", access: "tree", labelEn: "ZoneAssets" },
      seed: { type: NumberValue, runtimeType: "number", runtimePort: "in_5", access: "tree", labelEn: "Seed" },
      boundaryStyle: { type: StringValue, runtimeType: "string", runtimePort: "in_6", access: "item", labelEn: "BoundaryStyle" },
      relaxIterations: { type: NumberValue, runtimeType: "number", runtimePort: "in_7", access: "item", labelEn: "RelaxIterations" },
      smoothIterations: { type: NumberValue, runtimeType: "number", runtimePort: "in_8", access: "item", labelEn: "SmoothIterations" },
      input9: { type: NumberValue, runtimeType: "number", runtimePort: "in_10", access: "item", hidden: true },
      input10: { type: NumberValue, runtimeType: "number", runtimePort: "in_11", access: "item", hidden: true },
      input11: { type: StringValue, runtimeType: "string", runtimePort: "in_12", access: "item", hidden: true },
      input12: { type: StringValue, runtimeType: "string", runtimePort: "in_13", access: "item", hidden: true },
      input13: { type: NumberList, runtimeType: "number", runtimePort: "in_14", access: "list", hidden: true },
    },
    outputs: {
      scene: { type: Scene, runtimeType: "scene", runtimePort: "out_0", access: "tree", order: 0, labelEn: "Scene" },
      zones: { type: Scene, runtimeType: "scene", runtimePort: "out_1", access: "tree", order: 1, labelEn: "Zones" },
      zonesPath: { type: StringValue, runtimeType: "string", runtimePort: "out_2", access: "tree", order: 2, labelEn: "ZonesPath" },
    },
  },
  ({ scene, points, areas, zoneNames, zoneAssets, seed, boundaryStyle, relaxIterations, smoothIterations, input9, input10, input11, input12, input13 }) => {
    // @scene-id ap_in
    const scenePassthrough1 = scenePassthrough({
        "scene": scene,
      })

    // @scene-id ap_explode
    const nodeExplode2 = nodeExplode({
        "scene": scenePassthrough1.scene,
      })

    // @scene-id ap_rgrid
    const rectangularGrid3 = rectangularGrid({
        "fillValue": input9,
        "width": nodeExplode2.width,
        "height": nodeExplode2.height,
      })

    // @scene-id ap_slice
    const voxelSlice4 = voxelSlice({
        "z": input10,
        "voxels": nodeExplode2.voxels,
        "grid": rectangularGrid3.grid,
      })

    // @scene-id ap_seed
    const multiSeed5 = multiSeed({
        "seed": seed,
        "shape": voxelSlice4.slice,
      })

    // @scene-id ap_areas
    const textPanel6 = textPanel({
        "$params": {"text":"[3,2,1.5,1]","_nodeWidth":160,"_nodeHeight":76},
      })

    // @scene-id ap_boundary
    const textPanel7 = textPanel({
        "$params": {"text":"organic","_nodeWidth":160,"_nodeHeight":76},
      })

    // @scene-id ap_relax
    const numberValue8 = numberValue({
        "$params": {"value":8},
      })

    // @scene-id ap_smooth
    const numberValue9 = numberValue({
        "$params": {"value":12},
      })

    // @scene-id ap_partition
    const algRegionAreaPartition10 = algRegionAreaPartition({
        "points": points,
        "areas": [areas, textPanel6.output],
        "boundaryStyle": [boundaryStyle, textPanel7.output],
        "relaxIterations": [relaxIterations, numberValue8.value],
        "smoothIterations": [smoothIterations, numberValue9.value],
        "region": voxelSlice4.slice,
        "seed": multiSeed5.seed,
      })

    // @scene-id ap_g2n
    const gridSceneNode11 = gridSceneNode({
        "name": zoneNames,
        "schema": input11,
        "token": input12,
        "zRange": input13,
        "grid": algRegionAreaPartition10.partition,
      })

    // @scene-id ap_tile
    const areaPartitionTileAssetName12 = areaPartitionTileAssetName({
        "input1": zoneAssets,
        "input0": gridSceneNode11.scene,
      })

    // @scene-id ap_add_zones
    const addSceneChildren13 = addSceneChildren({
        "nodes": areaPartitionTileAssetName12.output0,
        "scene": scenePassthrough1.scene,
      })

    // @scene-id ap_focus_zones
    const sceneFocusPath14 = sceneFocusPath({
        "scene": addSceneChildren13.scene,
        "path": addSceneChildren13.childPaths,
      })

    // @scene-id ap_out_main
    const scenePassthrough15 = scenePassthrough({
        "scene": addSceneChildren13.scene,
      })

    // @scene-id ap_out_zones
    const scenePassthrough16 = scenePassthrough({
        "scene": sceneFocusPath14.scene,
      })

    // @scene-id ap_zpath
    const stringValue17 = stringValue({
        "value": addSceneChildren13.childPaths,
      })
    return {
      scene: scenePassthrough15.scene,
      zones: scenePassthrough16.scene,
      zonesPath: stringValue17.value,
    }
  },
)
