// Generated by scripts/generate-native-group-definitions.mts.
// JSON parity oracle only: batteries/groups/scene/LakeRegions/LakeRegions.json
// @scene-id definition:batteries.groups.scene.lake-regions.lake-regions.nested.0
const lakeRegionsMultiNames = defineGroup(
  {
    id: "scene.group.scene.lake-regions.lake-regions.nested.0",
    version: "1.0.0",
    inputs: {
      input0: { type: StringValue, runtimeType: "string", runtimePort: "in_0", access: "tree", hidden: true },
      count: { type: NumberValue, runtimeType: "number", runtimePort: "in_1", access: "tree", labelEn: "Count" },
      input2: { type: NumberValue, runtimeType: "number", runtimePort: "in_2", access: "item", hidden: true },
      prefix: { type: StringValue, runtimeType: "string", runtimePort: "in_3", access: "tree", labelEn: "Prefix" },
    },
    outputs: {
      output0: { type: NumberList, runtimeType: "number", runtimePort: "out_0", access: "list", hidden: true },
      names: { type: StringList, runtimeType: "string", runtimePort: "out_1", access: "list", labelEn: "Names" },
      output2: { type: NumberValue, runtimeType: "number", runtimePort: "out_2", access: "item" },
    },
  },
  ({ input0, count, input2, prefix }) => {
    // @scene-id node-1782131359609-omr0e
    const numberValue1 = numberValue({})

    // @scene-id node-1782131359609-u3dxn
    const numberValue2 = numberValue({
        "$params": {"value":1},
      })

    // @scene-id node-1782131359609-gywdf
    const typeNumber3 = typeNumber({
        "value": count,
      })

    // @scene-id node-1782131359609-j52qp
    const basicMathOp4 = basicMathOp({
        "$params": {"op":"-"},
        "op": input0,
        "b": numberValue2.value,
        "a": typeNumber3.value,
      })

    // @scene-id node-1782131359609-3q1gh
    const stringValue5 = stringValue({
        "value": prefix,
      })

    // @scene-id node-1782131359609-to5xz
    const rangeList6 = rangeList({
        "step": input2,
        "start": numberValue1.value,
        "end": basicMathOp4.result,
        "prefix": stringValue5.value,
      })
    return {
      output0: rangeList6.list,
      names: rangeList6.stringList,
      output2: rangeList6.count,
    }
  },
)

// @scene-id definition:batteries.groups.scene.lake-regions.lake-regions.nested.1
const lakeRegionsTileAssetName = defineGroup(
  {
    id: "scene.group.scene.lake-regions.lake-regions.nested.1",
    version: "1.0.0",
    inputs: {
      input0: { type: Scene, runtimeType: "scene", runtimePort: "in_0", access: "item" },
      input1: { type: StringValue, runtimeType: "string", runtimePort: "in_1", access: "tree" },
    },
    outputs: {
      output0: { type: Scene, runtimeType: "scene", runtimePort: "out_0", access: "item" },
    },
  },
  ({ input0, input1 }) => {
    // @scene-id node-1782131359609-h7k8n
    const textPanel1 = textPanel({
        "$params": {"text":"asset_name","_nodeWidth":180,"_nodeHeight":67},
      })

    // @scene-id node-1782131359609-afu19
    const textPanel2 = textPanel({
        "$params": {"text":"asset_type","_nodeWidth":181,"_nodeHeight":60},
      })

    // @scene-id node-1782131359609-e7eau
    const textPanel3 = textPanel({
        "$params": {"text":"tile","_nodeWidth":181,"_nodeHeight":60},
      })

    // @scene-id node-1782131359609-q6gtv
    const stringValue4 = stringValue({
        "value": input1,
      })

    // @scene-id node-1782131359609-q6rfx
    const sceneSetAttribute5 = sceneSetAttribute({
        "scene": input0,
        "key": textPanel1.output,
        "value": stringValue4.value,
      })

    // @scene-id node-1782131359609-av90h
    const sceneSetAttribute6 = sceneSetAttribute({
        "scene": sceneSetAttribute5.scene,
        "key": textPanel2.output,
        "value": textPanel3.output,
      })
    return {
      output0: sceneSetAttribute6.scene,
    }
  },
)

// @scene-id definition:batteries.groups.scene.lake-regions.lake-regions
export const lakeRegions = defineGroup(
  {
    id: "scene.group.scene.lake-regions.lake-regions",
    version: "1.0.0",
    inputs: {
      scene: { type: Scene, runtimeType: "scene", runtimePort: "in_1", access: "tree", labelEn: "Scene" },
      input1: { type: NumberValue, runtimeType: "number", runtimePort: "in_3", access: "item", hidden: true },
      input2: { type: NumberValue, runtimeType: "number", runtimePort: "in_4", access: "item", hidden: true },
      input3: { type: StringValue, runtimeType: "string", runtimePort: "in_5", hidden: true },
      input4: { type: StringValue, runtimeType: "string", runtimePort: "in_6", hidden: true },
      input5: { type: NumberValue, runtimeType: "number", runtimePort: "in_7", hidden: true },
      input6: { type: NumberValue, runtimeType: "number", runtimePort: "in_8", hidden: true },
      input7: { type: NumberValue, runtimeType: "number", runtimePort: "in_9", hidden: true },
      input8: { type: NumberValue, runtimeType: "number", runtimePort: "in_10", hidden: true },
      input9: { type: NumberValue, runtimeType: "number", runtimePort: "in_11", hidden: true },
      input10: { type: StringValue, runtimeType: "string", runtimePort: "in_12", access: "item", hidden: true },
      input11: { type: StringValue, runtimeType: "string", runtimePort: "in_13", access: "item", hidden: true },
      namePrefix: { type: StringValue, runtimeType: "string", runtimePort: "in_0", access: "tree", labelEn: "NamePrefix" },
      assetName: { type: StringValue, runtimeType: "string", runtimePort: "in_14", access: "tree", labelEn: "AssetName" },
      input14: { type: StringValue, runtimeType: "string", runtimePort: "in_15", access: "item", hidden: true },
      input15: { type: StringValue, runtimeType: "string", runtimePort: "in_16", access: "item", hidden: true },
      points: { type: Point2d, runtimeType: "point2d", runtimePort: "in_2", access: "list", labelEn: "Points" },
      input17: { type: NumberValue, runtimeType: "number", runtimePort: "in_17", access: "tree" },
    },
    outputs: {
      output0: { type: Grid, runtimeType: "grid", runtimePort: "out_1", access: "item", hidden: true, order: 0 },
      output1: { type: NumberValue, runtimeType: "number", runtimePort: "out_2", access: "item", hidden: true, order: 1 },
      scene: { type: Scene, runtimeType: "scene", runtimePort: "out_3", access: "tree", order: 2, labelEn: "Scene" },
      lake: { type: Scene, runtimeType: "scene", runtimePort: "out_4", access: "tree", order: 3, labelEn: "Lake" },
      lakePath: { type: StringValue, runtimeType: "string", runtimePort: "out_5", access: "tree", order: 4, labelEn: "LakePath" },
      rest: { type: Scene, runtimeType: "scene", runtimePort: "out_0", access: "tree", order: 5, labelEn: "Rest" },
      restPath: { type: StringValue, runtimeType: "string", runtimePort: "out_6", access: "tree", order: 6, labelEn: "RestPath" },
    },
  },
  ({ scene, input1, input2, input3, input4, input5, input6, input7, input8, input9, input10, input11, namePrefix, assetName, input14, input15, points, input17 }) => {
    // @scene-id node-1782131359609-sx6f4
    const scenePassthrough1 = scenePassthrough({
        "scene": scene,
      })

    // @scene-id node-1782131359609-o2et8
    const nodeExplode2 = nodeExplode({
        "scene": scenePassthrough1.scene,
      })

    // @scene-id node-1782131359609-1hz2x
    const rectangularGrid3 = rectangularGrid({
        "fillValue": input1,
        "width": nodeExplode2.width,
        "height": nodeExplode2.height,
      })

    // @scene-id node-1782131359609-isd22
    const voxelSlice4 = voxelSlice({
        "z": input2,
        "voxels": nodeExplode2.voxels,
        "grid": rectangularGrid3.grid,
      })

    // @scene-id node-1782131359609-ykrkl
    const textPanel5 = textPanel({
        "$params": {"text":"rest","_nodeWidth":172,"_nodeHeight":69},
      })

    // @scene-id node-1782131359609-d727o
    const numberValue6 = numberValue({
        "$params": {"value":3},
      })

    // @scene-id node-1782131359609-b4dds
    const numberValue7 = numberValue({
        "$params": {"value":50},
      })

    // @scene-id node-1782131359609-thp72
    const multiSeed8 = multiSeed({
        "seed": input17,
        "shape": voxelSlice4.slice,
      })

    // @scene-id node-1782131359609-49eti
    const algPointsScatter9 = algPointsScatter({
        "mode": input3,
        "countMode": input4,
        "density": input5,
        "count": input6,
        "targetValue": input7,
        "region": voxelSlice4.slice,
        "minSpacing": numberValue6.value,
        "seed": multiSeed8.seed,
      })

    // @scene-id node-1782131680512-h78ck
    const voxelRange10 = voxelRange({
        "voxels": nodeExplode2.voxels,
      })

    // @scene-id node-1782133215383
    const numberValue11 = numberValue({
        "$params": {"value":1},
      })

    // @scene-id node-1782132974315-uwxy5
    const algPoints2rects12 = algPoints2rects({
        "points": points,
        "region": voxelSlice4.slice,
        "widths": numberValue11.value,
        "heights": numberValue11.value,
      })

    // @scene-id node-1782133201818
    const algRegionUnionAll13 = algRegionUnionAll({
        "regions": algPoints2rects12.rects,
      })

    // @scene-id node-1782131359609-jv8ko
    const algRegionFloodGrow14 = algRegionFloodGrow({
        "sizeVariance": input8,
        "spacingDilate": input9,
        "region": voxelSlice4.slice,
        "size": numberValue7.value,
        "seed": multiSeed8.seed,
        "points": algRegionUnionAll13.region,
      })

    // @scene-id group_1782131359609_2zptk
    const lakeRegionsMultiNames15 = lakeRegionsMultiNames({
        "prefix": namePrefix,
        "count": algRegionFloodGrow14.count,
      })

    // @scene-id node-1782131359609-9qory
    const gridSceneNode16 = gridSceneNode({
        "schema": input10,
        "token": input11,
        "name": lakeRegionsMultiNames15.names,
        "grid": algRegionFloodGrow14.partition,
        "zRange": voxelSlice4.z,
      })

    // @scene-id group_1782131359609_wszan
    const lakeRegionsTileAssetName17 = lakeRegionsTileAssetName({
        "input1": assetName,
        "input0": gridSceneNode16.scene,
      })

    // @scene-id node-1782131359609-dbvbi
    const addSceneChildren18 = addSceneChildren({
        "nodes": lakeRegionsTileAssetName17.output0,
        "scene": scenePassthrough1.scene,
      })

    // @scene-id node-1782131359609-8swac
    const algRegionUnionAll19 = algRegionUnionAll({
        "regions": algRegionFloodGrow14.partition,
      })

    // @scene-id node-1782131359609-l427s
    const algRegionSubtract20 = algRegionSubtract({
        "a": voxelSlice4.slice,
        "b": algRegionUnionAll19.region,
      })

    // @scene-id node-1782131359609-32iqx
    const gridSceneNode21 = gridSceneNode({
        "schema": input14,
        "token": input15,
        "name": textPanel5.output,
        "grid": algRegionSubtract20.region,
        "zRange": voxelRange10.zRange,
      })

    // @scene-id node-1782131359609-26jsa
    const addSceneChildren22 = addSceneChildren({
        "scene": addSceneChildren18.scene,
        "nodes": gridSceneNode21.scene,
      })

    // @scene-id node-1782131359609-okeg8
    const sceneMergeSubtrees23 = sceneMergeSubtrees({
        "scenes": addSceneChildren22.scene,
      })

    // @scene-id node-1782131359609-phl7u
    const sceneFocusPath24 = sceneFocusPath({
        "path": addSceneChildren18.childPaths,
        "scene": sceneMergeSubtrees23.scene,
      })

    // @scene-id node-1782131359609-2p8qc
    const scenePassthrough25 = scenePassthrough({
        "scene": sceneMergeSubtrees23.scene,
      })

    // @scene-id node-1782131359609-k8c24
    const sceneFocusPath26 = sceneFocusPath({
        "path": addSceneChildren22.childPaths,
        "scene": sceneMergeSubtrees23.scene,
      })

    // @scene-id node-1782131359609-kjan9
    const scenePassthrough27 = scenePassthrough({
        "scene": sceneFocusPath24.scene,
      })

    // @scene-id node-1782131359609-ghrgu
    const scenePassthrough28 = scenePassthrough({
        "scene": sceneFocusPath26.scene,
      })

    // @scene-id node-1782131359609-55hn2
    const stringValue29 = stringValue({
        "value": addSceneChildren18.childPaths,
      })

    // @scene-id node-1782131359609-9kma1
    const stringValue30 = stringValue({
        "value": addSceneChildren22.childPaths,
      })
    return {
      output0: algPointsScatter9.points,
      output1: algPointsScatter9.count,
      scene: scenePassthrough25.scene,
      lake: scenePassthrough27.scene,
      lakePath: stringValue29.value,
      rest: scenePassthrough28.scene,
      restPath: stringValue30.value,
    }
  },
)
