// Generated by scripts/generate-native-group-definitions.mts.
// JSON parity oracle only: batteries/templates/scene/BuildingStructures/BuildingStructures.json
// @scene-id definition:batteries.templates.scene.building-structures.building-structures.nested.0
const buildingStructuresTileAssetName = defineGroup(
  {
    id: "scene.template.building-structures.nested.0",
    version: "1.0.0",
    inputs: {
      input0: { type: Scene, runtimeType: "scene", runtimePort: "in_0", access: "item" },
      input1: { type: StringValue, runtimeType: "string", runtimePort: "in_1", access: "tree" },
    },
    outputs: {
      output0: { type: Scene, runtimeType: "scene", runtimePort: "out_0", access: "item" },
    },
  },
  ({ input0, input1 }) => {
    // @scene-id node-1781855286085-ehwas
    const textPanel1 = textPanel({
        "$params": {"text":"asset_name","_nodeWidth":180,"_nodeHeight":67},
      })

    // @scene-id node-1781855286085-rgux2
    const textPanel2 = textPanel({
        "$params": {"text":"asset_type","_nodeWidth":181,"_nodeHeight":60},
      })

    // @scene-id node-1781855286085-mo321
    const textPanel3 = textPanel({
        "$params": {"text":"tile","_nodeWidth":181,"_nodeHeight":60},
      })

    // @scene-id node-1781855286085-wvtk7
    const stringValue4 = stringValue({
        "value": input1,
      })

    // @scene-id node-1781855286085-4wwgm
    const sceneSetAttribute5 = sceneSetAttribute({
        "scene": input0,
        "key": textPanel1.output,
        "value": stringValue4.value,
      })

    // @scene-id node-1781855286085-0ogcn
    const sceneSetAttribute6 = sceneSetAttribute({
        "scene": sceneSetAttribute5.scene,
        "key": textPanel2.output,
        "value": textPanel3.output,
      })
    return {
      output0: sceneSetAttribute6.scene,
    }
  },
)

// @scene-id definition:batteries.templates.scene.building-structures.building-structures.nested.1
const buildingStructuresTileAssetName2 = defineGroup(
  {
    id: "scene.template.building-structures.nested.1",
    version: "1.0.0",
    inputs: {
      input0: { type: Scene, runtimeType: "scene", runtimePort: "in_0", access: "item" },
      input1: { type: StringValue, runtimeType: "string", runtimePort: "in_1", access: "tree" },
    },
    outputs: {
      output0: { type: Scene, runtimeType: "scene", runtimePort: "out_0", access: "item" },
    },
  },
  ({ input0, input1 }) => {
    // @scene-id node-1781855286085-voh0m
    const textPanel1 = textPanel({
        "$params": {"text":"asset_name","_nodeWidth":180,"_nodeHeight":67},
      })

    // @scene-id node-1781855286085-88k5y
    const textPanel2 = textPanel({
        "$params": {"text":"asset_type","_nodeWidth":181,"_nodeHeight":60},
      })

    // @scene-id node-1781855286085-tkadm
    const textPanel3 = textPanel({
        "$params": {"text":"tile","_nodeWidth":181,"_nodeHeight":60},
      })

    // @scene-id node-1781855286085-imry8
    const stringValue4 = stringValue({
        "value": input1,
      })

    // @scene-id node-1781855286085-61nji
    const sceneSetAttribute5 = sceneSetAttribute({
        "scene": input0,
        "key": textPanel1.output,
        "value": stringValue4.value,
      })

    // @scene-id node-1781855286085-deyfj
    const sceneSetAttribute6 = sceneSetAttribute({
        "scene": sceneSetAttribute5.scene,
        "key": textPanel2.output,
        "value": textPanel3.output,
      })
    return {
      output0: sceneSetAttribute6.scene,
    }
  },
)

// @scene-id definition:batteries.templates.scene.building-structures.building-structures.nested.2
const buildingStructuresMultiNames = defineGroup(
  {
    id: "scene.template.building-structures.nested.2",
    version: "1.0.0",
    inputs: {
      input0: { type: StringValue, runtimeType: "string", runtimePort: "in_0", access: "tree", hidden: true },
      count: { type: NumberValue, runtimeType: "number", runtimePort: "in_1", access: "tree", labelEn: "Count" },
      input2: { type: NumberValue, runtimeType: "number", runtimePort: "in_2", access: "item", hidden: true },
      prefix: { type: StringValue, runtimeType: "string", runtimePort: "in_3", access: "tree", labelEn: "Prefix" },
    },
    outputs: {
      output0: { type: NumberList, runtimeType: "number", runtimePort: "out_0", access: "list", hidden: true },
      names: { type: StringList, runtimeType: "string", runtimePort: "out_1", access: "list", labelEn: "Names" },
      output2: { type: NumberValue, runtimeType: "number", runtimePort: "out_2", access: "item" },
    },
  },
  ({ input0, count, input2, prefix }) => {
    // @scene-id node-1781855286085-4vjdn
    const numberValue1 = numberValue({})

    // @scene-id node-1781855286085-c9rkq
    const numberValue2 = numberValue({
        "$params": {"value":1},
      })

    // @scene-id node-1781855286085-5o94m
    const typeNumber3 = typeNumber({
        "value": count,
      })

    // @scene-id node-1781855286085-8jscw
    const basicMathOp4 = basicMathOp({
        "$params": {"op":"-"},
        "op": input0,
        "b": numberValue2.value,
        "a": typeNumber3.value,
      })

    // @scene-id node-1781855286085-fa2g1
    const stringValue5 = stringValue({
        "value": prefix,
      })

    // @scene-id node-1781855286085-ohtai
    const rangeList6 = rangeList({
        "step": input2,
        "start": numberValue1.value,
        "end": basicMathOp4.result,
        "prefix": stringValue5.value,
      })
    return {
      output0: rangeList6.list,
      names: rangeList6.stringList,
      output2: rangeList6.count,
    }
  },
)

// @scene-id definition:batteries.templates.scene.building-structures.building-structures
export const buildingStructures = defineGroup(
  {
    id: "scene.template.building-structures",
    version: "1.0.0",
    inputs: {
      scene: { type: Scene, runtimeType: "scene", runtimePort: "in_0", access: "tree", labelEn: "Scene" },
      input1: { type: NumberValue, runtimeType: "number", runtimePort: "in_2", access: "item", hidden: true },
      input2: { type: NumberValue, runtimeType: "number", runtimePort: "in_3", access: "item", hidden: true },
      input3: { type: NumberValue, runtimeType: "number", runtimePort: "in_4", hidden: true },
      input4: { type: NumberValue, runtimeType: "number", runtimePort: "in_5", hidden: true },
      input5: { type: NumberValue, runtimeType: "number", runtimePort: "in_6", hidden: true },
      input6: { type: NumberValue, runtimeType: "number", runtimePort: "in_7", hidden: true },
      input7: { type: BooleanValue, runtimeType: "boolean", runtimePort: "in_1" },
      input8: { type: NumberValue, runtimeType: "number", runtimePort: "in_8", hidden: true },
      input9: { type: NumberValue, runtimeType: "number", runtimePort: "in_9", hidden: true },
      input10: { type: BooleanValue, runtimeType: "boolean", runtimePort: "in_10", hidden: true },
      input11: { type: StringValue, runtimeType: "string", runtimePort: "in_11", access: "item", hidden: true },
      input12: { type: StringValue, runtimeType: "string", runtimePort: "in_12", access: "item", hidden: true },
      input13: { type: StringValue, runtimeType: "string", runtimePort: "in_13", access: "item", hidden: true },
      input14: { type: StringValue, runtimeType: "string", runtimePort: "in_14", access: "item", hidden: true },
      input15: { type: StringValue, runtimeType: "string", runtimePort: "in_15", access: "item", hidden: true },
      input16: { type: StringValue, runtimeType: "string", runtimePort: "in_16", access: "item", hidden: true },
      input17: { type: StringValue, runtimeType: "string", runtimePort: "in_17", access: "item", hidden: true },
      input18: { type: StringValue, runtimeType: "string", runtimePort: "in_18", access: "item", hidden: true },
      input19: { type: StringValue, runtimeType: "string", runtimePort: "in_19", access: "item", hidden: true },
      input20: { type: StringValue, runtimeType: "string", runtimePort: "in_20", access: "item", hidden: true },
      input21: { type: StringValue, runtimeType: "string", runtimePort: "in_21", access: "item", hidden: true },
      input22: { type: StringValue, runtimeType: "string", runtimePort: "in_22", access: "item", hidden: true },
      wallAsset: { type: StringValue, runtimeType: "string", runtimePort: "in_23", access: "tree", hidden: false, labelEn: "WallAsset" },
      seed: { type: NumberValue, runtimeType: "number", runtimePort: "in_24", access: "tree", labelEn: "Seed" },
    },
    outputs: {
      scene: { type: Scene, runtimeType: "scene", runtimePort: "out_0", access: "tree", labelEn: "Scene" },
      rooms: { type: Scene, runtimeType: "scene", runtimePort: "out_1", access: "tree", labelEn: "Rooms" },
      roomsPath: { type: StringValue, runtimeType: "string", runtimePort: "out_2", access: "tree", hidden: false, labelEn: "RoomsPath" },
    },
  },
  ({ scene, input1, input2, input3, input4, input5, input6, input7, input8, input9, input10, input11, input12, input13, input14, input15, input16, input17, input18, input19, input20, input21, input22, wallAsset, seed }) => {
    // @scene-id node-1781855286085-x15r8
    const scenePassthrough1 = scenePassthrough({
        "scene": scene,
      })

    // @scene-id node-1781855286085-w9yjd
    const nodeExplode2 = nodeExplode({
        "scene": scenePassthrough1.scene,
      })

    // @scene-id node-1781855286085-6b089
    const rectangularGrid3 = rectangularGrid({
        "fillValue": input1,
        "width": nodeExplode2.width,
        "height": nodeExplode2.height,
      })

    // @scene-id node-1781855286085-7l72v
    const voxelSlice4 = voxelSlice({
        "z": input2,
        "voxels": nodeExplode2.voxels,
        "grid": rectangularGrid3.grid,
      })

    // @scene-id node-1781855286085-e63kg
    const algRegionOutline5 = algRegionOutline({
        "thickness": input3,
        "region": voxelSlice4.slice,
      })

    // @scene-id node-1781855286085-7yoio
    const algRegionSubtract6 = algRegionSubtract({
        "b": algRegionOutline5.topology,
        "a": voxelSlice4.slice,
      })

    // @scene-id node-1781855286085-k4bk6
    const textPanel7 = textPanel({
        "$params": {"text":"inner_wall","_nodeWidth":172,"_nodeHeight":69},
      })

    // @scene-id node-1781855286085-5dbph
    const textPanel8 = textPanel({
        "$params": {"text":"inner_door","_nodeWidth":172,"_nodeHeight":69},
      })

    // @scene-id node-1781855286085-bud0x
    const textPanel9 = textPanel({
        "$params": {"text":"outer_door","_nodeWidth":172,"_nodeHeight":69},
      })

    // @scene-id node-1781855286085-719jp
    const textPanel10 = textPanel({
        "$params": {"text":"window","_nodeWidth":172,"_nodeHeight":69},
      })

    // @scene-id node-1781855286085-ofq7q
    const textPanel11 = textPanel({
        "$params": {"text":"outer_wall","_nodeWidth":172,"_nodeHeight":69},
      })

    // @scene-id node-1781855286085-h35af
    const textPanel12 = textPanel({
        "$params": {"text":"room_","_nodeWidth":172,"_nodeHeight":69},
      })

    // @scene-id node-1781855286085-e7ht6
    const stringValue13 = stringValue({
        "value": wallAsset,
      })

    // @scene-id node-1781855286085-f5t4r
    const typeNumber14 = typeNumber({
        "value": seed,
      })

    // @scene-id node-1781855286085-ts4is
    const multiSeed15 = multiSeed({
        "shape": voxelSlice4.slice,
        "seed": typeNumber14.value,
      })

    // @scene-id node-1781855286085-cgpix
    const algRegionBsp16 = algRegionBsp({
        "density": input4,
        "region": algRegionSubtract6.region,
        "seed": multiSeed15.seed,
      })

    // @scene-id node-1781855286085-keu2h
    const algPartitionBoundaries17 = algPartitionBoundaries({
        "partition": algRegionBsp16.partition,
      })

    // @scene-id node-1781855286085-cu1qz
    const algPartitionConnect18 = algPartitionConnect({
        "topology": algPartitionBoundaries17.topology,
        "partition": algRegionBsp16.partition,
        "seed": multiSeed15.seed,
      })

    // @scene-id node-1781855286085-f757a
    const algRegionSubtract19 = algRegionSubtract({
        "a": algRegionOutline5.topology,
        "b": algPartitionBoundaries17.topology,
      })

    // @scene-id node-1781855286085-6bnx1
    const algTopologyPickDoors20 = algTopologyPickDoors({
        "count": input5,
        "width": input6,
        "bottomDoor": input7,
        "topology": algRegionSubtract19.region,
        "seed": multiSeed15.seed,
        "region": voxelSlice4.slice,
      })

    // @scene-id node-1781855286085-0y0vd
    const algRegionSubtract21 = algRegionSubtract({
        "a": algRegionSubtract19.region,
        "b": algTopologyPickDoors20.topology,
      })

    // @scene-id node-1781855286085-561gt
    const algTopologyPickWindows22 = algTopologyPickWindows({
        "count": input8,
        "width": input9,
        "random": input10,
        "topology": algRegionSubtract21.region,
        "seed": multiSeed15.seed,
      })

    // @scene-id node-1781855286085-0uq8v
    const algRegionSubtract23 = algRegionSubtract({
        "a": algRegionOutline5.topology,
        "b": algTopologyPickDoors20.topology,
      })

    // @scene-id node-1781855286085-7dmom
    const algRegionSubtract24 = algRegionSubtract({
        "a": algPartitionBoundaries17.topology,
        "b": algRegionOutline5.topology,
      })

    // @scene-id node-1781855286085-84mr5
    const algRegionSubtract25 = algRegionSubtract({
        "a": algRegionSubtract24.region,
        "b": algPartitionConnect18.topology,
      })

    // @scene-id group_1781855286085_j1gtz
    const buildingStructuresMultiNames26 = buildingStructuresMultiNames({
        "prefix": textPanel12.output,
        "count": algRegionBsp16.count,
      })

    // @scene-id node-1781855286085-lvbkz
    const voxelRange27 = voxelRange({
        "voxels": nodeExplode2.voxels,
      })

    // @scene-id node-1781855286085-ukzfd
    const gridSceneNode28 = gridSceneNode({
        "schema": input11,
        "token": input12,
        "grid": algRegionSubtract25.region,
        "zRange": voxelRange27.zRange,
        "name": textPanel7.output,
      })

    // @scene-id group_1781855286085_c345u
    const buildingStructuresTileAssetName29 = buildingStructuresTileAssetName({
        "input0": gridSceneNode28.scene,
        "input1": stringValue13.value,
      })

    // @scene-id node-1781855286085-ah689
    const gridSceneNode30 = gridSceneNode({
        "schema": input13,
        "token": input14,
        "grid": algPartitionConnect18.topology,
        "zRange": voxelRange27.zRange,
        "name": textPanel8.output,
      })

    // @scene-id node-1781855286085-2ic23
    const gridSceneNode31 = gridSceneNode({
        "schema": input15,
        "token": input16,
        "grid": algTopologyPickDoors20.topology,
        "zRange": voxelRange27.zRange,
        "name": textPanel9.output,
      })

    // @scene-id node-1781855286085-p3wlj
    const gridSceneNode32 = gridSceneNode({
        "schema": input17,
        "token": input18,
        "grid": algTopologyPickWindows22.topology,
        "zRange": voxelRange27.zRange,
        "name": textPanel10.output,
      })

    // @scene-id node-1781855286085-wdl06
    const gridSceneNode33 = gridSceneNode({
        "schema": input19,
        "token": input20,
        "grid": algRegionSubtract23.region,
        "zRange": voxelRange27.zRange,
        "name": textPanel11.output,
      })

    // @scene-id group_1781855286085_tl3re
    const buildingStructuresTileAssetName234 = buildingStructuresTileAssetName2({
        "input0": gridSceneNode33.scene,
        "input1": stringValue13.value,
      })

    // @scene-id node-1781855286085-e66ys
    const mergePoints35 = mergePoints({
        "$params": {"inferredAccess":"item","inferredType":"scene","portCount":6},
        "item_1": gridSceneNode30.scene,
        "item_2": gridSceneNode31.scene,
        "item_3": gridSceneNode32.scene,
        "item_0": buildingStructuresTileAssetName29.output0,
        "item_4": buildingStructuresTileAssetName234.output0,
      })

    // @scene-id node-1781855286085-aek5h
    const addSceneChildren36 = addSceneChildren({
        "nodes": mergePoints35.tree,
        "scene": scenePassthrough1.scene,
      })

    // @scene-id node-bs-room-zminus1-const
    const numberValue37 = numberValue({
        "$params": {"value":1,"min":0,"max":10,"precision":0},
      })

    // @scene-id node-bs-room-zmin-idx
    const numberValue38 = numberValue({
        "$params": {"value":0,"min":0,"max":10,"precision":0},
      })

    // @scene-id node-bs-room-zmin-get
    const listGetSingle39 = listGetSingle({
        "list": voxelRange27.zRange,
        "index": numberValue38.value,
      })

    // @scene-id node-bs-room-zfloor-math
    const basicMathOp40 = basicMathOp({
        "$params": {"op":"-"},
        "a": listGetSingle39.item,
        "b": numberValue37.value,
      })

    // @scene-id node-bs-room-zfloor-range
    const rangeList41 = rangeList({
        "start": basicMathOp40.result,
        "end": basicMathOp40.result,
      })

    // @scene-id node-1781855286085-y5f2n
    const gridSceneNode42 = gridSceneNode({
        "schema": input21,
        "token": input22,
        "grid": algRegionBsp16.partition,
        "name": buildingStructuresMultiNames26.names,
        "zRange": rangeList41.list,
      })

    // @scene-id node-1781855286085-svqce
    const addSceneChildren43 = addSceneChildren({
        "scene": addSceneChildren36.scene,
        "nodes": gridSceneNode42.scene,
      })

    // @scene-id node-1781855286085-fttlt
    const sceneMergeSubtrees44 = sceneMergeSubtrees({
        "scenes": addSceneChildren43.scene,
      })

    // @scene-id node-1781855286085-et0f6
    const sceneFocusPath45 = sceneFocusPath({
        "path": addSceneChildren43.childPaths,
        "scene": sceneMergeSubtrees44.scene,
      })

    // @scene-id node-1781855286085-06aqe
    const scenePassthrough46 = scenePassthrough({
        "scene": sceneMergeSubtrees44.scene,
      })

    // @scene-id node-1781855286085-vmw83
    const scenePassthrough47 = scenePassthrough({
        "scene": sceneFocusPath45.scene,
      })

    // @scene-id node-1781855286085-66bis
    const stringValue48 = stringValue({
        "value": addSceneChildren43.childPaths,
      })
    return {
      scene: scenePassthrough46.scene,
      rooms: scenePassthrough47.scene,
      roomsPath: stringValue48.value,
    }
  },
)
