// Generated by scripts/generate-native-group-definitions.mts.
// JSON parity oracle only: batteries/templates/structures/districts/EdgeTreeClusters/EdgeTreeClusters.json
// @scene-id definition:batteries.templates.structures.districts.edge-tree-clusters.edge-tree-clusters.nested.0
const edgeTreeClustersTileAssetName = defineGroup(
  {
    id: "scene.template.edge-tree-clusters.nested.0",
    version: "1.0.0",
    inputs: {
      input0: { type: Scene, runtimeType: "scene", runtimePort: "in_0", access: "item" },
      input1: { type: StringValue, runtimeType: "string", runtimePort: "in_1", access: "tree" },
    },
    outputs: {
      output0: { type: Scene, runtimeType: "scene", runtimePort: "out_0", access: "item" },
    },
  },
  ({ input0, input1 }) => {
    // @scene-id egtz_tp_name
    const textPanel1 = textPanel({
        "$params": {"text":"asset_name","_nodeWidth":180,"_nodeHeight":67},
      })

    // @scene-id egtz_tp_type
    const textPanel2 = textPanel({
        "$params": {"text":"asset_type","_nodeWidth":181,"_nodeHeight":60},
      })

    // @scene-id egtz_tp_tile
    const textPanel3 = textPanel({
        "$params": {"text":"tile","_nodeWidth":181,"_nodeHeight":60},
      })

    // @scene-id egtz_str
    const stringValue4 = stringValue({
        "value": input1,
      })

    // @scene-id egtz_set1
    const sceneSetAttribute5 = sceneSetAttribute({
        "scene": input0,
        "key": textPanel1.output,
        "value": stringValue4.value,
      })

    // @scene-id egtz_set2
    const sceneSetAttribute6 = sceneSetAttribute({
        "scene": sceneSetAttribute5.scene,
        "key": textPanel2.output,
        "value": textPanel3.output,
      })
    return {
      output0: sceneSetAttribute6.scene,
    }
  },
)

// @scene-id definition:batteries.templates.structures.districts.edge-tree-clusters.edge-tree-clusters
export const edgeTreeClusters = defineGroup(
  {
    id: "scene.template.edge-tree-clusters",
    version: "1.0.0",
    inputs: {
      input0: { type: Scene, runtimeType: "scene", runtimePort: "in_0", access: "tree" },
      districtAsset: { type: StringValue, runtimeType: "string", runtimePort: "in_1", access: "tree", labelEn: "DistrictAsset" },
      seed: { type: NumberValue, runtimeType: "number", runtimePort: "in_2", access: "item", labelEn: "Seed" },
      count: { type: NumberValue, runtimeType: "number", runtimePort: "in_3", access: "item", labelEn: "Count" },
      clusterSize: { type: NumberValue, runtimeType: "number", runtimePort: "in_4", access: "item", labelEn: "ClusterSize" },
      irregularity: { type: NumberValue, runtimeType: "number", runtimePort: "in_5", access: "item", labelEn: "Irregularity" },
      input6: { type: NumberValue, runtimeType: "number", runtimePort: "in_6", access: "item", hidden: true },
      input7: { type: NumberValue, runtimeType: "number", runtimePort: "in_7", access: "item", hidden: true },
      input8: { type: NumberValue, runtimeType: "number", runtimePort: "in_8", access: "item", hidden: true },
      input9: { type: NumberValue, runtimeType: "number", runtimePort: "in_9", access: "item", hidden: true },
      input10: { type: NumberValue, runtimeType: "number", runtimePort: "in_10", access: "item", hidden: true },
      input11: { type: StringValue, runtimeType: "string", runtimePort: "in_11", access: "item", hidden: true },
      input12: { type: StringValue, runtimeType: "string", runtimePort: "in_12", access: "item", hidden: true },
      input13: { type: NumberList, runtimeType: "number", runtimePort: "in_13", access: "list", hidden: true },
    },
    outputs: {
      scene: { type: Scene, runtimeType: "scene", runtimePort: "out_0", access: "tree", order: 0, labelEn: "Scene" },
      rest: { type: Scene, runtimeType: "scene", runtimePort: "out_1", access: "tree", order: 1, labelEn: "Rest" },
      clusters: { type: Scene, runtimeType: "scene", runtimePort: "out_2", access: "tree", order: 2, labelEn: "Clusters" },
      clustersPath: { type: StringValue, runtimeType: "string", runtimePort: "out_3", access: "tree", order: 3, labelEn: "ClustersPath" },
      restPath: { type: StringValue, runtimeType: "string", runtimePort: "out_4", access: "tree", order: 4, labelEn: "RestPath" },
    },
  },
  ({ input0, districtAsset, seed, count, clusterSize, irregularity, input6, input7, input8, input9, input10, input11, input12, input13 }) => {
    // @scene-id eg_in
    const scenePassthrough1 = scenePassthrough({
        "scene": input0,
      })

    // @scene-id eg_explode
    const nodeExplode2 = nodeExplode({
        "scene": scenePassthrough1.scene,
      })

    // @scene-id eg_rgrid
    const rectangularGrid3 = rectangularGrid({
        "fillValue": input9,
        "width": nodeExplode2.width,
        "height": nodeExplode2.height,
      })

    // @scene-id eg_slice
    const voxelSlice4 = voxelSlice({
        "z": input10,
        "voxels": nodeExplode2.voxels,
        "grid": rectangularGrid3.grid,
      })

    // @scene-id eg_clusters
    const edgeGreenCluster5 = edgeGreenCluster({
        "$params": {"count":17,"clusterSize":267},
        "seed": seed,
        "count": count,
        "clusterSize": clusterSize,
        "irregularity": irregularity,
        "sizeVariance": input6,
        "targetValue": input7,
        "outputValue": input8,
        "inputGrid": voxelSlice4.slice,
      })

    // @scene-id eg_name
    const stringValue6 = stringValue({
        "value": districtAsset,
      })

    // @scene-id eg_g2n
    const gridSceneNode7 = gridSceneNode({
        "schema": input11,
        "token": input12,
        "zRange": input13,
        "grid": edgeGreenCluster5.outputGrid,
        "name": stringValue6.value,
      })

    // @scene-id eg_tile
    const edgeTreeClustersTileAssetName8 = edgeTreeClustersTileAssetName({
        "input0": gridSceneNode7.scene,
        "input1": stringValue6.value,
      })

    // @scene-id eg_add
    const addSceneChildren9 = addSceneChildren({
        "nodes": edgeTreeClustersTileAssetName8.output0,
        "scene": scenePassthrough1.scene,
      })

    // @scene-id eg_subtract
    const algRegionSubtract10 = algRegionSubtract({
        "a": voxelSlice4.slice,
        "b": edgeGreenCluster5.outputGrid,
      })

    // @scene-id eg_rname
    const textPanel11 = textPanel({
        "$params": {"text":"rest","_nodeWidth":172,"_nodeHeight":69},
      })

    // @scene-id eg_g2n_rest
    const gridSceneNode12 = gridSceneNode({
        "grid": algRegionSubtract10.region,
        "name": textPanel11.output,
      })

    // @scene-id eg_add_rest
    const addSceneChildren13 = addSceneChildren({
        "scene": addSceneChildren9.scene,
        "nodes": gridSceneNode12.scene,
      })

    // @scene-id eg_merge
    const sceneMergeSubtrees14 = sceneMergeSubtrees({
        "scenes": addSceneChildren13.scene,
      })

    // @scene-id eg_focus
    const sceneFocusPath15 = sceneFocusPath({
        "scene": sceneMergeSubtrees14.scene,
        "path": addSceneChildren9.childPaths,
      })

    // @scene-id eg_focus_rest
    const sceneFocusPath16 = sceneFocusPath({
        "scene": sceneMergeSubtrees14.scene,
        "path": addSceneChildren13.childPaths,
      })

    // @scene-id eg_out_main
    const scenePassthrough17 = scenePassthrough({
        "scene": sceneMergeSubtrees14.scene,
      })

    // @scene-id eg_out_clusters
    const scenePassthrough18 = scenePassthrough({
        "scene": sceneFocusPath15.scene,
      })

    // @scene-id eg_out_rest
    const scenePassthrough19 = scenePassthrough({
        "scene": sceneFocusPath16.scene,
      })

    // @scene-id eg_path
    const stringValue20 = stringValue({
        "value": addSceneChildren9.childPaths,
      })

    // @scene-id eg_rpath
    const stringValue21 = stringValue({
        "value": addSceneChildren13.childPaths,
      })
    return {
      scene: scenePassthrough17.scene,
      rest: scenePassthrough19.scene,
      clusters: scenePassthrough18.scene,
      clustersPath: stringValue20.value,
      restPath: stringValue21.value,
    }
  },
)
