// Generated by scripts/generate-native-group-definitions.mts.
// JSON parity oracle only: batteries/templates/structures/decorations/PoiScatter/PoiScatter.json
// @scene-id definition:batteries.templates.structures.decorations.poi-scatter.poi-scatter.nested.0
const poiScatterTemplateObjectAssetName = defineGroup(
  {
    id: "scene.template.poi-scatter.nested.0",
    version: "1.0.0",
    inputs: {
      input0: { type: Scene, runtimeType: "scene", runtimePort: "in_0", access: "item" },
      input1: { type: StringValue, runtimeType: "string", runtimePort: "in_1", access: "tree" },
    },
    outputs: {
      output0: { type: Scene, runtimeType: "scene", runtimePort: "out_0", access: "item" },
    },
  },
  ({ input0, input1 }) => {
    // @scene-id ps-an-name
    const textPanel1 = textPanel({
        "$params": {"text":"asset_name"},
      })

    // @scene-id ps-an-type
    const textPanel2 = textPanel({
        "$params": {"text":"asset_type"},
      })

    // @scene-id ps-an-obj
    const textPanel3 = textPanel({
        "$params": {"text":"object"},
      })

    // @scene-id ps-an-str
    const stringValue4 = stringValue({
        "value": input1,
      })

    // @scene-id ps-an-set1
    const sceneSetAttribute5 = sceneSetAttribute({
        "scene": input0,
        "key": textPanel1.output,
        "value": stringValue4.value,
      })

    // @scene-id ps-an-set2
    const sceneSetAttribute6 = sceneSetAttribute({
        "scene": sceneSetAttribute5.scene,
        "key": textPanel2.output,
        "value": textPanel3.output,
      })
    return {
      output0: sceneSetAttribute6.scene,
    }
  },
)

// @scene-id definition:batteries.templates.structures.decorations.poi-scatter.poi-scatter
export const poiScatterTemplate = defineGroup(
  {
    id: "scene.template.poi-scatter",
    version: "1.0.0",
    inputs: {
      scene: { type: Scene, runtimeType: "scene", runtimePort: "in_0", access: "tree", order: 0, labelEn: "Scene" },
      assetName: { type: StringValue, runtimeType: "string", runtimePort: "in_1", access: "tree", order: 1, labelEn: "AssetName" },
      poiRules: { type: Any, runtimeType: "array", runtimePort: "in_2", order: 2, labelEn: "PoiRules" },
      seed: { type: NumberValue, runtimeType: "number", runtimePort: "in_3", access: "item", order: 3, labelEn: "Seed" },
    },
    outputs: {
      scene: { type: Scene, runtimeType: "scene", runtimePort: "out_0", access: "item", order: 0, labelEn: "Scene" },
      poi: { type: Scene, runtimeType: "scene", runtimePort: "out_1", access: "item", order: 1, labelEn: "Poi" },
      rest: { type: Scene, runtimeType: "scene", runtimePort: "out_2", access: "item", order: 2, labelEn: "Rest" },
      poiPath: { type: StringValue, runtimeType: "string", runtimePort: "out_3", access: "tree", order: 3, labelEn: "PoiPath" },
      restPath: { type: StringValue, runtimeType: "string", runtimePort: "out_4", access: "tree", order: 4, labelEn: "RestPath" },
    },
  },
  ({ scene, assetName, poiRules, seed }) => {
    // @scene-id ps-pt
    const scenePassthrough1 = scenePassthrough({
        "scene": scene,
      })

    // @scene-id ps-ex
    const nodeExplode2 = nodeExplode({
        "scene": scenePassthrough1.scene,
      })

    // @scene-id ps-rg
    const rectangularGrid3 = rectangularGrid({
        "width": nodeExplode2.width,
        "height": nodeExplode2.height,
      })

    // @scene-id ps-vs
    const voxelSlice4 = voxelSlice({
        "voxels": nodeExplode2.voxels,
        "grid": rectangularGrid3.grid,
      })

    // @scene-id ps-bat
    const poiScatter5 = poiScatter({
        "poiRules": poiRules,
        "seed": seed,
        "inputGrid": voxelSlice4.slice,
      })

    // @scene-id ps-txd
    const textPanel6 = textPanel({
        "$params": {"text":"poi"},
      })

    // @scene-id ps-g2d
    const gridSceneNode7 = gridSceneNode({
        "grid": poiScatter5.outputGrid,
        "name": textPanel6.output,
      })

    // @scene-id group_ps_objasset
    const poiScatterTemplateObjectAssetName8 = poiScatterTemplateObjectAssetName({
        "input1": assetName,
        "input0": gridSceneNode7.scene,
      })

    // @scene-id ps-ac1
    const addSceneChildren9 = addSceneChildren({
        "nodes": poiScatterTemplateObjectAssetName8.output0,
        "scene": scenePassthrough1.scene,
      })

    // @scene-id ps-sub
    const algRegionSubtract10 = algRegionSubtract({
        "a": voxelSlice4.slice,
        "b": poiScatter5.outputGrid,
      })

    // @scene-id ps-txr
    const textPanel11 = textPanel({
        "$params": {"text":"rest"},
      })

    // @scene-id ps-g2r
    const gridSceneNode12 = gridSceneNode({
        "grid": algRegionSubtract10.region,
        "name": textPanel11.output,
      })

    // @scene-id ps-ac2
    const addSceneChildren13 = addSceneChildren({
        "nodes": gridSceneNode12.scene,
        "scene": addSceneChildren9.scene,
      })

    // @scene-id ps-fpd
    const sceneFocusPath14 = sceneFocusPath({
        "scene": addSceneChildren13.scene,
        "path": addSceneChildren9.childPaths,
      })

    // @scene-id ps-fpr
    const sceneFocusPath15 = sceneFocusPath({
        "scene": addSceneChildren13.scene,
        "path": addSceneChildren13.childPaths,
      })

    // @scene-id ps-tsd
    const stringValue16 = stringValue({
        "value": addSceneChildren9.childPaths,
      })

    // @scene-id ps-tsr
    const stringValue17 = stringValue({
        "value": addSceneChildren13.childPaths,
      })
    return {
      scene: addSceneChildren13.scene,
      poi: sceneFocusPath14.scene,
      rest: sceneFocusPath15.scene,
      poiPath: stringValue16.value,
      restPath: stringValue17.value,
    }
  },
)
