// Generated by scripts/generate-native-group-definitions.mts.
// JSON parity oracle only: batteries/templates/structures/water/RandomLakeRegions/RandomLakeRegions.json
// @scene-id definition:batteries.templates.structures.water.random-lake-regions.random-lake-regions.nested.0
const randomLakeRegionsMultiNames = defineGroup(
  {
    id: "scene.template.random-lake-regions.nested.0",
    version: "1.0.0",
    inputs: {
      input0: { type: StringValue, runtimeType: "string", runtimePort: "in_0", access: "tree", hidden: true },
      count: { type: NumberValue, runtimeType: "number", runtimePort: "in_1", access: "tree", labelEn: "Count" },
      input2: { type: NumberValue, runtimeType: "number", runtimePort: "in_2", access: "item", hidden: true },
      prefix: { type: StringValue, runtimeType: "string", runtimePort: "in_3", access: "tree", labelEn: "Prefix" },
    },
    outputs: {
      output0: { type: NumberList, runtimeType: "number", runtimePort: "out_0", access: "list", hidden: true },
      names: { type: StringList, runtimeType: "string", runtimePort: "out_1", access: "list", labelEn: "Names" },
      output2: { type: NumberValue, runtimeType: "number", runtimePort: "out_2", access: "item" },
    },
  },
  ({ input0, count, input2, prefix }) => {
    // @scene-id node-1781196357312-kpdc6
    const numberValue1 = numberValue({})

    // @scene-id node-1781196357313-zx4q3
    const numberValue2 = numberValue({
        "$params": {"value":1},
      })

    // @scene-id node-1781196357313-ytu1s
    const typeNumber3 = typeNumber({
        "value": count,
      })

    // @scene-id node-1781196357313-uv479
    const basicMathOp4 = basicMathOp({
        "$params": {"op":"-"},
        "op": input0,
        "b": numberValue2.value,
        "a": typeNumber3.value,
      })

    // @scene-id node-1781196357313-p3rbt
    const stringValue5 = stringValue({
        "value": prefix,
      })

    // @scene-id node-1781196357313-c34js
    const rangeList6 = rangeList({
        "step": input2,
        "start": numberValue1.value,
        "end": basicMathOp4.result,
        "prefix": stringValue5.value,
      })
    return {
      output0: rangeList6.list,
      names: rangeList6.stringList,
      output2: rangeList6.count,
    }
  },
)

// @scene-id definition:batteries.templates.structures.water.random-lake-regions.random-lake-regions.nested.1
const randomLakeRegionsTileAssetName = defineGroup(
  {
    id: "scene.template.random-lake-regions.nested.1",
    version: "1.0.0",
    inputs: {
      input0: { type: Scene, runtimeType: "scene", runtimePort: "in_0", access: "item" },
      input1: { type: StringValue, runtimeType: "string", runtimePort: "in_1", access: "tree" },
    },
    outputs: {
      output0: { type: Scene, runtimeType: "scene", runtimePort: "out_0", access: "item" },
    },
  },
  ({ input0, input1 }) => {
    // @scene-id node-1781196424173-48nka
    const textPanel1 = textPanel({
        "$params": {"text":"asset_name","_nodeWidth":180,"_nodeHeight":67},
      })

    // @scene-id node-1781196424173-s5urz
    const textPanel2 = textPanel({
        "$params": {"text":"asset_type","_nodeWidth":181,"_nodeHeight":60},
      })

    // @scene-id node-1781196424173-v6d58
    const textPanel3 = textPanel({
        "$params": {"text":"tile","_nodeWidth":181,"_nodeHeight":60},
      })

    // @scene-id node-1781196424173-zxpwk
    const stringValue4 = stringValue({
        "value": input1,
      })

    // @scene-id node-1781196424173-a61li
    const sceneSetAttribute5 = sceneSetAttribute({
        "scene": input0,
        "key": textPanel1.output,
        "value": stringValue4.value,
      })

    // @scene-id node-1781196424173-qh0dn
    const sceneSetAttribute6 = sceneSetAttribute({
        "scene": sceneSetAttribute5.scene,
        "key": textPanel2.output,
        "value": textPanel3.output,
      })
    return {
      output0: sceneSetAttribute6.scene,
    }
  },
)

// @scene-id definition:batteries.templates.structures.water.random-lake-regions.random-lake-regions
export const randomLakeRegions = defineGroup(
  {
    id: "scene.template.random-lake-regions",
    version: "1.0.0",
    inputs: {
      input0: { type: Scene, runtimeType: "scene", runtimePort: "in_0", access: "tree" },
      input1: { type: NumberValue, runtimeType: "number", runtimePort: "in_4", access: "item", hidden: true },
      input2: { type: NumberValue, runtimeType: "number", runtimePort: "in_5", access: "item", hidden: true },
      input3: { type: StringValue, runtimeType: "string", runtimePort: "in_6", hidden: true },
      input4: { type: StringValue, runtimeType: "string", runtimePort: "in_7", hidden: true },
      input5: { type: NumberValue, runtimeType: "number", runtimePort: "in_8", hidden: true },
      expectedLakes: { type: NumberValue, runtimeType: "number", runtimePort: "in_1", labelEn: "ExpectedLakes" },
      lakeSize: { type: NumberValue, runtimeType: "number", runtimePort: "in_18", access: "item", labelEn: "LakeSize" },
      input8: { type: NumberValue, runtimeType: "number", runtimePort: "in_9", hidden: true },
      input9: { type: NumberValue, runtimeType: "number", runtimePort: "in_10", hidden: true },
      input10: { type: NumberValue, runtimeType: "number", runtimePort: "in_11", hidden: true },
      input11: { type: StringValue, runtimeType: "string", runtimePort: "in_12", access: "item", hidden: true },
      input12: { type: StringValue, runtimeType: "string", runtimePort: "in_13", access: "item", hidden: true },
      input13: { type: NumberList, runtimeType: "number", runtimePort: "in_14", access: "list", hidden: true },
      lakeAsset: { type: StringValue, runtimeType: "string", runtimePort: "in_2", access: "tree", labelEn: "LakeAsset" },
      input15: { type: StringValue, runtimeType: "string", runtimePort: "in_15", access: "item", hidden: true },
      input16: { type: StringValue, runtimeType: "string", runtimePort: "in_16", access: "item", hidden: true },
      input17: { type: NumberList, runtimeType: "number", runtimePort: "in_17", access: "list", hidden: true },
      seed: { type: NumberValue, runtimeType: "number", runtimePort: "in_3", access: "tree", labelEn: "Seed" },
    },
    outputs: {
      scene: { type: Scene, runtimeType: "scene", runtimePort: "out_0", access: "tree", order: 0, labelEn: "Scene" },
      lake: { type: Scene, runtimeType: "scene", runtimePort: "out_2", access: "tree", order: 1, labelEn: "Lake" },
      rest: { type: Scene, runtimeType: "scene", runtimePort: "out_1", access: "tree", order: 3, labelEn: "Rest" },
      lakePath: { type: StringValue, runtimeType: "string", runtimePort: "out_3", access: "tree", order: 2, labelEn: "LakePath" },
      restPath: { type: StringValue, runtimeType: "string", runtimePort: "out_4", access: "tree", order: 4, labelEn: "RestPath" },
    },
  },
  ({ input0, input1, input2, input3, input4, input5, expectedLakes, lakeSize, input8, input9, input10, input11, input12, input13, lakeAsset, input15, input16, input17, seed }) => {
    // @scene-id node-1781195086749-tmrnd
    const scenePassthrough1 = scenePassthrough({
        "scene": input0,
      })

    // @scene-id node-1781195086751-18hzj
    const nodeExplode2 = nodeExplode({
        "scene": scenePassthrough1.scene,
      })

    // @scene-id node-1781195086752-rl289
    const rectangularGrid3 = rectangularGrid({
        "fillValue": input1,
        "width": nodeExplode2.width,
        "height": nodeExplode2.height,
      })

    // @scene-id node-1781195086753-lprq9
    const voxelSlice4 = voxelSlice({
        "z": input2,
        "voxels": nodeExplode2.voxels,
        "grid": rectangularGrid3.grid,
      })

    // @scene-id node-1781196357316-pwne4
    const textPanel5 = textPanel({
        "$params": {"text":"lake_","_nodeWidth":172,"_nodeHeight":69},
      })

    // @scene-id node-1781196534058-ork8p
    const textPanel6 = textPanel({
        "$params": {"text":"rest","_nodeWidth":172,"_nodeHeight":69},
      })

    // @scene-id node-1781197086189-poa0d
    const numberValue7 = numberValue({
        "$params": {"value":3},
      })

    // @scene-id node-1781238323504
    const multiSeed8 = multiSeed({
        "seed": seed,
        "shape": voxelSlice4.slice,
      })

    // @scene-id node-1781196067660
    const algPointsScatter9 = algPointsScatter({
        "mode": input3,
        "countMode": input4,
        "density": input5,
        "count": expectedLakes,
        "targetValue": input8,
        "region": voxelSlice4.slice,
        "minSpacing": numberValue7.value,
        "seed": multiSeed8.seed,
      })

    // @scene-id node-1781196193164
    const algRegionFloodGrow10 = algRegionFloodGrow({
        "$params": {"size":50},
        "size": lakeSize,
        "sizeVariance": input9,
        "spacingDilate": input10,
        "points": algPointsScatter9.points,
        "region": voxelSlice4.slice,
        "seed": multiSeed8.seed,
      })

    // @scene-id group_1781196357312_1adif
    const randomLakeRegionsMultiNames11 = randomLakeRegionsMultiNames({
        "prefix": textPanel5.output,
        "count": algRegionFloodGrow10.count,
      })

    // @scene-id node-1781196357317-p09mn
    const gridSceneNode12 = gridSceneNode({
        "schema": input11,
        "token": input12,
        "zRange": input13,
        "name": randomLakeRegionsMultiNames11.names,
        "grid": algRegionFloodGrow10.partition,
      })

    // @scene-id group_1781196424173_7w8rd
    const randomLakeRegionsTileAssetName13 = randomLakeRegionsTileAssetName({
        "input1": lakeAsset,
        "input0": gridSceneNode12.scene,
      })

    // @scene-id node-1781196524935-1n9ci
    const addSceneChildren14 = addSceneChildren({
        "nodes": randomLakeRegionsTileAssetName13.output0,
        "scene": scenePassthrough1.scene,
      })

    // @scene-id node-1781196557844
    const algRegionUnionAll15 = algRegionUnionAll({
        "regions": algRegionFloodGrow10.partition,
      })

    // @scene-id node-1781196534055-ydsjh
    const algRegionSubtract16 = algRegionSubtract({
        "a": voxelSlice4.slice,
        "b": algRegionUnionAll15.region,
      })

    // @scene-id node-1781196534057-5e8c1
    const gridSceneNode17 = gridSceneNode({
        "schema": input15,
        "token": input16,
        "zRange": input17,
        "name": textPanel6.output,
        "grid": algRegionSubtract16.region,
      })

    // @scene-id node-1781196524938-x6l38
    const addSceneChildren18 = addSceneChildren({
        "scene": addSceneChildren14.scene,
        "nodes": gridSceneNode17.scene,
      })

    // @scene-id node-1781196524936-fwqpu
    const sceneMergeSubtrees19 = sceneMergeSubtrees({
        "scenes": addSceneChildren18.scene,
      })

    // @scene-id node-1781196524937-pz7vk
    const sceneFocusPath20 = sceneFocusPath({
        "path": addSceneChildren14.childPaths,
        "scene": sceneMergeSubtrees19.scene,
      })

    // @scene-id node-1781196524938-1gejd
    const scenePassthrough21 = scenePassthrough({
        "scene": sceneMergeSubtrees19.scene,
      })

    // @scene-id node-1781196524939-ha9qx
    const sceneFocusPath22 = sceneFocusPath({
        "path": addSceneChildren18.childPaths,
        "scene": sceneMergeSubtrees19.scene,
      })

    // @scene-id node-1781196524940-5z8b3
    const scenePassthrough23 = scenePassthrough({
        "scene": sceneFocusPath20.scene,
      })

    // @scene-id node-1781196524940-y8gid
    const scenePassthrough24 = scenePassthrough({
        "scene": sceneFocusPath22.scene,
      })

    // @scene-id node-1781238278026
    const stringValue25 = stringValue({
        "value": addSceneChildren14.childPaths,
      })

    // @scene-id node-1781238286100-4naph
    const stringValue26 = stringValue({
        "value": addSceneChildren18.childPaths,
      })
    return {
      scene: scenePassthrough21.scene,
      lake: scenePassthrough23.scene,
      rest: scenePassthrough24.scene,
      lakePath: stringValue25.value,
      restPath: stringValue26.value,
    }
  },
)
