// Generated by scripts/generate-native-group-definitions.mts.
// JSON parity oracle only: batteries/templates/scene/DistanceZones/DistanceZones.json
// @scene-id definition:batteries.templates.scene.distance-zones.distance-zones.nested.0
const distanceZonesNearAssetName = defineGroup(
  {
    id: "scene.template.distance-zones.nested.0",
    version: "1.0.0",
    inputs: {
      input0: { type: Scene, runtimeType: "scene", runtimePort: "in_0", access: "item" },
      input1: { type: StringValue, runtimeType: "string", runtimePort: "in_1", access: "tree" },
    },
    outputs: {
      output0: { type: Scene, runtimeType: "scene", runtimePort: "out_0", access: "item" },
    },
  },
  ({ input0, input1 }) => {
    // @scene-id node-dz-tanear-name
    const textPanel1 = textPanel({
        "$params": {"text":"asset_name","_nodeWidth":180,"_nodeHeight":67},
      })

    // @scene-id node-dz-tanear-type
    const textPanel2 = textPanel({
        "$params": {"text":"asset_type","_nodeWidth":181,"_nodeHeight":60},
      })

    // @scene-id node-dz-tanear-tile
    const textPanel3 = textPanel({
        "$params": {"text":"tile","_nodeWidth":181,"_nodeHeight":60},
      })

    // @scene-id node-dz-tanear-str
    const stringValue4 = stringValue({
        "value": input1,
      })

    // @scene-id node-dz-tanear-set1
    const sceneSetAttribute5 = sceneSetAttribute({
        "scene": input0,
        "key": textPanel1.output,
        "value": stringValue4.value,
      })

    // @scene-id node-dz-tanear-set2
    const sceneSetAttribute6 = sceneSetAttribute({
        "scene": sceneSetAttribute5.scene,
        "key": textPanel2.output,
        "value": textPanel3.output,
      })
    return {
      output0: sceneSetAttribute6.scene,
    }
  },
)

// @scene-id definition:batteries.templates.scene.distance-zones.distance-zones.nested.1
const distanceZonesFarAssetName = defineGroup(
  {
    id: "scene.template.distance-zones.nested.1",
    version: "1.0.0",
    inputs: {
      input0: { type: Scene, runtimeType: "scene", runtimePort: "in_0", access: "item" },
      input1: { type: StringValue, runtimeType: "string", runtimePort: "in_1", access: "tree" },
    },
    outputs: {
      output0: { type: Scene, runtimeType: "scene", runtimePort: "out_0", access: "item" },
    },
  },
  ({ input0, input1 }) => {
    // @scene-id node-dz-tafar-name
    const textPanel1 = textPanel({
        "$params": {"text":"asset_name","_nodeWidth":180,"_nodeHeight":67},
      })

    // @scene-id node-dz-tafar-type
    const textPanel2 = textPanel({
        "$params": {"text":"asset_type","_nodeWidth":181,"_nodeHeight":60},
      })

    // @scene-id node-dz-tafar-tile
    const textPanel3 = textPanel({
        "$params": {"text":"tile","_nodeWidth":181,"_nodeHeight":60},
      })

    // @scene-id node-dz-tafar-str
    const stringValue4 = stringValue({
        "value": input1,
      })

    // @scene-id node-dz-tafar-set1
    const sceneSetAttribute5 = sceneSetAttribute({
        "scene": input0,
        "key": textPanel1.output,
        "value": stringValue4.value,
      })

    // @scene-id node-dz-tafar-set2
    const sceneSetAttribute6 = sceneSetAttribute({
        "scene": sceneSetAttribute5.scene,
        "key": textPanel2.output,
        "value": textPanel3.output,
      })
    return {
      output0: sceneSetAttribute6.scene,
    }
  },
)

// @scene-id definition:batteries.templates.scene.distance-zones.distance-zones
export const distanceZones = defineGroup(
  {
    id: "scene.template.distance-zones",
    version: "1.0.0",
    inputs: {
      scene: { type: Scene, runtimeType: "scene", runtimePort: "in_0", access: "tree", order: 0, labelEn: "Scene" },
      threshold: { type: NumberValue, runtimeType: "number", runtimePort: "in_1", access: "item", order: 1, labelEn: "Threshold" },
      includeOuterBoundary: { type: BooleanValue, runtimeType: "bool", runtimePort: "in_2", access: "item", order: 2, labelEn: "IncludeOuterBoundary" },
      nearName: { type: StringValue, runtimeType: "string", runtimePort: "in_3", access: "item", order: 3, labelEn: "NearName" },
      nearAsset: { type: StringValue, runtimeType: "string", runtimePort: "in_4", access: "tree", order: 4, labelEn: "NearAsset" },
      farName: { type: StringValue, runtimeType: "string", runtimePort: "in_5", access: "item", order: 5, labelEn: "FarName" },
      farAsset: { type: StringValue, runtimeType: "string", runtimePort: "in_6", access: "tree", order: 6, labelEn: "FarAsset" },
      input7: { type: NumberValue, runtimeType: "number", runtimePort: "in_7", access: "item", hidden: true, order: 7 },
      input8: { type: BooleanValue, runtimeType: "bool", runtimePort: "in_8", access: "item", hidden: true, order: 8 },
      input9: { type: NumberValue, runtimeType: "number", runtimePort: "in_9", access: "item", hidden: true, order: 9 },
      input10: { type: NumberValue, runtimeType: "number", runtimePort: "in_10", access: "item", hidden: true, order: 10 },
      input11: { type: StringValue, runtimeType: "string", runtimePort: "in_11", access: "item", hidden: true, order: 11 },
      input12: { type: StringValue, runtimeType: "string", runtimePort: "in_12", access: "item", hidden: true, order: 12 },
      input13: { type: NumberList, runtimeType: "number", runtimePort: "in_13", access: "list", hidden: true, order: 13 },
      input14: { type: NumberList, runtimeType: "number", runtimePort: "in_14", access: "list", hidden: true, order: 14 },
    },
    outputs: {
      scene: { type: Scene, runtimeType: "scene", runtimePort: "out_0", access: "tree", order: 0, labelEn: "Scene" },
      near: { type: Scene, runtimeType: "scene", runtimePort: "out_1", access: "tree", order: 1, labelEn: "Near" },
      far: { type: Scene, runtimeType: "scene", runtimePort: "out_2", access: "tree", order: 2, labelEn: "Far" },
      nearPath: { type: StringValue, runtimeType: "string", runtimePort: "out_3", access: "tree", order: 3, labelEn: "NearPath" },
      farPath: { type: StringValue, runtimeType: "string", runtimePort: "out_4", access: "tree", order: 4, labelEn: "FarPath" },
    },
  },
  ({ scene, threshold, includeOuterBoundary, nearName, nearAsset, farName, farAsset, input7, input8, input9, input10, input11, input12, input13, input14 }) => {
    // @scene-id node-dz-pass-in
    const scenePassthrough1 = scenePassthrough({
        "scene": scene,
      })

    // @scene-id node-dz-explode
    const nodeExplode2 = nodeExplode({
        "scene": scenePassthrough1.scene,
      })

    // @scene-id node-dz-rect
    const rectangularGrid3 = rectangularGrid({
        "fillValue": input10,
        "width": nodeExplode2.width,
        "height": nodeExplode2.height,
      })

    // @scene-id node-dz-slice
    const voxelSlice4 = voxelSlice({
        "z": input9,
        "voxels": nodeExplode2.voxels,
        "grid": rectangularGrid3.grid,
      })

    // @scene-id node-dz-field
    const algFieldInnerDistance5 = algFieldInnerDistance({
        "includeOuterBoundary": includeOuterBoundary,
        "connectivity": input7,
        "normalize": input8,
        "region": voxelSlice4.slice,
      })

    // @scene-id node-dz-threshold
    const algFieldThreshold6 = algFieldThreshold({
        "threshold": threshold,
        "region": voxelSlice4.slice,
        "field": algFieldInnerDistance5.field,
      })

    // @scene-id node-dz-g2n-near
    const gridSceneNode7 = gridSceneNode({
        "name": nearName,
        "schema": input11,
        "token": input12,
        "zRange": input13,
        "grid": algFieldThreshold6.near,
      })

    // @scene-id group_1783200020000_tanear
    const distanceZonesNearAssetName8 = distanceZonesNearAssetName({
        "input1": nearAsset,
        "input0": gridSceneNode7.scene,
      })

    // @scene-id node-dz-addchild-near
    const addSceneChildren9 = addSceneChildren({
        "nodes": distanceZonesNearAssetName8.output0,
        "scene": scenePassthrough1.scene,
      })

    // @scene-id node-dz-g2n-far
    const gridSceneNode10 = gridSceneNode({
        "name": farName,
        "zRange": input14,
        "grid": algFieldThreshold6.far,
      })

    // @scene-id group_1783200020000_tafar
    const distanceZonesFarAssetName11 = distanceZonesFarAssetName({
        "input1": farAsset,
        "input0": gridSceneNode10.scene,
      })

    // @scene-id node-dz-addchild-far
    const addSceneChildren12 = addSceneChildren({
        "nodes": distanceZonesFarAssetName11.output0,
        "scene": addSceneChildren9.scene,
      })

    // @scene-id node-dz-merge
    const sceneMergeSubtrees13 = sceneMergeSubtrees({
        "scenes": addSceneChildren12.scene,
      })

    // @scene-id node-dz-focus-near
    const sceneFocusPath14 = sceneFocusPath({
        "scene": sceneMergeSubtrees13.scene,
        "path": addSceneChildren9.childPaths,
      })

    // @scene-id node-dz-focus-far
    const sceneFocusPath15 = sceneFocusPath({
        "scene": sceneMergeSubtrees13.scene,
        "path": addSceneChildren12.childPaths,
      })

    // @scene-id node-dz-pass-near
    const scenePassthrough16 = scenePassthrough({
        "scene": sceneFocusPath14.scene,
      })

    // @scene-id node-dz-pass-far
    const scenePassthrough17 = scenePassthrough({
        "scene": sceneFocusPath15.scene,
      })

    // @scene-id node-dz-pass-scene
    const scenePassthrough18 = scenePassthrough({
        "scene": sceneMergeSubtrees13.scene,
      })

    // @scene-id node-dz-type-nearpath
    const stringValue19 = stringValue({
        "value": addSceneChildren9.childPaths,
      })

    // @scene-id node-dz-type-farpath
    const stringValue20 = stringValue({
        "value": addSceneChildren12.childPaths,
      })
    return {
      scene: scenePassthrough18.scene,
      near: scenePassthrough16.scene,
      far: scenePassthrough17.scene,
      nearPath: stringValue19.value,
      farPath: stringValue20.value,
    }
  },
)
