// Generated by scripts/generate-native-group-definitions.mts.
// JSON parity oracle only: batteries/templates/structures/water/RiverSpline/RiverSpline.json
// @scene-id definition:batteries.templates.structures.water.river-spline.river-spline.nested.0
const riverSplineTemplateTileAssetName = defineGroup(
  {
    id: "scene.template.river-spline.nested.0",
    version: "1.0.0",
    inputs: {
      input0: { type: Scene, runtimeType: "scene", runtimePort: "in_0", access: "item" },
      input1: { type: StringValue, runtimeType: "string", runtimePort: "in_1", access: "tree" },
    },
    outputs: {
      output0: { type: Scene, runtimeType: "scene", runtimePort: "out_0", access: "item" },
    },
  },
  ({ input0, input1 }) => {
    // @scene-id node-1790000000008-ptt9f
    const textPanel1 = textPanel({
        "$params": {"text":"asset_name","_nodeWidth":180,"_nodeHeight":67},
      })

    // @scene-id node-1790000000008-rm2fy
    const textPanel2 = textPanel({
        "$params": {"text":"asset_type","_nodeWidth":181,"_nodeHeight":60},
      })

    // @scene-id node-1790000000008-obfmb
    const textPanel3 = textPanel({
        "$params": {"text":"tile","_nodeWidth":181,"_nodeHeight":60},
      })

    // @scene-id node-1790000000008-94gxn
    const stringValue4 = stringValue({
        "value": input1,
      })

    // @scene-id node-1790000000008-4twly
    const sceneSetAttribute5 = sceneSetAttribute({
        "scene": input0,
        "key": textPanel1.output,
        "value": stringValue4.value,
      })

    // @scene-id node-1790000000008-0767k
    const sceneSetAttribute6 = sceneSetAttribute({
        "scene": sceneSetAttribute5.scene,
        "key": textPanel2.output,
        "value": textPanel3.output,
      })
    return {
      output0: sceneSetAttribute6.scene,
    }
  },
)

// @scene-id definition:batteries.templates.structures.water.river-spline.river-spline
export const riverSplineTemplate = defineGroup(
  {
    id: "scene.template.river-spline",
    version: "1.0.0",
    inputs: {
      scene: { type: Scene, runtimeType: "scene", runtimePort: "in_0", access: "tree", labelEn: "Scene" },
      assetName: { type: StringValue, runtimeType: "string", runtimePort: "in_1", labelEn: "AssetName" },
      seed: { type: NumberValue, runtimeType: "number", runtimePort: "in_2", access: "tree", labelEn: "Seed" },
      points: { type: Any, runtimeType: "array", runtimePort: "in_3", access: "item", labelEn: "Points" },
      algorithm: { type: StringValue, runtimeType: "string", runtimePort: "in_4", access: "item", labelEn: "Algorithm" },
      riverWidth: { type: NumberValue, runtimeType: "number", runtimePort: "in_5", access: "item", labelEn: "RiverWidth" },
      numMidPoints: { type: NumberValue, runtimeType: "number", runtimePort: "in_6", access: "item", labelEn: "NumMidPoints" },
      offsetMin: { type: NumberValue, runtimeType: "number", runtimePort: "in_7", access: "item", labelEn: "OffsetMin" },
      offsetMax: { type: NumberValue, runtimeType: "number", runtimePort: "in_8", access: "item", labelEn: "OffsetMax" },
      segmentUniformity: { type: NumberValue, runtimeType: "number", runtimePort: "in_9", access: "item", labelEn: "SegmentUniformity" },
      input10: { type: NumberValue, runtimeType: "number", runtimePort: "in_10", access: "item", hidden: true },
      input11: { type: NumberValue, runtimeType: "number", runtimePort: "in_11", access: "item", hidden: true },
      input12: { type: NumberValue, runtimeType: "number", runtimePort: "in_12", access: "item", hidden: true },
      input13: { type: NumberValue, runtimeType: "number", runtimePort: "in_13", access: "item", hidden: true },
      input14: { type: NumberValue, runtimeType: "number", runtimePort: "in_14", access: "item", hidden: true },
      input15: { type: StringValue, runtimeType: "string", runtimePort: "in_15", access: "item", hidden: true },
      input16: { type: StringValue, runtimeType: "string", runtimePort: "in_16", access: "item", hidden: true },
      input17: { type: NumberList, runtimeType: "number", runtimePort: "in_17", access: "list", hidden: true },
    },
    outputs: {
      scene: { type: Scene, runtimeType: "scene", runtimePort: "out_0", access: "tree", order: 0, labelEn: "Scene" },
      river: { type: Scene, runtimeType: "scene", runtimePort: "out_1", access: "tree", order: 1, labelEn: "River" },
      rest: { type: Scene, runtimeType: "scene", runtimePort: "out_2", access: "tree", order: 2, labelEn: "Rest" },
      riverPath: { type: StringValue, runtimeType: "string", runtimePort: "out_3", access: "tree", order: 3, labelEn: "RiverPath" },
      restPath: { type: StringValue, runtimeType: "string", runtimePort: "out_4", access: "tree", order: 4, labelEn: "RestPath" },
    },
  },
  ({ scene, assetName, seed, points, algorithm, riverWidth, numMidPoints, offsetMin, offsetMax, segmentUniformity, input10, input11, input12, input13, input14, input15, input16, input17 }) => {
    // @scene-id node-1790000000008-c6vfi
    const scenePassthrough1 = scenePassthrough({
        "scene": scene,
      })

    // @scene-id node-1790000000008-du9e8
    const nodeExplode2 = nodeExplode({
        "scene": scenePassthrough1.scene,
      })

    // @scene-id node-1790000000008-6viw4
    const rectangularGrid3 = rectangularGrid({
        "fillValue": input13,
        "width": nodeExplode2.width,
        "height": nodeExplode2.height,
      })

    // @scene-id node-1790000000008-kej41
    const voxelSlice4 = voxelSlice({
        "z": input14,
        "voxels": nodeExplode2.voxels,
        "grid": rectangularGrid3.grid,
      })

    // @scene-id node-1790000000008-k9f8t
    const multiSeed5 = multiSeed({
        "seed": seed,
        "shape": voxelSlice4.slice,
      })

    // @scene-id node-1790000000008-h4vj0
    const riverSpline6 = riverSpline({
        "points": points,
        "algorithm": algorithm,
        "riverWidth": riverWidth,
        "numMidPoints": numMidPoints,
        "offsetMin": offsetMin,
        "offsetMax": offsetMax,
        "segmentUniformity": segmentUniformity,
        "windowSize": input10,
        "sigma": input11,
        "bezierDegree": input12,
        "inputGrid": voxelSlice4.slice,
        "seed": multiSeed5.seed,
      })

    // @scene-id node-1790000000008-slehw
    const gridSplitByValue7 = gridSplitByValue({
        "grid": riverSpline6.outputGrid,
      })

    // @scene-id node-1790000000008-i7rtn
    const strToListBranches8 = strToListBranches({
        "str": assetName,
      })

    // @scene-id node-1790000000008-tkeb1
    const gridSceneNode9 = gridSceneNode({
        "schema": input15,
        "token": input16,
        "zRange": input17,
        "grid": gridSplitByValue7.grids,
        "name": strToListBranches8.items,
      })

    // @scene-id group_1790000000008_hg1xq
    const riverSplineTemplateTileAssetName10 = riverSplineTemplateTileAssetName({
        "input0": gridSceneNode9.scene,
        "input1": strToListBranches8.items,
      })

    // @scene-id node-1790000000008-3eptq
    const addSceneChildren11 = addSceneChildren({
        "nodes": riverSplineTemplateTileAssetName10.output0,
        "scene": scenePassthrough1.scene,
      })

    // @scene-id node-1790000000008-7vrak
    const algRegionSubtract12 = algRegionSubtract({
        "a": voxelSlice4.slice,
        "b": riverSpline6.outputGrid,
      })

    // @scene-id node-1790000000008-2kmi6
    const textPanel13 = textPanel({
        "$params": {"text":"rest","_nodeWidth":172,"_nodeHeight":69},
      })

    // @scene-id node-1790000000008-6ldzn
    const gridSceneNode14 = gridSceneNode({
        "grid": algRegionSubtract12.region,
        "name": textPanel13.output,
      })

    // @scene-id node-1790000000008-ynr0v
    const addSceneChildren15 = addSceneChildren({
        "scene": addSceneChildren11.scene,
        "nodes": gridSceneNode14.scene,
      })

    // @scene-id node-1790000000008-xykwm
    const sceneMergeSubtrees16 = sceneMergeSubtrees({
        "scenes": addSceneChildren15.scene,
      })

    // @scene-id node-1790000000008-9l2e4
    const sceneFocusPath17 = sceneFocusPath({
        "scene": sceneMergeSubtrees16.scene,
        "path": addSceneChildren11.childPaths,
      })

    // @scene-id node-1790000000008-7hkpo
    const sceneFocusPath18 = sceneFocusPath({
        "scene": sceneMergeSubtrees16.scene,
        "path": addSceneChildren15.childPaths,
      })

    // @scene-id node-1790000000008-g36ob
    const scenePassthrough19 = scenePassthrough({
        "scene": sceneMergeSubtrees16.scene,
      })

    // @scene-id node-1790000000008-xgreg
    const scenePassthrough20 = scenePassthrough({
        "scene": sceneFocusPath17.scene,
      })

    // @scene-id node-1790000000008-o1ju5
    const scenePassthrough21 = scenePassthrough({
        "scene": sceneFocusPath18.scene,
      })

    // @scene-id node-1790000000008-4djdc
    const stringValue22 = stringValue({
        "value": addSceneChildren11.childPaths,
      })

    // @scene-id node-1790000000008-4kbf3
    const stringValue23 = stringValue({
        "value": addSceneChildren15.childPaths,
      })
    return {
      scene: scenePassthrough19.scene,
      river: scenePassthrough20.scene,
      rest: scenePassthrough21.scene,
      riverPath: stringValue22.value,
      restPath: stringValue23.value,
    }
  },
)
