// Generated by scripts/generate-native-group-definitions.mts.
// JSON parity oracle only: batteries/templates/structures/decorations/DecorationBorder/DecorationBorder.json
// @scene-id definition:batteries.templates.structures.decorations.decoration-border.decoration-border.nested.0
const decorationBorderTemplateObjectAssetName = defineGroup(
  {
    id: "scene.template.decoration-border.nested.0",
    version: "1.0.0",
    inputs: {
      input0: { type: Scene, runtimeType: "scene", runtimePort: "in_0", access: "item" },
      input1: { type: StringValue, runtimeType: "string", runtimePort: "in_1", access: "tree" },
    },
    outputs: {
      output0: { type: Scene, runtimeType: "scene", runtimePort: "out_0", access: "item" },
    },
  },
  ({ input0, input1 }) => {
    // @scene-id db-an-name
    const textPanel1 = textPanel({
        "$params": {"text":"asset_name"},
      })

    // @scene-id db-an-type
    const textPanel2 = textPanel({
        "$params": {"text":"asset_type"},
      })

    // @scene-id db-an-obj
    const textPanel3 = textPanel({
        "$params": {"text":"object"},
      })

    // @scene-id db-an-str
    const stringValue4 = stringValue({
        "value": input1,
      })

    // @scene-id db-an-set1
    const sceneSetAttribute5 = sceneSetAttribute({
        "scene": input0,
        "key": textPanel1.output,
        "value": stringValue4.value,
      })

    // @scene-id db-an-set2
    const sceneSetAttribute6 = sceneSetAttribute({
        "scene": sceneSetAttribute5.scene,
        "key": textPanel2.output,
        "value": textPanel3.output,
      })
    return {
      output0: sceneSetAttribute6.scene,
    }
  },
)

// @scene-id definition:batteries.templates.structures.decorations.decoration-border.decoration-border
export const decorationBorderTemplate = defineGroup(
  {
    id: "scene.template.decoration-border",
    version: "1.0.0",
    inputs: {
      scene: { type: Scene, runtimeType: "scene", runtimePort: "in_0", access: "tree", order: 0, labelEn: "Scene" },
      assetName: { type: StringValue, runtimeType: "string", runtimePort: "in_1", access: "tree", order: 1, labelEn: "AssetName" },
      decorationName: { type: StringValue, runtimeType: "string", runtimePort: "in_2", order: 2, labelEn: "DecorationName" },
      count: { type: NumberValue, runtimeType: "number", runtimePort: "in_3", access: "item", order: 3, labelEn: "Count" },
      fillMode: { type: StringValue, runtimeType: "string", runtimePort: "in_4", access: "item", order: 4, labelEn: "FillMode" },
      offset: { type: NumberValue, runtimeType: "number", runtimePort: "in_5", access: "item", order: 5, labelEn: "Offset" },
      seed: { type: NumberValue, runtimeType: "number", runtimePort: "in_6", access: "item", order: 6, labelEn: "Seed" },
      input7: { type: BooleanValue, runtimeType: "bool", runtimePort: "in_7", access: "item", hidden: true, order: 7 },
      input8: { type: NumberValue, runtimeType: "number", runtimePort: "in_8", access: "item", hidden: true, order: 8 },
      input9: { type: NumberValue, runtimeType: "number", runtimePort: "in_9", access: "item", hidden: true, order: 9 },
    },
    outputs: {
      scene: { type: Scene, runtimeType: "scene", runtimePort: "out_0", access: "item", order: 0, labelEn: "Scene" },
      decoration: { type: Scene, runtimeType: "scene", runtimePort: "out_1", access: "item", order: 1, labelEn: "Decoration" },
      rest: { type: Scene, runtimeType: "scene", runtimePort: "out_2", access: "item", order: 2, labelEn: "Rest" },
      decorationPath: { type: StringValue, runtimeType: "string", runtimePort: "out_3", access: "tree", order: 3, labelEn: "DecorationPath" },
      restPath: { type: StringValue, runtimeType: "string", runtimePort: "out_4", access: "tree", order: 4, labelEn: "RestPath" },
    },
  },
  ({ scene, assetName, decorationName, count, fillMode, offset, seed, input7, input8, input9 }) => {
    // @scene-id db-pt
    const scenePassthrough1 = scenePassthrough({
        "scene": scene,
      })

    // @scene-id db-ex
    const nodeExplode2 = nodeExplode({
        "scene": scenePassthrough1.scene,
      })

    // @scene-id db-rg
    const rectangularGrid3 = rectangularGrid({
        "width": nodeExplode2.width,
        "height": nodeExplode2.height,
      })

    // @scene-id db-vs
    const voxelSlice4 = voxelSlice({
        "voxels": nodeExplode2.voxels,
        "grid": rectangularGrid3.grid,
      })

    // @scene-id db-bat
    const decorationBorder5 = decorationBorder({
        "decorationName": decorationName,
        "count": count,
        "fillMode": fillMode,
        "offset": offset,
        "seed": seed,
        "rotate": input7,
        "startCount": input8,
        "itemSpacing": input9,
        "inputGrid": voxelSlice4.slice,
      })

    // @scene-id db-txd
    const textPanel6 = textPanel({
        "$params": {"text":"decoration"},
      })

    // @scene-id db-g2d
    const gridSceneNode7 = gridSceneNode({
        "grid": decorationBorder5.outputGrid,
        "name": textPanel6.output,
      })

    // @scene-id group_db_objasset
    const decorationBorderTemplateObjectAssetName8 = decorationBorderTemplateObjectAssetName({
        "input1": assetName,
        "input0": gridSceneNode7.scene,
      })

    // @scene-id db-ac1
    const addSceneChildren9 = addSceneChildren({
        "nodes": decorationBorderTemplateObjectAssetName8.output0,
        "scene": scenePassthrough1.scene,
      })

    // @scene-id db-sub
    const algRegionSubtract10 = algRegionSubtract({
        "a": voxelSlice4.slice,
        "b": decorationBorder5.outputGrid,
      })

    // @scene-id db-txr
    const textPanel11 = textPanel({
        "$params": {"text":"rest"},
      })

    // @scene-id db-g2r
    const gridSceneNode12 = gridSceneNode({
        "grid": algRegionSubtract10.region,
        "name": textPanel11.output,
      })

    // @scene-id db-ac2
    const addSceneChildren13 = addSceneChildren({
        "nodes": gridSceneNode12.scene,
        "scene": addSceneChildren9.scene,
      })

    // @scene-id db-fpd
    const sceneFocusPath14 = sceneFocusPath({
        "scene": addSceneChildren13.scene,
        "path": addSceneChildren9.childPaths,
      })

    // @scene-id db-fpr
    const sceneFocusPath15 = sceneFocusPath({
        "scene": addSceneChildren13.scene,
        "path": addSceneChildren13.childPaths,
      })

    // @scene-id db-tsd
    const stringValue16 = stringValue({
        "value": addSceneChildren9.childPaths,
      })

    // @scene-id db-tsr
    const stringValue17 = stringValue({
        "value": addSceneChildren13.childPaths,
      })
    return {
      scene: addSceneChildren13.scene,
      decoration: sceneFocusPath14.scene,
      rest: sceneFocusPath15.scene,
      decorationPath: stringValue16.value,
      restPath: stringValue17.value,
    }
  },
)
