// Generated by scripts/generate-native-group-definitions.mts.
// JSON parity oracle only: batteries/groups/scene/LocalPreciseDecoration/LocalPreciseDecoration.json
// @scene-id definition:batteries.groups.scene.local-precise-decoration.local-precise-decoration.nested.0
const localPreciseDecorationGroupMultiNames = defineGroup(
  {
    id: "scene.group.scene.local-precise-decoration.local-precise-decoration.nested.0",
    version: "1.0.0",
    inputs: {
      input0: { type: StringValue, runtimeType: "string", runtimePort: "in_0", access: "tree", hidden: true },
      count: { type: NumberValue, runtimeType: "number", runtimePort: "in_1", access: "tree", labelEn: "Count" },
      input2: { type: NumberValue, runtimeType: "number", runtimePort: "in_2", access: "item", hidden: true },
      prefix: { type: StringValue, runtimeType: "string", runtimePort: "in_3", access: "tree", labelEn: "Prefix" },
    },
    outputs: {
      output0: { type: NumberList, runtimeType: "number", runtimePort: "out_0", access: "list", hidden: true },
      names: { type: StringList, runtimeType: "string", runtimePort: "out_1", access: "list", labelEn: "Names" },
      output2: { type: NumberValue, runtimeType: "number", runtimePort: "out_2", access: "item" },
    },
  },
  ({ input0, count, input2, prefix }) => {
    // @scene-id node-1781858738320-yvvif
    const numberValue1 = numberValue({})

    // @scene-id node-1781858738320-g8h3c
    const numberValue2 = numberValue({
        "$params": {"value":1},
      })

    // @scene-id node-1781858738320-xcdeo
    const typeNumber3 = typeNumber({
        "value": count,
      })

    // @scene-id node-1781858738320-856y0
    const basicMathOp4 = basicMathOp({
        "$params": {"op":"-"},
        "op": input0,
        "b": numberValue2.value,
        "a": typeNumber3.value,
      })

    // @scene-id node-1781858738320-7e74g
    const stringValue5 = stringValue({
        "value": prefix,
      })

    // @scene-id node-1781858738320-wq05v
    const rangeList6 = rangeList({
        "step": input2,
        "start": numberValue1.value,
        "end": basicMathOp4.result,
        "prefix": stringValue5.value,
      })
    return {
      output0: rangeList6.list,
      names: rangeList6.stringList,
      output2: rangeList6.count,
    }
  },
)

// @scene-id definition:batteries.groups.scene.local-precise-decoration.local-precise-decoration.nested.1
const localPreciseDecorationGroupObjectAssetName = defineGroup(
  {
    id: "scene.group.scene.local-precise-decoration.local-precise-decoration.nested.1",
    version: "1.0.0",
    inputs: {
      input0: { type: Scene, runtimeType: "scene", runtimePort: "in_0", access: "item" },
      input1: { type: StringValue, runtimeType: "string", runtimePort: "in_1", access: "tree" },
    },
    outputs: {
      output0: { type: Scene, runtimeType: "scene", runtimePort: "out_0", access: "item" },
    },
  },
  ({ input0, input1 }) => {
    // @scene-id node-1781858738320-lhmix
    const textPanel1 = textPanel({
        "$params": {"text":"asset_name","_nodeWidth":180,"_nodeHeight":67},
      })

    // @scene-id node-1781858738320-r4n47
    const textPanel2 = textPanel({
        "$params": {"text":"asset_type","_nodeWidth":181,"_nodeHeight":60},
      })

    // @scene-id node-1781858738320-rwp0d
    const textPanel3 = textPanel({
        "$params": {"text":"object","_nodeWidth":181,"_nodeHeight":60},
      })

    // @scene-id node-1781858738320-a68n0
    const stringValue4 = stringValue({
        "value": input1,
      })

    // @scene-id node-1781858738320-yvrcz
    const sceneSetAttribute5 = sceneSetAttribute({
        "scene": input0,
        "key": textPanel1.output,
        "value": stringValue4.value,
      })

    // @scene-id node-1781858738320-ljp4f
    const sceneSetAttribute6 = sceneSetAttribute({
        "scene": sceneSetAttribute5.scene,
        "key": textPanel2.output,
        "value": textPanel3.output,
      })
    return {
      output0: sceneSetAttribute6.scene,
    }
  },
)

// @scene-id definition:batteries.groups.scene.local-precise-decoration.local-precise-decoration
export const localPreciseDecorationGroup = defineGroup(
  {
    id: "scene.group.scene.local-precise-decoration.local-precise-decoration",
    version: "1.0.0",
    inputs: {
      scene: { type: Scene, runtimeType: "scene", runtimePort: "in_1", access: "tree", labelEn: "Scene" },
      input1: { type: NumberValue, runtimeType: "number", runtimePort: "in_6", access: "item", hidden: true },
      input2: { type: NumberValue, runtimeType: "number", runtimePort: "in_7", access: "item", hidden: true },
      input3: { type: StringValue, runtimeType: "string", runtimePort: "in_8", access: "item", hidden: true },
      input4: { type: StringValue, runtimeType: "string", runtimePort: "in_9", access: "item", hidden: true },
      input5: { type: StringValue, runtimeType: "string", runtimePort: "in_10", access: "item", hidden: true },
      input6: { type: StringValue, runtimeType: "string", runtimePort: "in_11", access: "item", hidden: true },
      namePrefix: { type: StringValue, runtimeType: "string", runtimePort: "in_0", access: "tree", labelEn: "NamePrefix" },
      assetName: { type: StringValue, runtimeType: "string", runtimePort: "in_5", access: "tree", labelEn: "AssetName" },
      input9: { type: NumberValue, runtimeType: "number", runtimePort: "in_15", access: "item", hidden: true },
      input10: { type: StringValue, runtimeType: "string", runtimePort: "in_16", access: "item", hidden: true },
      input11: { type: StringValue, runtimeType: "string", runtimePort: "in_17", access: "tree", hidden: true },
      zHeight: { type: NumberValue, runtimeType: "number", runtimePort: "in_4", access: "item", labelEn: "zHeight" },
      input13: { type: StringValue, runtimeType: "string", runtimePort: "in_18", access: "tree", hidden: true },
      input14: { type: NumberValue, runtimeType: "number", runtimePort: "in_3", access: "tree" },
      point: { type: Point2d, runtimeType: "point2d", runtimePort: "in_2", access: "item", labelEn: "Point" },
      count: { type: NumberValue, runtimeType: "number", runtimePort: "in_19", access: "item", labelEn: "Count" },
      scatterRadius: { type: NumberValue, runtimeType: "number", runtimePort: "in_20", access: "item", labelEn: "ScatterRadius" },
      algorithm: { type: StringValue, runtimeType: "string", runtimePort: "in_21", access: "item", labelEn: "Algorithm" },
    },
    outputs: {
      scene: { type: Scene, runtimeType: "scene", runtimePort: "out_0", access: "tree", order: 0, labelEn: "Scene" },
      decoration: { type: Scene, runtimeType: "scene", runtimePort: "out_1", access: "tree", order: 1, labelEn: "Decoration" },
      rest: { type: Scene, runtimeType: "scene", runtimePort: "out_2", access: "tree", order: 3, labelEn: "Rest" },
      output3: { type: NumberValue, runtimeType: "number", runtimePort: "out_3", access: "item", hidden: true, order: 4 },
      decorationPath: { type: StringValue, runtimeType: "string", runtimePort: "out_4", access: "tree", order: 2, labelEn: "DecorationPath" },
      restPath: { type: StringValue, runtimeType: "string", runtimePort: "out_5", access: "tree", order: 5, labelEn: "RestPath" },
    },
  },
  ({ scene, input1, input2, input3, input4, input5, input6, namePrefix, assetName, input9, input10, input11, zHeight, input13, input14, point, count, scatterRadius, algorithm }) => {
    // @scene-id node-1781858738320-zohzz
    const scenePassthrough1 = scenePassthrough({
        "scene": scene,
      })

    // @scene-id node-1781858738320-700u8
    const nodeExplode2 = nodeExplode({
        "scene": scenePassthrough1.scene,
      })

    // @scene-id node-1781858738320-pqan3
    const rectangularGrid3 = rectangularGrid({
        "fillValue": input1,
        "height": nodeExplode2.height,
        "width": nodeExplode2.width,
      })

    // @scene-id node-1781858738320-afbxs
    const voxelSlice4 = voxelSlice({
        "z": input2,
        "voxels": nodeExplode2.voxels,
        "grid": rectangularGrid3.grid,
      })

    // @scene-id node-1781858738320-pyalj
    const textPanel5 = textPanel({
        "$params": {"text":"rest","_nodeWidth":172,"_nodeHeight":69},
      })

    // @scene-id node-1781858738320-48fpl
    const numberValue6 = numberValue({
        "$params": {"value":1,"min":0,"max":10,"precision":0},
      })

    // @scene-id node-1781858738320-qxplc
    const numberValue7 = numberValue({
        "$params": {"value":1,"min":0,"max":10,"precision":0},
      })

    // @scene-id node-1781858738320-tkxlv
    const multiSeed8 = multiSeed({
        "seed": input14,
        "shape": voxelSlice4.slice,
      })

    // @scene-id node-1781858738320-xdge2
    const algPointsCenterScatter9 = algPointsCenterScatter({
        "point": point,
        "count": count,
        "scatterRadius": scatterRadius,
        "algorithm": algorithm,
        "region": voxelSlice4.slice,
        "seed": multiSeed8.seed,
      })

    // @scene-id node-1781858738320-37e02
    const algRegionUnionAll10 = algRegionUnionAll({
        "regions": algPointsCenterScatter9.points,
      })

    // @scene-id node-1781858738320-jzbwd
    const algRegionSubtract11 = algRegionSubtract({
        "a": voxelSlice4.slice,
        "b": algRegionUnionAll10.region,
      })

    // @scene-id group_1781858738320_hqi4y
    const localPreciseDecorationGroupMultiNames12 = localPreciseDecorationGroupMultiNames({
        "prefix": namePrefix,
        "count": algPointsCenterScatter9.count,
      })

    // @scene-id node-1782115602603
    const basicMathOp13 = basicMathOp({
        "op": input11,
        "a": voxelSlice4.z,
        "b": numberValue6.value,
      })

    // @scene-id node-1782115684352-5js94
    const basicMathOp14 = basicMathOp({
        "b": zHeight,
        "op": input13,
        "a": voxelSlice4.z,
      })

    // @scene-id node-1781858738320-5jqbg
    const rangeList15 = rangeList({
        "step": input9,
        "prefix": input10,
        "start": basicMathOp13.result,
        "end": basicMathOp14.result,
      })

    // @scene-id node-1781858738320-z22j0
    const gridSceneNode16 = gridSceneNode({
        "schema": input3,
        "token": input4,
        "name": localPreciseDecorationGroupMultiNames12.names,
        "grid": algPointsCenterScatter9.points,
        "zRange": rangeList15.list,
      })

    // @scene-id group_1781858738320_akwyt
    const localPreciseDecorationGroupObjectAssetName17 = localPreciseDecorationGroupObjectAssetName({
        "input1": assetName,
        "input0": gridSceneNode16.scene,
      })

    // @scene-id node-1781858738320-8zgfb
    const addSceneChildren18 = addSceneChildren({
        "scene": scenePassthrough1.scene,
        "nodes": localPreciseDecorationGroupObjectAssetName17.output0,
      })

    // @scene-id node-1781858738320-3qolb
    const stringValue19 = stringValue({
        "value": addSceneChildren18.childPaths,
      })

    // @scene-id node-1782116136996
    const voxelRange20 = voxelRange({
        "voxels": nodeExplode2.voxels,
      })

    // @scene-id node-1781858738320-ld1ji
    const gridSceneNode21 = gridSceneNode({
        "schema": input5,
        "token": input6,
        "name": textPanel5.output,
        "grid": algRegionSubtract11.region,
        "zRange": voxelRange20.zRange,
      })

    // @scene-id node-1781858738320-s02ik
    const addSceneChildren22 = addSceneChildren({
        "scene": addSceneChildren18.scene,
        "nodes": gridSceneNode21.scene,
      })

    // @scene-id node-1781858738320-rrl6m
    const sceneMergeSubtrees23 = sceneMergeSubtrees({
        "scenes": addSceneChildren22.scene,
      })

    // @scene-id node-1781858738320-2pz49
    const scenePassthrough24 = scenePassthrough({
        "scene": sceneMergeSubtrees23.scene,
      })

    // @scene-id node-1781858738320-gq0uq
    const sceneFocusPath25 = sceneFocusPath({
        "scene": sceneMergeSubtrees23.scene,
        "path": addSceneChildren22.childPaths,
      })

    // @scene-id node-1781858738320-9fbqi
    const scenePassthrough26 = scenePassthrough({
        "scene": sceneMergeSubtrees23.scene,
      })

    // @scene-id node-1781858738320-d5gd5
    const scenePassthrough27 = scenePassthrough({
        "scene": sceneFocusPath25.scene,
      })

    // @scene-id node-1781858738320-1zauf
    const stringValue28 = stringValue({
        "value": addSceneChildren22.childPaths,
      })
    return {
      scene: scenePassthrough24.scene,
      decoration: scenePassthrough26.scene,
      rest: scenePassthrough27.scene,
      output3: numberValue7.value,
      decorationPath: stringValue19.value,
      restPath: stringValue28.value,
    }
  },
)
