// Generated by scripts/generate-native-group-definitions.mts.
// JSON parity oracle only: batteries/templates/structures/districts/BspDistrictCluster/BspDistrictCluster.json
// @scene-id definition:batteries.templates.structures.districts.bsp-district-cluster.bsp-district-cluster.nested.0
const bspDistrictClusterTileAssetName = defineGroup(
  {
    id: "scene.template.bsp-district-cluster.nested.0",
    version: "1.0.0",
    inputs: {
      input0: { type: Scene, runtimeType: "scene", runtimePort: "in_0", access: "item" },
      input1: { type: StringValue, runtimeType: "string", runtimePort: "in_1", access: "tree" },
    },
    outputs: {
      output0: { type: Scene, runtimeType: "scene", runtimePort: "out_0", access: "item" },
    },
  },
  ({ input0, input1 }) => {
    // @scene-id node-1782298073824-ptt9f
    const textPanel1 = textPanel({
        "$params": {"text":"asset_name","_nodeWidth":180,"_nodeHeight":67},
      })

    // @scene-id node-1782298073824-rm2fy
    const textPanel2 = textPanel({
        "$params": {"text":"asset_type","_nodeWidth":181,"_nodeHeight":60},
      })

    // @scene-id node-1782298073824-obfmb
    const textPanel3 = textPanel({
        "$params": {"text":"tile","_nodeWidth":181,"_nodeHeight":60},
      })

    // @scene-id node-1782298073824-94gxn
    const stringValue4 = stringValue({
        "value": input1,
      })

    // @scene-id node-1782298073824-4twly
    const sceneSetAttribute5 = sceneSetAttribute({
        "scene": input0,
        "key": textPanel1.output,
        "value": stringValue4.value,
      })

    // @scene-id node-1782298073824-0767k
    const sceneSetAttribute6 = sceneSetAttribute({
        "scene": sceneSetAttribute5.scene,
        "key": textPanel2.output,
        "value": textPanel3.output,
      })
    return {
      output0: sceneSetAttribute6.scene,
    }
  },
)

// @scene-id definition:batteries.templates.structures.districts.bsp-district-cluster.bsp-district-cluster
export const bspDistrictCluster = defineGroup(
  {
    id: "scene.template.bsp-district-cluster",
    version: "1.0.0",
    inputs: {
      input0: { type: Scene, runtimeType: "scene", runtimePort: "in_0", access: "tree" },
      districtAsset: { type: StringValue, runtimeType: "string", runtimePort: "in_1", labelEn: "DistrictAsset" },
      seed: { type: NumberValue, runtimeType: "number", runtimePort: "in_2", access: "tree", labelEn: "Seed" },
      point: { type: Point2d, runtimeType: "point2d", runtimePort: "in_3", access: "item", labelEn: "Point" },
      rectCount: { type: NumberValue, runtimeType: "number", runtimePort: "in_4", access: "item", labelEn: "RectCount" },
      minSize: { type: NumberValue, runtimeType: "number", runtimePort: "in_5", access: "item", labelEn: "MinSize" },
      maxSize: { type: NumberValue, runtimeType: "number", runtimePort: "in_6", access: "item", labelEn: "MaxSize" },
      splitRatio: { type: NumberValue, runtimeType: "number", runtimePort: "in_7", access: "item", hidden: true, labelEn: "SplitRatio" },
      input8: { type: NumberValue, runtimeType: "number", runtimePort: "in_8", access: "item", hidden: true },
      input9: { type: NumberValue, runtimeType: "number", runtimePort: "in_9", access: "item", hidden: true },
      input10: { type: StringValue, runtimeType: "string", runtimePort: "in_10", access: "item", hidden: true },
      input11: { type: StringValue, runtimeType: "string", runtimePort: "in_11", access: "item", hidden: true },
      input12: { type: NumberList, runtimeType: "number", runtimePort: "in_12", access: "list", hidden: true },
    },
    outputs: {
      scene: { type: Scene, runtimeType: "scene", runtimePort: "out_0", access: "tree", order: 0, labelEn: "Scene" },
      rest: { type: Scene, runtimeType: "scene", runtimePort: "out_1", access: "tree", order: 1, labelEn: "Rest" },
      district: { type: Scene, runtimeType: "scene", runtimePort: "out_2", access: "tree", order: 2, labelEn: "District" },
      districtPath: { type: StringValue, runtimeType: "string", runtimePort: "out_3", access: "tree", order: 3, labelEn: "DistrictPath" },
      restPath: { type: StringValue, runtimeType: "string", runtimePort: "out_4", access: "tree", order: 4, labelEn: "RestPath" },
    },
  },
  ({ input0, districtAsset, seed, point, rectCount, minSize, maxSize, splitRatio, input8, input9, input10, input11, input12 }) => {
    // @scene-id node-1782298073824-c6vfi
    const scenePassthrough1 = scenePassthrough({
        "scene": input0,
      })

    // @scene-id node-1782298073824-du9e8
    const nodeExplode2 = nodeExplode({
        "scene": scenePassthrough1.scene,
      })

    // @scene-id node-1782298073824-6viw4
    const rectangularGrid3 = rectangularGrid({
        "fillValue": input8,
        "width": nodeExplode2.width,
        "height": nodeExplode2.height,
      })

    // @scene-id node-1782298073824-kej41
    const voxelSlice4 = voxelSlice({
        "z": input9,
        "voxels": nodeExplode2.voxels,
        "grid": rectangularGrid3.grid,
      })

    // @scene-id node-1782298073824-k9f8t
    const multiSeed5 = multiSeed({
        "seed": seed,
        "shape": voxelSlice4.slice,
      })

    // @scene-id node-1782298073824-h4vj0
    const bspRectGen6 = bspRectGen({
        "centerPoint": point,
        "targetCount": rectCount,
        "minSize": minSize,
        "maxSize": maxSize,
        "splitRatio": splitRatio,
        "inputGrid": voxelSlice4.slice,
        "seed": multiSeed5.seed,
      })

    // @scene-id node-1782298073824-slehw
    const gridSplitByValue7 = gridSplitByValue({
        "grid": bspRectGen6.outputGrid,
      })

    // @scene-id node-1782298073824-i7rtn
    const strToListBranches8 = strToListBranches({
        "str": districtAsset,
      })

    // @scene-id node-1782298073824-tkeb1
    const gridSceneNode9 = gridSceneNode({
        "schema": input10,
        "token": input11,
        "zRange": input12,
        "grid": gridSplitByValue7.grids,
        "name": strToListBranches8.items,
      })

    // @scene-id group_1782298073824_hg1xq
    const bspDistrictClusterTileAssetName10 = bspDistrictClusterTileAssetName({
        "input0": gridSceneNode9.scene,
        "input1": strToListBranches8.items,
      })

    // @scene-id node-1782298073824-3eptq
    const addSceneChildren11 = addSceneChildren({
        "nodes": bspDistrictClusterTileAssetName10.output0,
        "scene": scenePassthrough1.scene,
      })

    // @scene-id node-1782298073824-7vrak
    const algRegionSubtract12 = algRegionSubtract({
        "a": voxelSlice4.slice,
        "b": bspRectGen6.outputGrid,
      })

    // @scene-id node-1782298073824-2kmi6
    const textPanel13 = textPanel({
        "$params": {"text":"rest","_nodeWidth":172,"_nodeHeight":69},
      })

    // @scene-id node-1782298073824-6ldzn
    const gridSceneNode14 = gridSceneNode({
        "grid": algRegionSubtract12.region,
        "name": textPanel13.output,
      })

    // @scene-id node-1782298073824-ynr0v
    const addSceneChildren15 = addSceneChildren({
        "scene": addSceneChildren11.scene,
        "nodes": gridSceneNode14.scene,
      })

    // @scene-id node-1782298073824-xykwm
    const sceneMergeSubtrees16 = sceneMergeSubtrees({
        "scenes": addSceneChildren15.scene,
      })

    // @scene-id node-1782298073824-9l2e4
    const sceneFocusPath17 = sceneFocusPath({
        "scene": sceneMergeSubtrees16.scene,
        "path": addSceneChildren11.childPaths,
      })

    // @scene-id node-1782298073824-7hkpo
    const sceneFocusPath18 = sceneFocusPath({
        "scene": sceneMergeSubtrees16.scene,
        "path": addSceneChildren15.childPaths,
      })

    // @scene-id node-1782298073824-g36ob
    const scenePassthrough19 = scenePassthrough({
        "scene": sceneMergeSubtrees16.scene,
      })

    // @scene-id node-1782298073824-xgreg
    const scenePassthrough20 = scenePassthrough({
        "scene": sceneFocusPath17.scene,
      })

    // @scene-id node-1782298073824-o1ju5
    const scenePassthrough21 = scenePassthrough({
        "scene": sceneFocusPath18.scene,
      })

    // @scene-id node-1782298073824-4djdc
    const stringValue22 = stringValue({
        "value": addSceneChildren11.childPaths,
      })

    // @scene-id node-1782298073824-4kbf3
    const stringValue23 = stringValue({
        "value": addSceneChildren15.childPaths,
      })
    return {
      scene: scenePassthrough19.scene,
      rest: scenePassthrough21.scene,
      district: scenePassthrough20.scene,
      districtPath: stringValue22.value,
      restPath: stringValue23.value,
    }
  },
)
