// Generated by scripts/generate-native-group-definitions.mts.
// JSON parity oracle only: batteries/templates/scene/IslandRegions/IslandRegions.json
// @scene-id definition:batteries.templates.scene.island-regions.island-regions.nested.0
const islandRegionsTileAssetName = defineGroup(
  {
    id: "scene.template.island-regions.nested.0",
    version: "1.0.0",
    inputs: {
      input0: { type: Scene, runtimeType: "scene", runtimePort: "in_0", access: "item" },
      input1: { type: StringValue, runtimeType: "string", runtimePort: "in_1", access: "tree" },
    },
    outputs: {
      output0: { type: Scene, runtimeType: "scene", runtimePort: "out_0", access: "item" },
    },
  },
  ({ input0, input1 }) => {
    // @scene-id node-island-ta-name
    const textPanel1 = textPanel({
        "$params": {"text":"asset_name","_nodeWidth":180,"_nodeHeight":67},
      })

    // @scene-id node-island-ta-type
    const textPanel2 = textPanel({
        "$params": {"text":"asset_type","_nodeWidth":181,"_nodeHeight":60},
      })

    // @scene-id node-island-ta-tile
    const textPanel3 = textPanel({
        "$params": {"text":"tile","_nodeWidth":181,"_nodeHeight":60},
      })

    // @scene-id node-island-ta-str
    const stringValue4 = stringValue({
        "value": input1,
      })

    // @scene-id node-island-ta-set1
    const sceneSetAttribute5 = sceneSetAttribute({
        "scene": input0,
        "key": textPanel1.output,
        "value": stringValue4.value,
      })

    // @scene-id node-island-ta-set2
    const sceneSetAttribute6 = sceneSetAttribute({
        "scene": sceneSetAttribute5.scene,
        "key": textPanel2.output,
        "value": textPanel3.output,
      })
    return {
      output0: sceneSetAttribute6.scene,
    }
  },
)

// @scene-id definition:batteries.templates.scene.island-regions.island-regions
export const islandRegions = defineGroup(
  {
    id: "scene.template.island-regions",
    version: "1.0.0",
    inputs: {
      scene: { type: Scene, runtimeType: "scene", runtimePort: "in_0", access: "tree", order: 0, labelEn: "Scene" },
      points: { type: Point2d, runtimeType: "point2d", runtimePort: "in_1", access: "list", order: 1, labelEn: "Points" },
      islandSizes: { type: NumberList, runtimeType: "number", runtimePort: "in_2", access: "list", order: 2, labelEn: "IslandSizes" },
      islandName: { type: StringValue, runtimeType: "string", runtimePort: "in_3", access: "item", order: 3, labelEn: "IslandName" },
      islandAsset: { type: StringValue, runtimeType: "string", runtimePort: "in_4", access: "tree", order: 4, labelEn: "IslandAsset" },
      seed: { type: NumberValue, runtimeType: "number", runtimePort: "in_5", access: "item", order: 5, labelEn: "Seed" },
      input6: { type: NumberValue, runtimeType: "number", runtimePort: "in_6", access: "item", hidden: true, order: 6 },
      input7: { type: NumberValue, runtimeType: "number", runtimePort: "in_7", access: "item", hidden: true, order: 7 },
      input8: { type: NumberValue, runtimeType: "number", runtimePort: "in_8", access: "item", hidden: true, order: 8 },
      input9: { type: StringValue, runtimeType: "string", runtimePort: "in_9", access: "item", hidden: true, order: 9 },
      input10: { type: StringValue, runtimeType: "string", runtimePort: "in_10", access: "item", hidden: true, order: 10 },
      input11: { type: NumberList, runtimeType: "number", runtimePort: "in_11", access: "list", hidden: true, order: 11 },
    },
    outputs: {
      scene: { type: Scene, runtimeType: "scene", runtimePort: "out_0", access: "tree", order: 0, labelEn: "Scene" },
      island: { type: Scene, runtimeType: "scene", runtimePort: "out_1", access: "tree", order: 1, labelEn: "Island" },
      rest: { type: Scene, runtimeType: "scene", runtimePort: "out_2", access: "tree", order: 2, labelEn: "Rest" },
      islandPath: { type: StringValue, runtimeType: "string", runtimePort: "out_3", access: "tree", order: 3, labelEn: "IslandPath" },
      restPath: { type: StringValue, runtimeType: "string", runtimePort: "out_4", access: "tree", order: 4, labelEn: "RestPath" },
    },
  },
  ({ scene, points, islandSizes, islandName, islandAsset, seed, input6, input7, input8, input9, input10, input11 }) => {
    // @scene-id node-island-pass-in
    const scenePassthrough1 = scenePassthrough({
        "scene": scene,
      })

    // @scene-id node-island-explode
    const nodeExplode2 = nodeExplode({
        "scene": scenePassthrough1.scene,
      })

    // @scene-id node-island-rect
    const rectangularGrid3 = rectangularGrid({
        "fillValue": input8,
        "width": nodeExplode2.width,
        "height": nodeExplode2.height,
      })

    // @scene-id node-island-slice
    const voxelSlice4 = voxelSlice({
        "z": input7,
        "voxels": nodeExplode2.voxels,
        "grid": rectangularGrid3.grid,
      })

    // @scene-id node-island-gen
    const newIslandRegionGen5 = newIslandRegionGen({
        "points": points,
        "islandSizes": islandSizes,
        "seed": seed,
        "radiusVar": input6,
        "grid": voxelSlice4.slice,
      })

    // @scene-id node-island-g2n-main
    const gridSceneNode6 = gridSceneNode({
        "name": islandName,
        "schema": input9,
        "token": input10,
        "zRange": input11,
        "grid": newIslandRegionGen5.islandGrid,
      })

    // @scene-id group_1783100010000_taisl
    const islandRegionsTileAssetName7 = islandRegionsTileAssetName({
        "input1": islandAsset,
        "input0": gridSceneNode6.scene,
      })

    // @scene-id node-island-addchild-main
    const addSceneChildren8 = addSceneChildren({
        "nodes": islandRegionsTileAssetName7.output0,
        "scene": scenePassthrough1.scene,
      })

    // @scene-id node-island-text-rest
    const textPanel9 = textPanel({
        "$params": {"text":"rest","_nodeWidth":180,"_nodeHeight":60},
      })

    // @scene-id node-island-subtract
    const algRegionSubtract10 = algRegionSubtract({
        "a": voxelSlice4.slice,
        "b": newIslandRegionGen5.islandGrid,
      })

    // @scene-id node-island-g2n-rest
    const gridSceneNode11 = gridSceneNode({
        "grid": algRegionSubtract10.region,
        "name": textPanel9.output,
      })

    // @scene-id node-island-addchild-rest
    const addSceneChildren12 = addSceneChildren({
        "scene": addSceneChildren8.scene,
        "nodes": gridSceneNode11.scene,
      })

    // @scene-id node-island-merge
    const sceneMergeSubtrees13 = sceneMergeSubtrees({
        "scenes": addSceneChildren12.scene,
      })

    // @scene-id node-island-focus-main
    const sceneFocusPath14 = sceneFocusPath({
        "scene": sceneMergeSubtrees13.scene,
        "path": addSceneChildren8.childPaths,
      })

    // @scene-id node-island-focus-rest
    const sceneFocusPath15 = sceneFocusPath({
        "scene": sceneMergeSubtrees13.scene,
        "path": addSceneChildren12.childPaths,
      })

    // @scene-id node-island-pass-island
    const scenePassthrough16 = scenePassthrough({
        "scene": sceneFocusPath14.scene,
      })

    // @scene-id node-island-pass-rest
    const scenePassthrough17 = scenePassthrough({
        "scene": sceneFocusPath15.scene,
      })

    // @scene-id node-island-pass-scene
    const scenePassthrough18 = scenePassthrough({
        "scene": sceneMergeSubtrees13.scene,
      })

    // @scene-id node-island-type-islandpath
    const stringValue19 = stringValue({
        "value": addSceneChildren8.childPaths,
      })

    // @scene-id node-island-type-restpath
    const stringValue20 = stringValue({
        "value": addSceneChildren12.childPaths,
      })
    return {
      scene: scenePassthrough18.scene,
      island: scenePassthrough16.scene,
      rest: scenePassthrough17.scene,
      islandPath: stringValue19.value,
      restPath: stringValue20.value,
    }
  },
)
