// Generated by scripts/generate-native-group-definitions.mts.
// JSON parity oracle only: batteries/groups/scene/PickMultiBuildings/PickMultiBuildings.json
// @scene-id definition:batteries.groups.scene.pick-multi-buildings.pick-multi-buildings.nested.0
const pickMultiBuildingsGroupObjectAssetName = defineGroup(
  {
    id: "scene.group.scene.pick-multi-buildings.pick-multi-buildings.nested.0",
    version: "1.0.0",
    inputs: {
      input0: { type: Scene, runtimeType: "scene", runtimePort: "in_0", access: "item" },
      input1: { type: StringValue, runtimeType: "string", runtimePort: "in_1", access: "tree" },
    },
    outputs: {
      output0: { type: Scene, runtimeType: "scene", runtimePort: "out_0", access: "item" },
    },
  },
  ({ input0, input1 }) => {
    // @scene-id node-1781806898646-7n96y
    const textPanel1 = textPanel({
        "$params": {"text":"asset_name","_nodeWidth":180,"_nodeHeight":67},
      })

    // @scene-id node-1781806898646-8l9p3
    const textPanel2 = textPanel({
        "$params": {"text":"asset_type","_nodeWidth":181,"_nodeHeight":60},
      })

    // @scene-id node-1781806898646-lmtbw
    const textPanel3 = textPanel({
        "$params": {"text":"object","_nodeWidth":181,"_nodeHeight":60},
      })

    // @scene-id node-1781806898646-ar2sc
    const stringValue4 = stringValue({
        "value": input1,
      })

    // @scene-id node-1781806898646-52pm7
    const sceneSetAttribute5 = sceneSetAttribute({
        "scene": input0,
        "key": textPanel1.output,
        "value": stringValue4.value,
      })

    // @scene-id node-1781806898646-14d1p
    const sceneSetAttribute6 = sceneSetAttribute({
        "scene": sceneSetAttribute5.scene,
        "key": textPanel2.output,
        "value": textPanel3.output,
      })
    return {
      output0: sceneSetAttribute6.scene,
    }
  },
)

// @scene-id definition:batteries.groups.scene.pick-multi-buildings.pick-multi-buildings
export const pickMultiBuildingsGroup = defineGroup(
  {
    id: "scene.group.scene.pick-multi-buildings.pick-multi-buildings",
    version: "1.0.0",
    inputs: {
      scene: { type: Scene, runtimeType: "scene", runtimePort: "in_6", access: "tree", order: 0, labelEn: "Scene" },
      input1: { type: NumberValue, runtimeType: "number", runtimePort: "in_7", access: "item", hidden: true, order: 1 },
      input2: { type: NumberValue, runtimeType: "number", runtimePort: "in_8", access: "item", hidden: true, order: 3 },
      input3: { type: StringValue, runtimeType: "string", runtimePort: "in_9", access: "item", hidden: true, order: 4 },
      input4: { type: StringValue, runtimeType: "string", runtimePort: "in_10", access: "item", hidden: true, order: 5 },
      buildingHeights: { type: StringValue, runtimeType: "string", runtimePort: "in_2", access: "item", order: 6, labelEn: "BuildingHeights" },
      input6: { type: StringValue, runtimeType: "string", runtimePort: "in_11", access: "item", hidden: true, order: 7 },
      input7: { type: StringValue, runtimeType: "string", runtimePort: "in_12", access: "item", hidden: true, order: 8 },
      input8: { type: StringValue, runtimeType: "string", runtimePort: "in_14", access: "tree", hidden: true, order: 9 },
      buildingHeights9: { type: NumberValue, runtimeType: "number", runtimePort: "in_3", access: "tree", order: 10, labelEn: "BuildingHeights" },
      input10: { type: StringValue, runtimeType: "string", runtimePort: "in_15", access: "tree", hidden: true, order: 11 },
      input11: { type: NumberValue, runtimeType: "number", runtimePort: "in_16", access: "item", hidden: true, order: 12 },
      input12: { type: StringValue, runtimeType: "string", runtimePort: "in_17", access: "item", hidden: true, order: 13 },
      buildingAssets: { type: StringValue, runtimeType: "string", runtimePort: "in_4", access: "tree", order: 14, labelEn: "BuildingAssets" },
      input14: { type: Point2d, runtimeType: "point2d", runtimePort: "in_5", access: "list", order: 2 },
      areaWidths: { type: NumberList, runtimeType: "number", runtimePort: "in_0", access: "list", order: 15, labelEn: "AreaWidths" },
      areaHeights: { type: NumberList, runtimeType: "number", runtimePort: "in_1", access: "list", order: 16, labelEn: "AreaHeights" },
      input17: { type: NumberValue, runtimeType: "number", runtimePort: "in_13", order: 17 },
    },
    outputs: {
      buildings: { type: Scene, runtimeType: "scene", runtimePort: "out_2", access: "tree", order: 1, labelEn: "Buildings" },
      scene: { type: Scene, runtimeType: "scene", runtimePort: "out_3", access: "tree", order: 0, labelEn: "Scene" },
      rest: { type: Scene, runtimeType: "scene", runtimePort: "out_1", access: "tree", order: 3, labelEn: "Rest" },
      buildingsPaths: { type: StringValue, runtimeType: "string", runtimePort: "out_0", access: "tree", order: 2, labelEn: "BuildingsPaths" },
      restPath: { type: StringValue, runtimeType: "string", runtimePort: "out_4", access: "tree", order: 4, labelEn: "RestPath" },
    },
  },
  ({ scene, input1, input2, input3, input4, buildingHeights, input6, input7, input8, buildingHeights9, input10, input11, input12, buildingAssets, input14, areaWidths, areaHeights, input17 }) => {
    // @scene-id node-1781806898644-47ref
    const scenePassthrough1 = scenePassthrough({
        "scene": scene,
      })

    // @scene-id node-1781806898644-u6hzk
    const nodeExplode2 = nodeExplode({
        "scene": scenePassthrough1.scene,
      })

    // @scene-id node-1781806898645-weju7
    const rectangularGrid3 = rectangularGrid({
        "fillValue": input1,
        "width": nodeExplode2.width,
        "height": nodeExplode2.height,
      })

    // @scene-id node-1781806898645-888kv
    const voxelSlice4 = voxelSlice({
        "z": input2,
        "voxels": nodeExplode2.voxels,
        "grid": rectangularGrid3.grid,
      })

    // @scene-id node-1781806898645-16zbn
    const textPanel5 = textPanel({
        "$params": {"text":"rest","_nodeWidth":180,"_nodeHeight":60},
      })

    // @scene-id node-1781806898649-9um6m
    const numberValue6 = numberValue({
        "$params": {"value":1},
      })

    // @scene-id node-1781806898649-qk4em
    const basicMathOp7 = basicMathOp({
        "$params": {"op":"+"},
        "op": input8,
        "b": numberValue6.value,
        "a": voxelSlice4.z,
      })

    // @scene-id node-1781806898649-nl8qf
    const typeNumber8 = typeNumber({
        "value": buildingHeights9,
      })

    // @scene-id node-1781806898650-t304k
    const basicMathOp9 = basicMathOp({
        "$params": {"op":"+"},
        "op": input10,
        "b": typeNumber8.value,
        "a": voxelSlice4.z,
      })

    // @scene-id node-1781806898651-7ol6l
    const rangeList10 = rangeList({
        "step": input11,
        "prefix": input12,
        "start": basicMathOp7.result,
        "end": basicMathOp9.result,
      })

    // @scene-id node-1781809174652
    const algPoints2rects11 = algPoints2rects({
        "points": input14,
        "widths": areaWidths,
        "heights": areaHeights,
        "region": voxelSlice4.slice,
      })

    // @scene-id node-1781806898646-eusbb
    const algRegionBlockyCarve12 = algRegionBlockyCarve({
        "seed": input17,
        "region": algPoints2rects11.rects,
      })

    // @scene-id node-1781806898646-4zzf0
    const gridSceneNode13 = gridSceneNode({
        "name": buildingHeights,
        "schema": input6,
        "token": input7,
        "grid": algRegionBlockyCarve12.region,
        "zRange": rangeList10.list,
      })

    // @scene-id group_1781806898646_kf1og
    const pickMultiBuildingsGroupObjectAssetName14 = pickMultiBuildingsGroupObjectAssetName({
        "$params": {"__groupIsTemplate":false},
        "input1": buildingAssets,
        "input0": gridSceneNode13.scene,
      })

    // @scene-id node-1781806898647-61f53
    const addSceneChildren15 = addSceneChildren({
        "scene": scenePassthrough1.scene,
        "nodes": pickMultiBuildingsGroupObjectAssetName14.output0,
      })

    // @scene-id node-1781806898649-p9vbj
    const stringValue16 = stringValue({
        "value": addSceneChildren15.childPaths,
      })

    // @scene-id node-1781809379750
    const algRegionUnionAll17 = algRegionUnionAll({
        "regions": algRegionBlockyCarve12.region,
      })

    // @scene-id node-1781806898645-3q9ez
    const algRegionSubtract18 = algRegionSubtract({
        "a": voxelSlice4.slice,
        "b": algRegionUnionAll17.region,
      })

    // @scene-id node-1781839657843
    const voxelRange19 = voxelRange({
        "voxels": nodeExplode2.voxels,
      })

    // @scene-id node-1781806898645-brqxn
    const gridSceneNode20 = gridSceneNode({
        "schema": input3,
        "token": input4,
        "grid": algRegionSubtract18.region,
        "name": textPanel5.output,
        "zRange": voxelRange19.zRange,
      })

    // @scene-id node-1781806898648-p84qk
    const addSceneChildren21 = addSceneChildren({
        "scene": addSceneChildren15.scene,
        "nodes": gridSceneNode20.scene,
      })

    // @scene-id node-1781806898647-86kxu
    const sceneMergeSubtrees22 = sceneMergeSubtrees({
        "scenes": addSceneChildren21.scene,
      })

    // @scene-id node-1781806898647-63q9u
    const sceneFocusPath23 = sceneFocusPath({
        "scene": sceneMergeSubtrees22.scene,
        "path": addSceneChildren15.childPaths,
      })

    // @scene-id node-1781806898648-tn4we
    const scenePassthrough24 = scenePassthrough({
        "scene": sceneFocusPath23.scene,
      })

    // @scene-id node-1781806898648-w2dph
    const scenePassthrough25 = scenePassthrough({
        "scene": sceneMergeSubtrees22.scene,
      })

    // @scene-id node-1781806898648-eiy7b
    const sceneFocusPath26 = sceneFocusPath({
        "path": addSceneChildren21.childPaths,
        "scene": sceneMergeSubtrees22.scene,
      })

    // @scene-id node-1781806898648-d9nlj
    const scenePassthrough27 = scenePassthrough({
        "scene": sceneFocusPath26.scene,
      })

    // @scene-id node-1781806898649-qsd00
    const stringValue28 = stringValue({
        "value": addSceneChildren21.childPaths,
      })
    return {
      buildings: scenePassthrough24.scene,
      scene: scenePassthrough25.scene,
      rest: scenePassthrough27.scene,
      buildingsPaths: stringValue16.value,
      restPath: stringValue28.value,
    }
  },
)
