// Generated by scripts/generate-native-group-definitions.mts.
// JSON parity oracle only: batteries/groups/structures/topographic/MountainContourGenerate/MountainContourGenerate.json
// @scene-id definition:batteries.groups.structures.topographic.mountain-contour-generate.mountain-contour-generate.nested.0
const mountainContourGenerateGroupMultiNames = defineGroup(
  {
    id: "scene.group.structures.topographic.mountain-contour-generate.mountain-contour-generate.nested.0",
    version: "1.0.0",
    inputs: {
      input0: { type: StringValue, runtimeType: "string", runtimePort: "in_0", access: "tree", hidden: true },
      count: { type: NumberValue, runtimeType: "number", runtimePort: "in_1", access: "tree", labelEn: "Count" },
      input2: { type: NumberValue, runtimeType: "number", runtimePort: "in_2", access: "item", hidden: true },
      prefix: { type: StringValue, runtimeType: "string", runtimePort: "in_3", access: "tree", labelEn: "Prefix" },
    },
    outputs: {
      layerIndices: { type: NumberList, runtimeType: "number", runtimePort: "out_0", access: "list", hidden: false, order: 0, labelEn: "LayerIndices" },
      names: { type: StringList, runtimeType: "string", runtimePort: "out_1", access: "list", labelEn: "Names" },
      output2: { type: NumberValue, runtimeType: "number", runtimePort: "out_2", access: "item" },
    },
  },
  ({ input0, count, input2, prefix }) => {
    // @scene-id node-1781196357312-kpdc6
    const numberValue1 = numberValue({
        "$params": {"value":0},
      })

    // @scene-id node-1781196357313-zx4q3
    const numberValue2 = numberValue({
        "$params": {"value":1},
      })

    // @scene-id node-1781196357313-ytu1s
    const typeNumber3 = typeNumber({
        "value": count,
      })

    // @scene-id node-1781196357313-uv479
    const basicMathOp4 = basicMathOp({
        "$params": {"op":"-"},
        "op": input0,
        "b": numberValue2.value,
        "a": typeNumber3.value,
      })

    // @scene-id node-1781196357313-p3rbt
    const stringValue5 = stringValue({
        "value": prefix,
      })

    // @scene-id node-1781196357313-c34js
    const rangeList6 = rangeList({
        "step": input2,
        "start": numberValue1.value,
        "end": basicMathOp4.result,
        "prefix": stringValue5.value,
      })
    return {
      layerIndices: rangeList6.list,
      names: rangeList6.stringList,
      output2: rangeList6.count,
    }
  },
)

// @scene-id definition:batteries.groups.structures.topographic.mountain-contour-generate.mountain-contour-generate.nested.1
const mountainContourGenerateGroupTileAssetName = defineGroup(
  {
    id: "scene.group.structures.topographic.mountain-contour-generate.mountain-contour-generate.nested.1",
    version: "1.0.0",
    inputs: {
      input0: { type: Scene, runtimeType: "scene", runtimePort: "in_0", access: "item" },
      input1: { type: StringValue, runtimeType: "string", runtimePort: "in_1", access: "tree" },
    },
    outputs: {
      output0: { type: Scene, runtimeType: "scene", runtimePort: "out_0", access: "item" },
    },
  },
  ({ input0, input1 }) => {
    // @scene-id node-1781196424173-48nka
    const textPanel1 = textPanel({
        "$params": {"text":"asset_name","_nodeWidth":180,"_nodeHeight":67},
      })

    // @scene-id node-1781196424173-s5urz
    const textPanel2 = textPanel({
        "$params": {"text":"asset_type","_nodeWidth":181,"_nodeHeight":60},
      })

    // @scene-id node-1781196424173-v6d58
    const textPanel3 = textPanel({
        "$params": {"text":"tile","_nodeWidth":181,"_nodeHeight":60},
      })

    // @scene-id node-1781196424173-zxpwk
    const stringValue4 = stringValue({
        "value": input1,
      })

    // @scene-id node-1781196424173-a61li
    const sceneSetAttribute5 = sceneSetAttribute({
        "scene": input0,
        "key": textPanel1.output,
        "value": stringValue4.value,
      })

    // @scene-id node-1781196424173-qh0dn
    const sceneSetAttribute6 = sceneSetAttribute({
        "scene": sceneSetAttribute5.scene,
        "key": textPanel2.output,
        "value": textPanel3.output,
      })
    return {
      output0: sceneSetAttribute6.scene,
    }
  },
)

// @scene-id definition:batteries.groups.structures.topographic.mountain-contour-generate.mountain-contour-generate
export const mountainContourGenerateGroup = defineGroup(
  {
    id: "scene.group.structures.topographic.mountain-contour-generate.mountain-contour-generate",
    version: "1.0.0",
    inputs: {
      scene: { type: Scene, runtimeType: "scene", runtimePort: "in_0", access: "tree", labelEn: "Scene" },
      assetName: { type: StringValue, runtimeType: "string", runtimePort: "in_1", labelEn: "AssetName" },
      seed: { type: NumberValue, runtimeType: "number", runtimePort: "in_2", access: "tree", labelEn: "Seed" },
      maxElevationLayers: { type: NumberValue, runtimeType: "number", runtimePort: "in_3", access: "item", labelEn: "MaxElevationLayers" },
      peakCount: { type: NumberValue, runtimeType: "number", runtimePort: "in_4", access: "item", labelEn: "PeakCount" },
      peakRadius: { type: NumberValue, runtimeType: "number", runtimePort: "in_5", access: "item", labelEn: "PeakRadius" },
      peakStrength: { type: NumberValue, runtimeType: "number", runtimePort: "in_6", access: "item", labelEn: "PeakStrength" },
      noiseScale: { type: NumberValue, runtimeType: "number", runtimePort: "in_7", access: "item", labelEn: "NoiseScale" },
      warpStrength: { type: NumberValue, runtimeType: "number", runtimePort: "in_8", access: "item", labelEn: "WarpStrength" },
      namePrefix: { type: StringValue, runtimeType: "string", runtimePort: "in_9", labelEn: "NamePrefix" },
    },
    outputs: {
      scene: { type: Scene, runtimeType: "scene", runtimePort: "out_0", access: "tree", order: 0, labelEn: "Scene" },
      mountain: { type: Scene, runtimeType: "scene", runtimePort: "out_2", access: "tree", order: 1, labelEn: "Mountain" },
      rest: { type: Scene, runtimeType: "scene", runtimePort: "out_1", access: "tree", order: 2, labelEn: "Rest" },
      mountainPath: { type: StringValue, runtimeType: "string", runtimePort: "out_3", access: "tree", order: 2, labelEn: "MountainPath" },
      restPath: { type: StringValue, runtimeType: "string", runtimePort: "out_4", access: "tree", order: 4, labelEn: "RestPath" },
    },
  },
  ({ scene, assetName, seed, maxElevationLayers, peakCount, peakRadius, peakStrength, noiseScale, warpStrength, namePrefix }) => {
    // @scene-id node-1781195086749-tmrnd
    const scenePassthrough1 = scenePassthrough({
        "scene": scene,
      })

    // @scene-id node-1781195086751-18hzj
    const nodeExplode2 = nodeExplode({
        "scene": scenePassthrough1.scene,
      })

    // @scene-id node-1781195086752-rl289
    const rectangularGrid3 = rectangularGrid({
        "width": nodeExplode2.width,
        "height": nodeExplode2.height,
      })

    // @scene-id node-1781195086753-lprq9
    const voxelSlice4 = voxelSlice({
        "voxels": nodeExplode2.voxels,
        "grid": rectangularGrid3.grid,
      })

    // @scene-id node-1781196534058-ork8p
    const textPanel5 = textPanel({
        "$params": {"text":"rest","_nodeWidth":172,"_nodeHeight":69},
      })

    // @scene-id node-1781238323504
    const multiSeed6 = multiSeed({
        "seed": seed,
        "shape": voxelSlice4.slice,
      })

    // @scene-id mc_field
    const algFieldMountainContour7 = algFieldMountainContour({
        "peakCount": peakCount,
        "peakRadius": peakRadius,
        "peakStrength": peakStrength,
        "noiseScale": noiseScale,
        "warpStrength": warpStrength,
        "region": voxelSlice4.slice,
        "seed": multiSeed6.seed,
      })

    // @scene-id mc_prefix
    const stringValue8 = stringValue({
        "$params": {"value":"Contour"},
        "value": namePrefix,
      })

    // @scene-id mc_quantize
    const algPartitionFieldQuantize9 = algPartitionFieldQuantize({
        "maxElevationLayers": maxElevationLayers,
        "field": algFieldMountainContour7.field,
        "region": voxelSlice4.slice,
        "namePrefix": stringValue8.value,
      })

    // @scene-id group_1781196357312_1adif
    const mountainContourGenerateGroupMultiNames10 = mountainContourGenerateGroupMultiNames({
        "count": algPartitionFieldQuantize9.count,
        "prefix": stringValue8.value,
      })

    // @scene-id node-1781196357317-p09mn
    const gridSceneNode11 = gridSceneNode({
        "name": mountainContourGenerateGroupMultiNames10.names,
        "grid": algPartitionFieldQuantize9.partition,
        "z": mountainContourGenerateGroupMultiNames10.layerIndices,
      })

    // @scene-id group_1781196424173_7w8rd
    const mountainContourGenerateGroupTileAssetName12 = mountainContourGenerateGroupTileAssetName({
        "input1": assetName,
        "input0": gridSceneNode11.scene,
      })

    // @scene-id node-1781196524935-1n9ci
    const addSceneChildren13 = addSceneChildren({
        "nodes": mountainContourGenerateGroupTileAssetName12.output0,
        "scene": scenePassthrough1.scene,
      })

    // @scene-id node-1781196557844
    const algRegionUnionAll14 = algRegionUnionAll({
        "regions": algPartitionFieldQuantize9.partition,
      })

    // @scene-id node-1781196534055-ydsjh
    const algRegionSubtract15 = algRegionSubtract({
        "a": [voxelSlice4.slice, voxelSlice4.slice],
        "b": [algRegionUnionAll14.region, algRegionUnionAll14.region],
      })

    // @scene-id node-1781196534057-5e8c1
    const gridSceneNode16 = gridSceneNode({
        "name": textPanel5.output,
        "grid": algRegionSubtract15.region,
      })

    // @scene-id node-1781196524938-x6l38
    const addSceneChildren17 = addSceneChildren({
        "scene": addSceneChildren13.scene,
        "nodes": gridSceneNode16.scene,
      })

    // @scene-id node-1781196524936-fwqpu
    const sceneMergeSubtrees18 = sceneMergeSubtrees({
        "scenes": addSceneChildren17.scene,
      })

    // @scene-id node-1781196524937-pz7vk
    const sceneFocusPath19 = sceneFocusPath({
        "path": addSceneChildren13.childPaths,
        "scene": sceneMergeSubtrees18.scene,
      })

    // @scene-id node-1781196524938-1gejd
    const scenePassthrough20 = scenePassthrough({
        "scene": sceneMergeSubtrees18.scene,
      })

    // @scene-id node-1781196524939-ha9qx
    const sceneFocusPath21 = sceneFocusPath({
        "path": addSceneChildren17.childPaths,
        "scene": sceneMergeSubtrees18.scene,
      })

    // @scene-id node-1781196524940-5z8b3
    const scenePassthrough22 = scenePassthrough({
        "scene": sceneFocusPath19.scene,
      })

    // @scene-id node-1781196524940-y8gid
    const scenePassthrough23 = scenePassthrough({
        "scene": sceneFocusPath21.scene,
      })

    // @scene-id node-1781238278026
    const stringValue24 = stringValue({
        "value": addSceneChildren13.childPaths,
      })

    // @scene-id node-1781238286100-4naph
    const stringValue25 = stringValue({
        "value": addSceneChildren17.childPaths,
      })
    return {
      scene: scenePassthrough20.scene,
      mountain: scenePassthrough22.scene,
      rest: scenePassthrough23.scene,
      mountainPath: stringValue24.value,
      restPath: stringValue25.value,
    }
  },
)
