// Generated by scripts/generate-native-group-definitions.mts.
// JSON parity oracle only: batteries/groups/scene/AddBaseGrid/AddBaseGrid.json
// @scene-id definition:batteries.groups.scene.add-base-grid.add-base-grid.nested.0
const addBaseGridGroupTileAssetName = defineGroup(
  {
    id: "scene.group.scene.add-base-grid.add-base-grid.nested.0",
    version: "1.0.0",
    inputs: {
      input0: { type: Scene, runtimeType: "scene", runtimePort: "in_0", access: "item" },
      input1: { type: StringValue, runtimeType: "string", runtimePort: "in_1", access: "tree" },
    },
    outputs: {
      output0: { type: Scene, runtimeType: "scene", runtimePort: "out_0", access: "item" },
    },
  },
  ({ input0, input1 }) => {
    // @scene-id node-1781802325174-mtj8o
    const textPanel1 = textPanel({
        "$params": {"text":"asset_name","_nodeWidth":180,"_nodeHeight":67},
      })

    // @scene-id node-1781802325174-u327m
    const textPanel2 = textPanel({
        "$params": {"text":"asset_type","_nodeWidth":181,"_nodeHeight":60},
      })

    // @scene-id node-1781802325174-wwdmk
    const textPanel3 = textPanel({
        "$params": {"text":"tile","_nodeWidth":181,"_nodeHeight":60},
      })

    // @scene-id node-1781802325174-b650w
    const stringValue4 = stringValue({
        "value": input1,
      })

    // @scene-id node-1781802325174-byry8
    const sceneSetAttribute5 = sceneSetAttribute({
        "scene": input0,
        "key": textPanel1.output,
        "value": stringValue4.value,
      })

    // @scene-id node-1781802325174-zujoh
    const sceneSetAttribute6 = sceneSetAttribute({
        "scene": sceneSetAttribute5.scene,
        "key": textPanel2.output,
        "value": textPanel3.output,
      })
    return {
      output0: sceneSetAttribute6.scene,
    }
  },
)

// @scene-id definition:batteries.groups.scene.add-base-grid.add-base-grid
export const addBaseGridGroup = defineGroup(
  {
    id: "scene.group.scene.add-base-grid.add-base-grid",
    version: "1.0.0",
    inputs: {
      baseName: { type: StringValue, runtimeType: "string", runtimePort: "in_1", access: "item", order: 1, labelEn: "BaseName" },
      input1: { type: StringValue, runtimeType: "string", runtimePort: "in_5", access: "item", hidden: true, order: 2 },
      input2: { type: StringValue, runtimeType: "string", runtimePort: "in_6", access: "item", hidden: true, order: 3 },
      input3: { type: NumberList, runtimeType: "number", runtimePort: "in_7", access: "list", hidden: true, order: 4 },
      width: { type: NumberValue, runtimeType: "number", runtimePort: "in_2", access: "item", order: 5, labelEn: "Width" },
      height: { type: NumberValue, runtimeType: "number", runtimePort: "in_3", access: "item", order: 6, labelEn: "Height" },
      input6: { type: NumberValue, runtimeType: "number", runtimePort: "in_8", access: "item", hidden: true, order: 7 },
      rootScene: { type: Scene, runtimeType: "scene", runtimePort: "in_0", access: "item", order: 0, labelEn: "RootScene" },
      baseAsset: { type: StringValue, runtimeType: "string", runtimePort: "in_4", access: "tree", order: 8, labelEn: "BaseAsset" },
    },
    outputs: {
      baseNode: { type: Scene, runtimeType: "scene", runtimePort: "out_1", access: "item", order: 1, labelEn: "BaseNode" },
      rootScene: { type: Scene, runtimeType: "scene", runtimePort: "out_2", access: "tree", order: 0, labelEn: "RootScene" },
      baseNodePath: { type: StringValue, runtimeType: "string", runtimePort: "out_3", access: "tree", order: 2, labelEn: "BaseNodePath" },
      output3: { type: Scene, runtimeType: "scene", runtimePort: "out_0", access: "item", hidden: true, order: 3 },
    },
  },
  ({ baseName, input1, input2, input3, width, height, input6, rootScene, baseAsset }) => {
    // @scene-id node-1781802325174-67n8m
    const rectangularGrid1 = rectangularGrid({
        "width": width,
        "height": height,
        "fillValue": input6,
      })

    // @scene-id node-1781802325174-i51nt
    const gridSceneNode2 = gridSceneNode({
        "name": baseName,
        "schema": input1,
        "token": input2,
        "zRange": input3,
        "grid": rectangularGrid1.grid,
      })

    // @scene-id group_1781802325174_p4hvv
    const addBaseGridGroupTileAssetName3 = addBaseGridGroupTileAssetName({
        "input1": baseAsset,
        "input0": gridSceneNode2.scene,
      })

    // @scene-id node-1781802325174-nksca
    const addSceneChildren4 = addSceneChildren({
        "scene": rootScene,
        "nodes": addBaseGridGroupTileAssetName3.output0,
      })

    // @scene-id node-1781802325174-eez9r
    const sceneFocusPath5 = sceneFocusPath({
        "path": addSceneChildren4.childPaths,
        "scene": addSceneChildren4.scene,
      })

    // @scene-id node-1781802325174-se1qy
    const scenePassthrough6 = scenePassthrough({
        "scene": addSceneChildren4.scene,
      })

    // @scene-id node-1781802325174-lh2th
    const stringValue7 = stringValue({
        "value": addSceneChildren4.childPaths,
      })
    return {
      baseNode: sceneFocusPath5.scene,
      rootScene: scenePassthrough6.scene,
      baseNodePath: stringValue7.value,
      output3: gridSceneNode2.scene,
    }
  },
)
