// Generated by scripts/generate-native-group-definitions.mts.
// JSON parity oracle only: batteries/groups/scene/ObjectAssetName/ObjectAssetName.json
// @scene-id definition:batteries.groups.scene.object-asset-name.object-asset-name
export const objectAssetName = defineGroup(
  {
    id: "scene.group.scene.object-asset-name.object-asset-name",
    version: "1.0.0",
    inputs: {
      input0: { type: Scene, runtimeType: "scene", runtimePort: "in_0", access: "item" },
      input1: { type: StringValue, runtimeType: "string", runtimePort: "in_1", access: "tree" },
    },
    outputs: {
      output0: { type: Scene, runtimeType: "scene", runtimePort: "out_0", access: "item" },
    },
  },
  ({ input0, input1 }) => {
    // @scene-id node-1781226693286-9nzec
    const textPanel1 = textPanel({
        "$params": {"text":"asset_name","_nodeWidth":180,"_nodeHeight":67},
      })

    // @scene-id node-1781226693286-e9ls0
    const textPanel2 = textPanel({
        "$params": {"text":"asset_type","_nodeWidth":181,"_nodeHeight":60},
      })

    // @scene-id node-1781226693286-wf693
    const textPanel3 = textPanel({
        "$params": {"text":"object","_nodeWidth":181,"_nodeHeight":60},
      })

    // @scene-id node-1781226693286-c385q
    const stringValue4 = stringValue({
        "value": input1,
      })

    // @scene-id node-1781226693286-nilqf
    const sceneSetAttribute5 = sceneSetAttribute({
        "scene": input0,
        "key": textPanel1.output,
        "value": stringValue4.value,
      })

    // @scene-id node-1781226693286-8nhaz
    const sceneSetAttribute6 = sceneSetAttribute({
        "scene": sceneSetAttribute5.scene,
        "key": textPanel2.output,
        "value": textPanel3.output,
      })
    return {
      output0: sceneSetAttribute6.scene,
    }
  },
)
