// Generated by scripts/generate-native-group-definitions.mts.
// JSON parity oracle only: batteries/templates/structures/decorations/NaturalDecorationDistribution/NaturalDecorationDistribution.json
// @scene-id definition:batteries.templates.structures.decorations.natural-decoration-distribution.natural-decoration-distribution.nested.0
const naturalDecorationDistributionMultiNames = defineGroup(
  {
    id: "scene.template.natural-decoration-distribution.nested.0",
    version: "1.0.0",
    inputs: {
      input0: { type: StringValue, runtimeType: "string", runtimePort: "in_0", access: "tree", hidden: true },
      count: { type: NumberValue, runtimeType: "number", runtimePort: "in_1", access: "tree", labelEn: "Count" },
      input2: { type: NumberValue, runtimeType: "number", runtimePort: "in_2", access: "item", hidden: true },
      prefix: { type: StringValue, runtimeType: "string", runtimePort: "in_3", access: "tree", labelEn: "Prefix" },
    },
    outputs: {
      output0: { type: NumberList, runtimeType: "number", runtimePort: "out_0", access: "list", hidden: true },
      names: { type: StringList, runtimeType: "string", runtimePort: "out_1", access: "list", labelEn: "Names" },
      output2: { type: NumberValue, runtimeType: "number", runtimePort: "out_2", access: "item" },
    },
  },
  ({ input0, count, input2, prefix }) => {
    // @scene-id node-1781858738320-yvvif
    const numberValue1 = numberValue({})

    // @scene-id node-1781858738320-g8h3c
    const numberValue2 = numberValue({
        "$params": {"value":1},
      })

    // @scene-id node-1781858738320-xcdeo
    const typeNumber3 = typeNumber({
        "value": count,
      })

    // @scene-id node-1781858738320-856y0
    const basicMathOp4 = basicMathOp({
        "$params": {"op":"-"},
        "op": input0,
        "b": numberValue2.value,
        "a": typeNumber3.value,
      })

    // @scene-id node-1781858738320-7e74g
    const stringValue5 = stringValue({
        "value": prefix,
      })

    // @scene-id node-1781858738320-wq05v
    const rangeList6 = rangeList({
        "step": input2,
        "start": numberValue1.value,
        "end": basicMathOp4.result,
        "prefix": stringValue5.value,
      })
    return {
      output0: rangeList6.list,
      names: rangeList6.stringList,
      output2: rangeList6.count,
    }
  },
)

// @scene-id definition:batteries.templates.structures.decorations.natural-decoration-distribution.natural-decoration-distribution.nested.1
const naturalDecorationDistributionObjectAssetName = defineGroup(
  {
    id: "scene.template.natural-decoration-distribution.nested.1",
    version: "1.0.0",
    inputs: {
      input0: { type: Scene, runtimeType: "scene", runtimePort: "in_0", access: "item" },
      input1: { type: StringValue, runtimeType: "string", runtimePort: "in_1", access: "tree" },
    },
    outputs: {
      output0: { type: Scene, runtimeType: "scene", runtimePort: "out_0", access: "item" },
    },
  },
  ({ input0, input1 }) => {
    // @scene-id node-1781858738320-lhmix
    const textPanel1 = textPanel({
        "$params": {"text":"asset_name","_nodeWidth":180,"_nodeHeight":67},
      })

    // @scene-id node-1781858738320-r4n47
    const textPanel2 = textPanel({
        "$params": {"text":"asset_type","_nodeWidth":181,"_nodeHeight":60},
      })

    // @scene-id node-1781858738320-rwp0d
    const textPanel3 = textPanel({
        "$params": {"text":"object","_nodeWidth":181,"_nodeHeight":60},
      })

    // @scene-id node-1781858738320-a68n0
    const stringValue4 = stringValue({
        "value": input1,
      })

    // @scene-id node-1781858738320-yvrcz
    const sceneSetAttribute5 = sceneSetAttribute({
        "scene": input0,
        "key": textPanel1.output,
        "value": stringValue4.value,
      })

    // @scene-id node-1781858738320-ljp4f
    const sceneSetAttribute6 = sceneSetAttribute({
        "scene": sceneSetAttribute5.scene,
        "key": textPanel2.output,
        "value": textPanel3.output,
      })
    return {
      output0: sceneSetAttribute6.scene,
    }
  },
)

// @scene-id definition:batteries.templates.structures.decorations.natural-decoration-distribution.natural-decoration-distribution
export const naturalDecorationDistribution = defineGroup(
  {
    id: "scene.template.natural-decoration-distribution",
    version: "1.0.0",
    inputs: {
      scene: { type: Scene, runtimeType: "scene", runtimePort: "in_1", access: "tree", labelEn: "Scene" },
      input1: { type: NumberValue, runtimeType: "number", runtimePort: "in_6", access: "item", hidden: true },
      input2: { type: NumberValue, runtimeType: "number", runtimePort: "in_7", access: "item", hidden: true },
      input3: { type: StringValue, runtimeType: "string", runtimePort: "in_8", access: "item", hidden: true },
      input4: { type: StringValue, runtimeType: "string", runtimePort: "in_9", access: "item", hidden: true },
      input5: { type: StringValue, runtimeType: "string", runtimePort: "in_10", access: "item", hidden: true },
      input6: { type: StringValue, runtimeType: "string", runtimePort: "in_11", access: "item", hidden: true },
      namePrefix: { type: StringValue, runtimeType: "string", runtimePort: "in_0", access: "tree", labelEn: "NamePrefix" },
      input8: { type: Grid, runtimeType: "grid", runtimePort: "in_12", access: "item", hidden: true },
      input9: { type: StringValue, runtimeType: "string", runtimePort: "in_13", hidden: true },
      density: { type: NumberValue, runtimeType: "number", runtimePort: "in_2", labelEn: "Density" },
      input11: { type: NumberValue, runtimeType: "number", runtimePort: "in_14", hidden: true },
      assetName: { type: StringValue, runtimeType: "string", runtimePort: "in_5", access: "tree", labelEn: "AssetName" },
      input13: { type: NumberValue, runtimeType: "number", runtimePort: "in_15", access: "item", hidden: true },
      input14: { type: StringValue, runtimeType: "string", runtimePort: "in_16", access: "item", hidden: true },
      input15: { type: StringValue, runtimeType: "string", runtimePort: "in_17", access: "tree", hidden: true },
      zHeight: { type: NumberValue, runtimeType: "number", runtimePort: "in_4", access: "item", labelEn: "zHeight" },
      input17: { type: StringValue, runtimeType: "string", runtimePort: "in_18", access: "tree", hidden: true },
      seed: { type: NumberValue, runtimeType: "number", runtimePort: "in_3", access: "tree", labelEn: "Seed" },
    },
    outputs: {
      scene: { type: Scene, runtimeType: "scene", runtimePort: "out_0", access: "tree", order: 0, labelEn: "Scene" },
      decoration: { type: Scene, runtimeType: "scene", runtimePort: "out_1", access: "tree", order: 1, labelEn: "Decoration" },
      rest: { type: Scene, runtimeType: "scene", runtimePort: "out_2", access: "tree", order: 3, labelEn: "Rest" },
      output3: { type: NumberValue, runtimeType: "number", runtimePort: "out_3", access: "item", hidden: true, order: 4 },
      decorationPath: { type: StringValue, runtimeType: "string", runtimePort: "out_4", access: "tree", order: 2, labelEn: "DecorationPath" },
      restPath: { type: StringValue, runtimeType: "string", runtimePort: "out_5", access: "tree", order: 5, labelEn: "RestPath" },
    },
  },
  ({ scene, input1, input2, input3, input4, input5, input6, namePrefix, input8, input9, density, input11, assetName, input13, input14, input15, zHeight, input17, seed }) => {
    // @scene-id node-1781858738320-bux7c
    const numberValue1 = numberValue({
        "$params": {"value":0.5,"min":0,"max":100,"precision":2},
      })

    // @scene-id node-1781858738320-zohzz
    const scenePassthrough2 = scenePassthrough({
        "scene": scene,
      })

    // @scene-id node-1781858738320-700u8
    const nodeExplode3 = nodeExplode({
        "scene": scenePassthrough2.scene,
      })

    // @scene-id node-1781858738320-pqan3
    const rectangularGrid4 = rectangularGrid({
        "fillValue": input1,
        "height": nodeExplode3.height,
        "width": nodeExplode3.width,
      })

    // @scene-id node-1781858738320-afbxs
    const voxelSlice5 = voxelSlice({
        "z": input2,
        "voxels": nodeExplode3.voxels,
        "grid": rectangularGrid4.grid,
      })

    // @scene-id node-1781858738320-pyalj
    const textPanel6 = textPanel({
        "$params": {"text":"rest","_nodeWidth":172,"_nodeHeight":69},
      })

    // @scene-id node-1781858738320-48fpl
    const numberValue7 = numberValue({
        "$params": {"value":1,"min":0,"max":10,"precision":0},
      })

    // @scene-id node-1781858738320-qxplc
    const numberValue8 = numberValue({
        "$params": {"value":1,"min":0,"max":10,"precision":0},
      })

    // @scene-id node-1781858738320-tkxlv
    const multiSeed9 = multiSeed({
        "seed": seed,
        "shape": voxelSlice5.slice,
      })

    // @scene-id node-1781858738320-mu118
    const algRegionRandomFill10 = algRegionRandomFill({
        "edge": input8,
        "mode": input9,
        "density": density,
        "count": input11,
        "region": voxelSlice5.slice,
        "seed": multiSeed9.seed,
      })

    // @scene-id node-1781858738320-xdge2
    const algField2points11 = algField2points({
        "threshold": numberValue1.value,
        "field": algRegionRandomFill10.region,
      })

    // @scene-id node-1781858738320-37e02
    const algRegionUnionAll12 = algRegionUnionAll({
        "regions": algField2points11.points,
      })

    // @scene-id node-1781858738320-jzbwd
    const algRegionSubtract13 = algRegionSubtract({
        "a": voxelSlice5.slice,
        "b": algRegionUnionAll12.region,
      })

    // @scene-id group_1781858738320_hqi4y
    const naturalDecorationDistributionMultiNames14 = naturalDecorationDistributionMultiNames({
        "prefix": namePrefix,
        "count": algField2points11.count,
      })

    // @scene-id node-1782115602603
    const basicMathOp15 = basicMathOp({
        "op": input15,
        "a": voxelSlice5.z,
        "b": numberValue7.value,
      })

    // @scene-id node-1782115684352-5js94
    const basicMathOp16 = basicMathOp({
        "b": zHeight,
        "op": input17,
        "a": voxelSlice5.z,
      })

    // @scene-id node-1781858738320-5jqbg
    const rangeList17 = rangeList({
        "step": input13,
        "prefix": input14,
        "start": basicMathOp15.result,
        "end": basicMathOp16.result,
      })

    // @scene-id node-1781858738320-z22j0
    const gridSceneNode18 = gridSceneNode({
        "schema": input3,
        "token": input4,
        "name": naturalDecorationDistributionMultiNames14.names,
        "grid": algField2points11.points,
        "zRange": rangeList17.list,
      })

    // @scene-id group_1781858738320_akwyt
    const naturalDecorationDistributionObjectAssetName19 = naturalDecorationDistributionObjectAssetName({
        "input1": assetName,
        "input0": gridSceneNode18.scene,
      })

    // @scene-id node-1781858738320-8zgfb
    const addSceneChildren20 = addSceneChildren({
        "scene": scenePassthrough2.scene,
        "nodes": naturalDecorationDistributionObjectAssetName19.output0,
      })

    // @scene-id node-1781858738320-3qolb
    const stringValue21 = stringValue({
        "value": addSceneChildren20.childPaths,
      })

    // @scene-id node-1782116136996
    const voxelRange22 = voxelRange({
        "voxels": nodeExplode3.voxels,
      })

    // @scene-id node-1781858738320-ld1ji
    const gridSceneNode23 = gridSceneNode({
        "schema": input5,
        "token": input6,
        "name": textPanel6.output,
        "grid": algRegionSubtract13.region,
        "zRange": voxelRange22.zRange,
      })

    // @scene-id node-1781858738320-s02ik
    const addSceneChildren24 = addSceneChildren({
        "scene": addSceneChildren20.scene,
        "nodes": gridSceneNode23.scene,
      })

    // @scene-id node-1781858738320-rrl6m
    const sceneMergeSubtrees25 = sceneMergeSubtrees({
        "scenes": addSceneChildren24.scene,
      })

    // @scene-id node-1781858738320-2pz49
    const scenePassthrough26 = scenePassthrough({
        "scene": sceneMergeSubtrees25.scene,
      })

    // @scene-id node-1781858738320-gq0uq
    const sceneFocusPath27 = sceneFocusPath({
        "scene": sceneMergeSubtrees25.scene,
        "path": addSceneChildren24.childPaths,
      })

    // @scene-id node-1781858738320-9fbqi
    const scenePassthrough28 = scenePassthrough({
        "scene": sceneMergeSubtrees25.scene,
      })

    // @scene-id node-1781858738320-d5gd5
    const scenePassthrough29 = scenePassthrough({
        "scene": sceneFocusPath27.scene,
      })

    // @scene-id node-1781858738320-1zauf
    const stringValue30 = stringValue({
        "value": addSceneChildren24.childPaths,
      })
    return {
      scene: scenePassthrough26.scene,
      decoration: scenePassthrough28.scene,
      rest: scenePassthrough29.scene,
      output3: numberValue8.value,
      decorationPath: stringValue21.value,
      restPath: stringValue30.value,
    }
  },
)
