// Generated by scripts/generate-native-group-definitions.mts.
// JSON parity oracle only: batteries/templates/structures/topographic/HillContourGenerate/HillContourGenerate.json
// @scene-id definition:batteries.templates.structures.topographic.hill-contour-generate.hill-contour-generate.nested.0
const hillContourGenerateTemplateTileAssetName = defineGroup(
  {
    id: "scene.template.hill-contour-generate.nested.0",
    version: "1.0.0",
    inputs: {
      input0: { type: Scene, runtimeType: "scene", runtimePort: "in_0", access: "item" },
      input1: { type: StringValue, runtimeType: "string", runtimePort: "in_1", access: "tree" },
    },
    outputs: {
      output0: { type: Scene, runtimeType: "scene", runtimePort: "out_0", access: "item" },
    },
  },
  ({ input0, input1 }) => {
    // @scene-id node-1790000000006-ptt9f
    const textPanel1 = textPanel({
        "$params": {"text":"asset_name","_nodeWidth":180,"_nodeHeight":67},
      })

    // @scene-id node-1790000000006-rm2fy
    const textPanel2 = textPanel({
        "$params": {"text":"asset_type","_nodeWidth":181,"_nodeHeight":60},
      })

    // @scene-id node-1790000000006-obfmb
    const textPanel3 = textPanel({
        "$params": {"text":"tile","_nodeWidth":181,"_nodeHeight":60},
      })

    // @scene-id node-1790000000006-94gxn
    const stringValue4 = stringValue({
        "value": input1,
      })

    // @scene-id node-1790000000006-4twly
    const sceneSetAttribute5 = sceneSetAttribute({
        "scene": input0,
        "key": textPanel1.output,
        "value": stringValue4.value,
      })

    // @scene-id node-1790000000006-0767k
    const sceneSetAttribute6 = sceneSetAttribute({
        "scene": sceneSetAttribute5.scene,
        "key": textPanel2.output,
        "value": textPanel3.output,
      })
    return {
      output0: sceneSetAttribute6.scene,
    }
  },
)

// @scene-id definition:batteries.templates.structures.topographic.hill-contour-generate.hill-contour-generate
export const hillContourGenerateTemplate = defineGroup(
  {
    id: "scene.template.hill-contour-generate",
    version: "1.0.0",
    inputs: {
      scene: { type: Scene, runtimeType: "scene", runtimePort: "in_0", access: "tree", labelEn: "Scene" },
      assetName: { type: StringValue, runtimeType: "string", runtimePort: "in_1", labelEn: "AssetName" },
      seed: { type: NumberValue, runtimeType: "number", runtimePort: "in_2", access: "tree", labelEn: "Seed" },
      contourLevels: { type: NumberValue, runtimeType: "number", runtimePort: "in_3", access: "item", labelEn: "ContourLevels" },
      hillCount: { type: NumberValue, runtimeType: "number", runtimePort: "in_4", access: "item", labelEn: "HillCount" },
      roundness: { type: NumberValue, runtimeType: "number", runtimePort: "in_5", access: "item", labelEn: "Roundness" },
      peakRadius: { type: NumberValue, runtimeType: "number", runtimePort: "in_6", access: "item", labelEn: "PeakRadius" },
      noiseAmount: { type: NumberValue, runtimeType: "number", runtimePort: "in_7", access: "item", labelEn: "NoiseAmount" },
      peakPosition: { type: NumberValue, runtimeType: "number", runtimePort: "in_8", access: "item", labelEn: "PeakPosition" },
      input9: { type: NumberValue, runtimeType: "number", runtimePort: "in_9", access: "item", hidden: true },
      input10: { type: NumberValue, runtimeType: "number", runtimePort: "in_10", access: "item", hidden: true },
      input11: { type: NumberValue, runtimeType: "number", runtimePort: "in_11", access: "item", hidden: true },
      input12: { type: NumberValue, runtimeType: "number", runtimePort: "in_12", access: "item", hidden: true },
      input13: { type: StringValue, runtimeType: "string", runtimePort: "in_13", access: "item", hidden: true },
      input14: { type: StringValue, runtimeType: "string", runtimePort: "in_14", access: "item", hidden: true },
      input15: { type: NumberList, runtimeType: "number", runtimePort: "in_15", access: "list", hidden: true },
    },
    outputs: {
      scene: { type: Scene, runtimeType: "scene", runtimePort: "out_0", access: "tree", order: 0, labelEn: "Scene" },
      hill: { type: Scene, runtimeType: "scene", runtimePort: "out_1", access: "tree", order: 1, labelEn: "Hill" },
      rest: { type: Scene, runtimeType: "scene", runtimePort: "out_2", access: "tree", order: 2, labelEn: "Rest" },
      hillPath: { type: StringValue, runtimeType: "string", runtimePort: "out_3", access: "tree", order: 3, labelEn: "HillPath" },
      restPath: { type: StringValue, runtimeType: "string", runtimePort: "out_4", access: "tree", order: 4, labelEn: "RestPath" },
    },
  },
  ({ scene, assetName, seed, contourLevels, hillCount, roundness, peakRadius, noiseAmount, peakPosition, input9, input10, input11, input12, input13, input14, input15 }) => {
    // @scene-id node-1790000000006-c6vfi
    const scenePassthrough1 = scenePassthrough({
        "scene": scene,
      })

    // @scene-id node-1790000000006-du9e8
    const nodeExplode2 = nodeExplode({
        "scene": scenePassthrough1.scene,
      })

    // @scene-id node-1790000000006-6viw4
    const rectangularGrid3 = rectangularGrid({
        "fillValue": input11,
        "width": nodeExplode2.width,
        "height": nodeExplode2.height,
      })

    // @scene-id node-1790000000006-kej41
    const voxelSlice4 = voxelSlice({
        "z": input12,
        "voxels": nodeExplode2.voxels,
        "grid": rectangularGrid3.grid,
      })

    // @scene-id node-1790000000006-k9f8t
    const multiSeed5 = multiSeed({
        "seed": seed,
        "shape": voxelSlice4.slice,
      })

    // @scene-id node-1790000000006-h4vj0
    const hillContourGenerate6 = hillContourGenerate({
        "contourLevels": contourLevels,
        "hillCount": hillCount,
        "roundness": roundness,
        "peakRadius": peakRadius,
        "noiseAmount": noiseAmount,
        "peakPosition": peakPosition,
        "minHoleSize": input9,
        "minIslandSize": input10,
        "inputGrid": voxelSlice4.slice,
        "seed": multiSeed5.seed,
      })

    // @scene-id node-1790000000006-slehw
    const gridSplitByValue7 = gridSplitByValue({
        "grid": hillContourGenerate6.outputGrid,
      })

    // @scene-id node-1790000000006-i7rtn
    const strToListBranches8 = strToListBranches({
        "str": assetName,
      })

    // @scene-id node-1790000000006-tkeb1
    const gridSceneNode9 = gridSceneNode({
        "schema": input13,
        "token": input14,
        "zRange": input15,
        "grid": gridSplitByValue7.grids,
        "name": strToListBranches8.items,
        "z": gridSplitByValue7.values,
      })

    // @scene-id group_1790000000006_hg1xq
    const hillContourGenerateTemplateTileAssetName10 = hillContourGenerateTemplateTileAssetName({
        "input0": gridSceneNode9.scene,
        "input1": strToListBranches8.items,
      })

    // @scene-id node-1790000000006-3eptq
    const addSceneChildren11 = addSceneChildren({
        "nodes": hillContourGenerateTemplateTileAssetName10.output0,
        "scene": scenePassthrough1.scene,
      })

    // @scene-id node-1790000000006-7vrak
    const algRegionSubtract12 = algRegionSubtract({
        "a": voxelSlice4.slice,
        "b": hillContourGenerate6.outputGrid,
      })

    // @scene-id node-1790000000006-2kmi6
    const textPanel13 = textPanel({
        "$params": {"text":"rest","_nodeWidth":172,"_nodeHeight":69},
      })

    // @scene-id node-1790000000006-6ldzn
    const gridSceneNode14 = gridSceneNode({
        "grid": algRegionSubtract12.region,
        "name": textPanel13.output,
      })

    // @scene-id node-1790000000006-ynr0v
    const addSceneChildren15 = addSceneChildren({
        "scene": addSceneChildren11.scene,
        "nodes": gridSceneNode14.scene,
      })

    // @scene-id node-1790000000006-xykwm
    const sceneMergeSubtrees16 = sceneMergeSubtrees({
        "scenes": addSceneChildren15.scene,
      })

    // @scene-id node-1790000000006-9l2e4
    const sceneFocusPath17 = sceneFocusPath({
        "scene": sceneMergeSubtrees16.scene,
        "path": addSceneChildren11.childPaths,
      })

    // @scene-id node-1790000000006-7hkpo
    const sceneFocusPath18 = sceneFocusPath({
        "scene": sceneMergeSubtrees16.scene,
        "path": addSceneChildren15.childPaths,
      })

    // @scene-id node-1790000000006-g36ob
    const scenePassthrough19 = scenePassthrough({
        "scene": sceneMergeSubtrees16.scene,
      })

    // @scene-id node-1790000000006-xgreg
    const scenePassthrough20 = scenePassthrough({
        "scene": sceneFocusPath17.scene,
      })

    // @scene-id node-1790000000006-o1ju5
    const scenePassthrough21 = scenePassthrough({
        "scene": sceneFocusPath18.scene,
      })

    // @scene-id node-1790000000006-4djdc
    const stringValue22 = stringValue({
        "value": addSceneChildren11.childPaths,
      })

    // @scene-id node-1790000000006-4kbf3
    const stringValue23 = stringValue({
        "value": addSceneChildren15.childPaths,
      })
    return {
      scene: scenePassthrough19.scene,
      hill: scenePassthrough20.scene,
      rest: scenePassthrough21.scene,
      hillPath: stringValue22.value,
      restPath: stringValue23.value,
    }
  },
)
