/**
 * 影游 → 一等引擎 game 的「壳」生成（B1/B3，主程 07-06 收敛裁决）。
 *
 * 编译产物落在 `.forgeax/games/<slug>/`，与所有引擎 game 同构：
 *   - `forge.json`：`entry:"main.ts"`，**无 defaultScene、无 reelGameGuid**
 *     （forge.json 是 `.strict()` schema，reelGameGuid 是非法字段 → B3 删除）。
 *   - `main.ts`：薄壳 `export const bootstrap = createReelBootstrap('<guid>')`，
 *     播放走 play-runtime 统一 kind-blind 路径（createApp → import main.ts → bootstrap），
 *     host 零 kind 分支。入口 GUID 由 main.ts 壳持有（不再塞 forge.json）。
 *   - 媒体 pack（`assets/reel-game.pack.json` + `assets/reel-media/`）由 buildReelGameAsset 产（B2）。
 *
 * 纯函数（无 I/O），供 build CLI（packages/build/reel-src/export）与 wb-reel 编辑器
 * 「编译/导出」动作共用、可单测。
 */

const UUID_RE = /^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/;

export interface ReelGameShell {
  /** 已 sanitize 的 forge.json 对象（调用方负责 JSON.stringify 落盘）。 */
  forge: Record<string, unknown>;
  /** main.ts 薄壳源码。 */
  mainTs: string;
  /** 入口 reel-game 资产 GUID（= pack 里 reel-game 条目的 guid，= createReelBootstrap 参数）。 */
  guid: string;
}

export interface BuildReelGameShellOptions {
  /** 入口 reel-game 资产 GUID（须为合法 UUID；= buildReelGameAsset 的 opts.guid）。 */
  guid: string;
  /** 游戏 slug（= `.forgeax/games/<slug>/` 目录名；forge.json.id 必须与之一致）。 */
  slug: string;
  /** 显示名（缺省用既有 forge.name 或 slug）。 */
  title?: string;
  /** 既有 forge.json（保留合法字段如 physics/preview；剔除 reelGameGuid/defaultScene）。 */
  existingForge?: Record<string, unknown>;
}

/** 渲染 main.ts 薄壳源码。类型标注即 A3 窄镜像对真 `BootstrapEntry` 的编译期断言点。 */
export function renderReelMainTs(guid: string): string {
  if (!UUID_RE.test(guid)) {
    throw new Error(`[reel-shell] renderReelMainTs: 非法 guid: ${guid}`);
  }
  return `// Auto-generated by wb-reel export — DO NOT EDIT.
// 互动影游（reel）作为一个普通 forgeax-engine game 的薄壳入口。
// 播放由 @forgeax-extension/wb-reel 的 reel-runtime 驱动：把 DOM 视频/图/字幕挂到 ctx.uiRoot，
// 不画 3D。走 play-runtime 统一 kind-blind 路径（createApp → import main.ts → bootstrap）。
import type { World } from '@forgeax/engine-ecs';
import type { BootstrapContext } from '@forgeax/engine-app';
import { createReelBootstrap } from '@forgeax-extension/wb-reel/runtime';

// reel-game scenario 资产 GUID（与 assets/reel-game.pack.json 里 reel-game 入口条目一致）。
// 类型标注为真 BootstrapEntry：这里就是 reel-runtime 窄结构镜像对引擎契约的编译期断言。
export const bootstrap: (world: World, ctx?: BootstrapContext) => void | Promise<void> =
  createReelBootstrap(${JSON.stringify(guid)});
`;
}

/** 生成影游一等 game 的 forge.json 对象 + main.ts 薄壳。纯函数。 */
export function buildReelGameShell(opts: BuildReelGameShellOptions): ReelGameShell {
  const { guid, slug } = opts;
  if (!UUID_RE.test(guid)) {
    throw new Error(`[reel-shell] buildReelGameShell: 非法 guid: ${guid}`);
  }
  if (!slug) {
    throw new Error('[reel-shell] buildReelGameShell: slug 必填');
  }

  const forge: Record<string, unknown> = { ...(opts.existingForge ?? {}) };
  // B3：forge.json 是 .strict() schema —— reelGameGuid 是非法字段，删除（入口 GUID 改由 main.ts 壳持有）。
  delete forge.reelGameGuid;
  // 07-06 裁决：reel 无 defaultScene（缺失时 play-runtime 优雅跳过、bootstrap 照常触发）。
  delete forge.defaultScene;
  // id 必须与目录名一致。
  forge.id = slug;
  forge.name =
    typeof forge.name === 'string' && forge.name.length > 0 ? forge.name : opts.title || slug;
  if (typeof forge.schemaVersion !== 'string') forge.schemaVersion = '1.0.0';
  // B1：引擎 bootstrap 入口。
  forge.entry = 'main.ts';

  return { forge, mainTs: renderReelMainTs(guid), guid };
}
