// Generated from sibling meta.json; edit deliberately and keep parity.
import { defineAtomic } from '@forgeax/scene-authoring'

export default defineAtomic({
  "functionName": "wangTile",
  "contractVersion": "3.0.0",
  "opId": "wang_tile",
  "description": "Wang Tile constraint-based terrain generator with 25 built-in Noita inside.png atlas tiles downsampled to 20×10 / 10×20. Output: 0=wall/solid, 1,2,3...=connected structure region IDs.",
  "inputs": [
    {
      "name": "tiles",
      "type": "grid",
      "description": "Array of tile templates, each a 2D number grid (0=solid/bg, 1=structure/passage, 2=terrain). All tiles must be the same size. If empty, uses built-in Noita inside.png horizontal tiles (20×10, 25 tiles) (rank=1: K grids).",
      "label": "瓦片列表"
    },
    {
      "name": "edgeLabels",
      "type": "dict",
      "description": "Array of edge label objects (same length as tiles). Each has {N,S,E,W} string labels. When provided, uses label matching instead of border pixel matching. Can be auto-generated by atlas_to_tiles.py converter (rank=1: K dicts).",
      "label": "边缘标签"
    },
    {
      "name": "defaultSet",
      "type": "string",
      "defaultValue": "horizontal",
      "description": "Built-in tile set to use when tiles input is empty: 'horizontal' (20×10) or 'vertical' (10×20).",
      "label": "默认瓦片组",
      "mode": "parameter"
    },
    {
      "name": "rows",
      "type": "number",
      "defaultValue": 8,
      "description": "Number of tile rows (1~64). Output height = rows × tile height.",
      "label": "行数",
      "mode": "parameter"
    },
    {
      "name": "cols",
      "type": "number",
      "defaultValue": 8,
      "description": "Number of tile columns (1~64). Output width = cols × tile width.",
      "label": "列数",
      "mode": "parameter"
    },
    {
      "name": "weights",
      "type": "number",
      "description": "Weight array (same length as tiles). Higher weight = higher selection probability. If empty, uses equal weights (rank=1).",
      "label": "权重列表",
      "mode": "parameter"
    },
    {
      "name": "seed",
      "type": "number",
      "defaultValue": 0,
      "description": "Random seed; 0 uses default. Different seeds produce different layouts.",
      "label": "随机种子",
      "mode": "parameter"
    }
  ],
  "outputs": [
    {
      "name": "grid",
      "type": "grid",
      "description": "Partition grid: 0=wall/solid, 1,2,3...=connected structure region IDs (flood-fill labeling).",
      "label": "区域网格"
    },
    {
      "name": "valueGrid",
      "type": "grid",
      "description": "Material grid: 0=solid/bg, 1=structure/passage, 2=terrain feature. Raw tile values, can be combined with region grid.",
      "label": "材质网格"
    },
    {
      "name": "regionCount",
      "type": "number",
      "description": "Total number of connected non-wall regions.",
      "label": "区域数"
    },
    {
      "name": "numTiles",
      "type": "number",
      "description": "Total number of tiles placed (= rows × cols).",
      "label": "瓦片总数"
    }
  ],
  "deterministic": true
})
