// Generated by scripts/generate-native-group-definitions.mts.
// JSON parity oracle only: batteries/groups/scene/PathConnection/PathConnection.json
// @scene-id definition:batteries.groups.scene.path-connection.path-connection.nested.0
const pathConnectionTileAssetName = defineGroup(
  {
    id: "scene.group.scene.path-connection.path-connection.nested.0",
    version: "1.0.0",
    inputs: {
      input0: { type: Scene, runtimeType: "scene", runtimePort: "in_0", access: "item" },
      input1: { type: StringValue, runtimeType: "string", runtimePort: "in_1", access: "tree" },
    },
    outputs: {
      output0: { type: Scene, runtimeType: "scene", runtimePort: "out_0", access: "item" },
    },
  },
  ({ input0, input1 }) => {
    // @scene-id node-1781833009971-xqqh3
    const textPanel1 = textPanel({
        "$params": {"text":"asset_name","_nodeWidth":180,"_nodeHeight":67},
      })

    // @scene-id node-1781833009971-owdnw
    const textPanel2 = textPanel({
        "$params": {"text":"asset_type","_nodeWidth":181,"_nodeHeight":60},
      })

    // @scene-id node-1781833009971-503ho
    const textPanel3 = textPanel({
        "$params": {"text":"tile","_nodeWidth":181,"_nodeHeight":60},
      })

    // @scene-id node-1781833009971-tpa7p
    const stringValue4 = stringValue({
        "value": input1,
      })

    // @scene-id node-1781833009971-b8znd
    const sceneSetAttribute5 = sceneSetAttribute({
        "scene": input0,
        "key": textPanel1.output,
        "value": stringValue4.value,
      })

    // @scene-id node-1781833009971-jfgou
    const sceneSetAttribute6 = sceneSetAttribute({
        "scene": sceneSetAttribute5.scene,
        "key": textPanel2.output,
        "value": textPanel3.output,
      })
    return {
      output0: sceneSetAttribute6.scene,
    }
  },
)

// @scene-id definition:batteries.groups.scene.path-connection.path-connection
export const pathConnection = defineGroup(
  {
    id: "scene.group.scene.path-connection.path-connection",
    version: "1.0.0",
    inputs: {
      input0: { type: NumberValue, runtimeType: "number", runtimePort: "in_4", order: 1 },
      input1: { type: NumberValue, runtimeType: "number", runtimePort: "in_5", hidden: true, order: 2 },
      scene: { type: Scene, runtimeType: "scene", runtimePort: "in_2", access: "tree", order: 0, labelEn: "Scene" },
      input3: { type: NumberValue, runtimeType: "number", runtimePort: "in_6", access: "item", hidden: true, order: 3 },
      input4: { type: NumberValue, runtimeType: "number", runtimePort: "in_7", access: "item", hidden: true, order: 4 },
      roadName: { type: StringValue, runtimeType: "string", runtimePort: "in_0", access: "item", order: 5, labelEn: "RoadName" },
      input6: { type: StringValue, runtimeType: "string", runtimePort: "in_8", access: "item", hidden: true, order: 6 },
      input7: { type: StringValue, runtimeType: "string", runtimePort: "in_9", access: "item", hidden: true, order: 7 },
      roadAsset: { type: StringValue, runtimeType: "string", runtimePort: "in_1", access: "tree", order: 8, labelEn: "RoadAsset" },
      input9: { type: StringValue, runtimeType: "string", runtimePort: "in_10", access: "item", hidden: true, order: 9 },
      input10: { type: StringValue, runtimeType: "string", runtimePort: "in_11", access: "item", hidden: true, order: 10 },
      input11: { type: NumberList, runtimeType: "number", runtimePort: "in_12", access: "list", hidden: true, order: 11 },
      pOI: { type: Point2d, runtimeType: "point2d", runtimePort: "in_3", access: "list", order: 12, labelEn: "POI" },
      input13: { type: NumberValue, runtimeType: "number", runtimePort: "in_13", access: "item", hidden: true, order: 13 },
      input14: { type: StringValue, runtimeType: "string", runtimePort: "in_14", access: "item", hidden: true, order: 14 },
    },
    outputs: {
      scene: { type: Scene, runtimeType: "scene", runtimePort: "out_0", access: "tree", order: 0, labelEn: "Scene" },
      path: { type: Scene, runtimeType: "scene", runtimePort: "out_1", access: "tree", order: 1, labelEn: "Path" },
      rest: { type: Scene, runtimeType: "scene", runtimePort: "out_2", access: "tree", order: 3, labelEn: "Rest" },
      pathPath: { type: StringValue, runtimeType: "string", runtimePort: "out_3", access: "tree", order: 2, labelEn: "PathPath" },
      restPath: { type: StringValue, runtimeType: "string", runtimePort: "out_4", access: "tree", order: 4, labelEn: "RestPath" },
    },
  },
  ({ input0, input1, scene, input3, input4, roadName, input6, input7, roadAsset, input9, input10, input11, pOI, input13, input14 }) => {
    // @scene-id node-1781838293221
    const booleanValue1 = booleanValue({
        "$params": {"value":true},
      })

    // @scene-id node-1781833009971-d0fe6
    const scenePassthrough2 = scenePassthrough({
        "scene": scene,
      })

    // @scene-id node-1781833009971-hljbi
    const nodeExplode3 = nodeExplode({
        "scene": scenePassthrough2.scene,
      })

    // @scene-id node-1781833009971-b4rdr
    const rectangularGrid4 = rectangularGrid({
        "fillValue": input3,
        "width": nodeExplode3.width,
        "height": nodeExplode3.height,
      })

    // @scene-id node-1781833009971-qpckm
    const voxelSlice5 = voxelSlice({
        "z": input4,
        "voxels": nodeExplode3.voxels,
        "grid": rectangularGrid4.grid,
      })

    // @scene-id node-1781833009971-0xnpv
    const algRegionSubtract6 = algRegionSubtract({
        "a": rectangularGrid4.grid,
        "b": voxelSlice5.slice,
      })

    // @scene-id node-1781833009971-eaa1h
    const textPanel7 = textPanel({
        "$params": {"text":"rest","_nodeWidth":172,"_nodeHeight":69},
      })

    // @scene-id node-1781838422205
    const rangeList8 = rangeList({
        "step": input13,
        "prefix": input14,
        "end": voxelSlice5.z,
        "start": voxelSlice5.z,
      })

    // @scene-id node-path-poi-grid
    const pointsToGrid9 = pointsToGrid({
        "points": pOI,
        "region": voxelSlice5.slice,
      })

    // @scene-id node-1781833009971-jqytz
    const algTopologyConnectPoints10 = algTopologyConnectPoints({
        "roadWidth": input0,
        "roadValue": input1,
        "coverPoi": booleanValue1.value,
        "obstacle": algRegionSubtract6.region,
        "poiGrid": pointsToGrid9.mask,
      })

    // @scene-id node-1781833009971-2et7b
    const gridSceneNode11 = gridSceneNode({
        "name": roadName,
        "schema": input6,
        "token": input7,
        "grid": algTopologyConnectPoints10.topology,
        "zRange": rangeList8.list,
      })

    // @scene-id group_1781833009971_vydtw
    const pathConnectionTileAssetName12 = pathConnectionTileAssetName({
        "input1": roadAsset,
        "input0": gridSceneNode11.scene,
      })

    // @scene-id node-1781833009971-k921s
    const addSceneChildren13 = addSceneChildren({
        "nodes": pathConnectionTileAssetName12.output0,
        "scene": scenePassthrough2.scene,
      })

    // @scene-id node-1781833009971-04pyl
    const algRegionSubtract14 = algRegionSubtract({
        "a": voxelSlice5.slice,
        "b": algTopologyConnectPoints10.topology,
      })

    // @scene-id node-1781833009971-ov86z
    const gridSceneNode15 = gridSceneNode({
        "schema": input9,
        "token": input10,
        "zRange": input11,
        "name": textPanel7.output,
        "grid": algRegionSubtract14.region,
      })

    // @scene-id node-1781833009971-tt6oo
    const addSceneChildren16 = addSceneChildren({
        "scene": addSceneChildren13.scene,
        "nodes": gridSceneNode15.scene,
      })

    // @scene-id node-1781833009971-kd94f
    const sceneMergeSubtrees17 = sceneMergeSubtrees({
        "scenes": addSceneChildren16.scene,
      })

    // @scene-id node-1781833009971-7rtwm
    const sceneFocusPath18 = sceneFocusPath({
        "path": addSceneChildren13.childPaths,
        "scene": sceneMergeSubtrees17.scene,
      })

    // @scene-id node-1781833009971-t2hn0
    const scenePassthrough19 = scenePassthrough({
        "scene": sceneMergeSubtrees17.scene,
      })

    // @scene-id node-1781833009971-2sl5s
    const sceneFocusPath20 = sceneFocusPath({
        "path": addSceneChildren16.childPaths,
        "scene": sceneMergeSubtrees17.scene,
      })

    // @scene-id node-1781833009971-2478v
    const scenePassthrough21 = scenePassthrough({
        "scene": sceneFocusPath18.scene,
      })

    // @scene-id node-1781833009971-880ru
    const scenePassthrough22 = scenePassthrough({
        "scene": sceneFocusPath20.scene,
      })

    // @scene-id node-1781833009971-a1cxl
    const stringValue23 = stringValue({
        "value": addSceneChildren13.childPaths,
      })

    // @scene-id node-1781833009971-6ezsf
    const stringValue24 = stringValue({
        "value": addSceneChildren16.childPaths,
      })
    return {
      scene: scenePassthrough19.scene,
      path: scenePassthrough21.scene,
      rest: scenePassthrough22.scene,
      pathPath: stringValue23.value,
      restPath: stringValue24.value,
    }
  },
)
