// Generated by scripts/generate-native-group-definitions.mts.
// JSON parity oracle only: batteries/groups/test_terrain/Group Node/Group Node.json
// Inventory status: retired-test-oracle; never loaded by the production Registry.
// @scene-id definition:batteries.groups.test-terrain.group-node.group-node.nested.0
const groupNodeZoneNesting = defineGroup(
  {
    id: "scene.group.test-terrain.group-node.group-node.nested.0",
    version: "1.0.0",
    inputs: {
      input0: { type: Scene, runtimeType: "scene", runtimePort: "in_0", access: "tree" },
      districtName: { type: StringValue, runtimeType: "string", runtimePort: "in_1", access: "tree", labelEn: "DistrictName" },
      seed: { type: NumberValue, runtimeType: "number", runtimePort: "in_2", access: "tree", labelEn: "Seed" },
      erosionStrength: { type: NumberValue, runtimeType: "number", runtimePort: "in_3", access: "item", labelEn: "ErosionStrength" },
      layers: { type: NumberValue, runtimeType: "number", runtimePort: "in_4", access: "item", labelEn: "Layers" },
      splineSmoothness: { type: NumberValue, runtimeType: "number", runtimePort: "in_5", access: "item", labelEn: "SplineSmoothness" },
      input6: { type: NumberValue, runtimeType: "number", runtimePort: "in_6", access: "item", hidden: true },
      input7: { type: StringValue, runtimeType: "string", runtimePort: "in_7", access: "item", hidden: true },
      input8: { type: StringValue, runtimeType: "string", runtimePort: "in_8", access: "item", hidden: true },
      input9: { type: NumberValue, runtimeType: "number", runtimePort: "in_9", access: "item", hidden: true },
      input10: { type: NumberValue, runtimeType: "number", runtimePort: "in_10", access: "item", hidden: true },
      input11: { type: NumberValue, runtimeType: "number", runtimePort: "in_11", access: "item", hidden: true },
      input12: { type: StringValue, runtimeType: "string", runtimePort: "in_12", access: "item", hidden: true },
      input13: { type: StringValue, runtimeType: "string", runtimePort: "in_13", access: "item", hidden: true },
      input14: { type: NumberList, runtimeType: "number", runtimePort: "in_14", access: "list", hidden: true },
    },
    outputs: {
      output0: { type: Scene, runtimeType: "scene", runtimePort: "out_0", access: "tree", order: 0 },
      rest: { type: Scene, runtimeType: "scene", runtimePort: "out_1", access: "tree", order: 1, labelEn: "Rest" },
      district: { type: Scene, runtimeType: "scene", runtimePort: "out_2", access: "tree", order: 2, labelEn: "District" },
      districtPath: { type: StringValue, runtimeType: "string", runtimePort: "out_3", access: "tree", order: 3, labelEn: "DistrictPath" },
      restPath: { type: StringValue, runtimeType: "string", runtimePort: "out_4", access: "tree", order: 4, labelEn: "RestPath" },
    },
  },
  ({ input0, districtName, seed, erosionStrength, layers, splineSmoothness, input6, input7, input8, input9, input10, input11, input12, input13, input14 }) => {
    // @scene-id node-1782135422794-av8z0
    const scenePassthrough1 = scenePassthrough({
        "scene": input0,
      })

    // @scene-id node-1782135422794-uu20v
    const nodeExplode2 = nodeExplode({
        "scene": scenePassthrough1.scene,
      })

    // @scene-id node-1782135422794-bn0qq
    const rectangularGrid3 = rectangularGrid({
        "fillValue": input10,
        "width": nodeExplode2.width,
        "height": nodeExplode2.height,
      })

    // @scene-id node-1782135422794-txozr
    const voxelSlice4 = voxelSlice({
        "z": input11,
        "voxels": nodeExplode2.voxels,
        "grid": rectangularGrid3.grid,
      })

    // @scene-id node-1782135422794-v6cxg
    const multiSeed5 = multiSeed({
        "seed": seed,
        "shape": voxelSlice4.slice,
      })

    // @scene-id node-1782135422794-s4fsk
    const zoneNesting6 = zoneNesting({
        "$params": {"splineAlgorithm":"cubic_spline"},
        "erosionStrength": erosionStrength,
        "layers": layers,
        "splineSmoothness": splineSmoothness,
        "targetValue": input6,
        "algorithm": input7,
        "splineAlgorithm": input8,
        "splineSeed": input9,
        "inputGrid": voxelSlice4.slice,
        "seed": multiSeed5.seed,
      })

    // @scene-id node-1782135422794-y9s8j
    const stringValue7 = stringValue({
        "value": districtName,
      })

    // @scene-id node-1782135422794-suyfj
    const gridSceneNode8 = gridSceneNode({
        "schema": input12,
        "token": input13,
        "zRange": input14,
        "grid": zoneNesting6.outputGrid,
        "name": stringValue7.value,
      })

    // @scene-id group_1782135422794_gplhj
    const groupNodeTileAssetName9 = groupNodeTileAssetName({
        "input0": gridSceneNode8.scene,
        "input1": stringValue7.value,
      })

    // @scene-id node-1782135422794-lszia
    const addSceneChildren10 = addSceneChildren({
        "nodes": groupNodeTileAssetName9.output0,
        "scene": scenePassthrough1.scene,
      })

    // @scene-id node-1782135422794-o7bd0
    const algRegionSubtract11 = algRegionSubtract({
        "a": voxelSlice4.slice,
        "b": zoneNesting6.outputGrid,
      })

    // @scene-id node-1782135422794-lrbtb
    const textPanel12 = textPanel({
        "$params": {"text":"rest","_nodeWidth":172,"_nodeHeight":69},
      })

    // @scene-id node-1782135422794-ojdr7
    const gridSceneNode13 = gridSceneNode({
        "grid": algRegionSubtract11.region,
        "name": textPanel12.output,
      })

    // @scene-id node-1782135422794-ocg0t
    const addSceneChildren14 = addSceneChildren({
        "scene": addSceneChildren10.scene,
        "nodes": gridSceneNode13.scene,
      })

    // @scene-id node-1782135422794-n0t1c
    const sceneMergeSubtrees15 = sceneMergeSubtrees({
        "scenes": addSceneChildren14.scene,
      })

    // @scene-id node-1782135422794-p60jt
    const sceneFocusPath16 = sceneFocusPath({
        "scene": sceneMergeSubtrees15.scene,
        "path": addSceneChildren10.childPaths,
      })

    // @scene-id node-1782135422794-aou7b
    const sceneFocusPath17 = sceneFocusPath({
        "scene": sceneMergeSubtrees15.scene,
        "path": addSceneChildren14.childPaths,
      })

    // @scene-id node-1782135422794-1suaw
    const scenePassthrough18 = scenePassthrough({
        "scene": sceneMergeSubtrees15.scene,
      })

    // @scene-id node-1782135422794-txr5d
    const scenePassthrough19 = scenePassthrough({
        "scene": sceneFocusPath16.scene,
      })

    // @scene-id node-1782135422794-86w38
    const scenePassthrough20 = scenePassthrough({
        "scene": sceneFocusPath17.scene,
      })

    // @scene-id node-1782135422794-0kvnp
    const stringValue21 = stringValue({
        "value": addSceneChildren10.childPaths,
      })

    // @scene-id node-1782135422794-e93ia
    const stringValue22 = stringValue({
        "value": addSceneChildren14.childPaths,
      })
    return {
      output0: scenePassthrough18.scene,
      rest: scenePassthrough20.scene,
      district: scenePassthrough19.scene,
      districtPath: stringValue21.value,
      restPath: stringValue22.value,
    }
  },
)

// @scene-id definition:batteries.groups.test-terrain.group-node.group-node.nested.1
const groupNodeTileAssetName = defineGroup(
  {
    id: "scene.group.test-terrain.group-node.group-node.nested.1",
    version: "1.0.0",
    inputs: {
      input0: { type: Scene, runtimeType: "scene", runtimePort: "in_0", access: "item" },
      input1: { type: StringValue, runtimeType: "string", runtimePort: "in_1", access: "tree" },
    },
    outputs: {
      output0: { type: Scene, runtimeType: "scene", runtimePort: "out_0", access: "item" },
    },
  },
  ({ input0, input1 }) => {
    // @scene-id node-1782135422794-jw5p8
    const textPanel1 = textPanel({
        "$params": {"text":"asset_name","_nodeWidth":180,"_nodeHeight":67},
      })

    // @scene-id node-1782135422794-65l5i
    const textPanel2 = textPanel({
        "$params": {"text":"asset_type","_nodeWidth":181,"_nodeHeight":60},
      })

    // @scene-id node-1782135422794-lngl5
    const textPanel3 = textPanel({
        "$params": {"text":"tile","_nodeWidth":181,"_nodeHeight":60},
      })

    // @scene-id node-1782135422794-0i0yk
    const stringValue4 = stringValue({
        "value": input1,
      })

    // @scene-id node-1782135422794-c77kg
    const sceneSetAttribute5 = sceneSetAttribute({
        "scene": input0,
        "key": textPanel1.output,
        "value": stringValue4.value,
      })

    // @scene-id node-1782135422794-gwarw
    const sceneSetAttribute6 = sceneSetAttribute({
        "scene": sceneSetAttribute5.scene,
        "key": textPanel2.output,
        "value": textPanel3.output,
      })
    return {
      output0: sceneSetAttribute6.scene,
    }
  },
)

// @scene-id definition:batteries.groups.test-terrain.group-node.group-node.nested.2
const groupNodeLakeRegions = defineGroup(
  {
    id: "scene.group.test-terrain.group-node.group-node.nested.2",
    version: "1.0.0",
    inputs: {
      input0: { type: Scene, runtimeType: "scene", runtimePort: "in_0", access: "tree" },
      input1: { type: NumberValue, runtimeType: "number", runtimePort: "in_4", access: "item", hidden: true },
      input2: { type: NumberValue, runtimeType: "number", runtimePort: "in_5", access: "item", hidden: true },
      input3: { type: StringValue, runtimeType: "string", runtimePort: "in_6", hidden: true },
      input4: { type: StringValue, runtimeType: "string", runtimePort: "in_7", hidden: true },
      input5: { type: NumberValue, runtimeType: "number", runtimePort: "in_8", hidden: true },
      expectedLakes: { type: NumberValue, runtimeType: "number", runtimePort: "in_1", labelEn: "ExpectedLakes" },
      input7: { type: NumberValue, runtimeType: "number", runtimePort: "in_9", hidden: true },
      input8: { type: NumberValue, runtimeType: "number", runtimePort: "in_10", hidden: true },
      input9: { type: NumberValue, runtimeType: "number", runtimePort: "in_11", hidden: true },
      input10: { type: StringValue, runtimeType: "string", runtimePort: "in_12", access: "item", hidden: true },
      input11: { type: StringValue, runtimeType: "string", runtimePort: "in_13", access: "item", hidden: true },
      input12: { type: NumberList, runtimeType: "number", runtimePort: "in_14", access: "list", hidden: true },
      lakeAsset: { type: StringValue, runtimeType: "string", runtimePort: "in_2", access: "tree", labelEn: "LakeAsset" },
      input14: { type: StringValue, runtimeType: "string", runtimePort: "in_15", access: "item", hidden: true },
      input15: { type: StringValue, runtimeType: "string", runtimePort: "in_16", access: "item", hidden: true },
      input16: { type: NumberList, runtimeType: "number", runtimePort: "in_17", access: "list", hidden: true },
      seed: { type: NumberValue, runtimeType: "number", runtimePort: "in_3", access: "tree", labelEn: "Seed" },
    },
    outputs: {
      output0: { type: Scene, runtimeType: "scene", runtimePort: "out_0", access: "tree", order: 0 },
      lake: { type: Scene, runtimeType: "scene", runtimePort: "out_2", access: "tree", order: 1, labelEn: "Lake" },
      rest: { type: Scene, runtimeType: "scene", runtimePort: "out_1", access: "tree", order: 3, labelEn: "Rest" },
      lakePath: { type: StringValue, runtimeType: "string", runtimePort: "out_3", access: "tree", order: 2, labelEn: "LakePath" },
      restPath: { type: StringValue, runtimeType: "string", runtimePort: "out_4", access: "tree", order: 4, labelEn: "RestPath" },
    },
  },
  ({ input0, input1, input2, input3, input4, input5, expectedLakes, input7, input8, input9, input10, input11, input12, lakeAsset, input14, input15, input16, seed }) => {
    // @scene-id node-1782135463523-fdqrl
    const scenePassthrough1 = scenePassthrough({
        "scene": input0,
      })

    // @scene-id node-1782135463523-dllzu
    const nodeExplode2 = nodeExplode({
        "scene": scenePassthrough1.scene,
      })

    // @scene-id node-1782135463523-7w3gg
    const rectangularGrid3 = rectangularGrid({
        "fillValue": input1,
        "width": nodeExplode2.width,
        "height": nodeExplode2.height,
      })

    // @scene-id node-1782135463523-5dy58
    const voxelSlice4 = voxelSlice({
        "z": input2,
        "voxels": nodeExplode2.voxels,
        "grid": rectangularGrid3.grid,
      })

    // @scene-id node-1782135463523-dgn2i
    const textPanel5 = textPanel({
        "$params": {"text":"lake_","_nodeWidth":172,"_nodeHeight":69},
      })

    // @scene-id node-1782135463523-hyr95
    const textPanel6 = textPanel({
        "$params": {"text":"rest","_nodeWidth":172,"_nodeHeight":69},
      })

    // @scene-id node-1782135463523-abh29
    const numberValue7 = numberValue({
        "$params": {"value":3},
      })

    // @scene-id node-1782135463523-apw19
    const numberValue8 = numberValue({
        "$params": {"value":50},
      })

    // @scene-id node-1782135463523-rdlih
    const multiSeed9 = multiSeed({
        "seed": seed,
        "shape": voxelSlice4.slice,
      })

    // @scene-id node-1782135463523-tvbin
    const algPointsScatter10 = algPointsScatter({
        "mode": input3,
        "countMode": input4,
        "density": input5,
        "count": expectedLakes,
        "targetValue": input7,
        "region": voxelSlice4.slice,
        "minSpacing": numberValue7.value,
        "seed": multiSeed9.seed,
      })

    // @scene-id node-1782135463523-rsvwu
    const algRegionFloodGrow11 = algRegionFloodGrow({
        "sizeVariance": input8,
        "spacingDilate": input9,
        "points": algPointsScatter10.points,
        "region": voxelSlice4.slice,
        "size": numberValue8.value,
        "seed": multiSeed9.seed,
      })

    // @scene-id group_1782135463523_cncyr
    const groupNodeMultiNames12 = groupNodeMultiNames({
        "prefix": textPanel5.output,
        "count": algRegionFloodGrow11.count,
      })

    // @scene-id node-1782135463523-2rslr
    const gridSceneNode13 = gridSceneNode({
        "schema": input10,
        "token": input11,
        "zRange": input12,
        "name": groupNodeMultiNames12.names,
        "grid": algRegionFloodGrow11.partition,
      })

    // @scene-id group_1782135463523_6uyrm
    const groupNodeTileAssetName214 = groupNodeTileAssetName2({
        "input1": lakeAsset,
        "input0": gridSceneNode13.scene,
      })

    // @scene-id node-1782135463523-4k2i7
    const addSceneChildren15 = addSceneChildren({
        "nodes": groupNodeTileAssetName214.output0,
        "scene": scenePassthrough1.scene,
      })

    // @scene-id node-1782135463523-1ze1l
    const algRegionUnionAll16 = algRegionUnionAll({
        "regions": algRegionFloodGrow11.partition,
      })

    // @scene-id node-1782135463523-n9bgi
    const algRegionSubtract17 = algRegionSubtract({
        "a": voxelSlice4.slice,
        "b": algRegionUnionAll16.region,
      })

    // @scene-id node-1782135463523-6p2jg
    const gridSceneNode18 = gridSceneNode({
        "schema": input14,
        "token": input15,
        "zRange": input16,
        "name": textPanel6.output,
        "grid": algRegionSubtract17.region,
      })

    // @scene-id node-1782135463523-gtk5s
    const addSceneChildren19 = addSceneChildren({
        "scene": addSceneChildren15.scene,
        "nodes": gridSceneNode18.scene,
      })

    // @scene-id node-1782135463523-wjeh5
    const sceneMergeSubtrees20 = sceneMergeSubtrees({
        "scenes": addSceneChildren19.scene,
      })

    // @scene-id node-1782135463523-cmpdk
    const sceneFocusPath21 = sceneFocusPath({
        "path": addSceneChildren15.childPaths,
        "scene": sceneMergeSubtrees20.scene,
      })

    // @scene-id node-1782135463523-nsf12
    const scenePassthrough22 = scenePassthrough({
        "scene": sceneMergeSubtrees20.scene,
      })

    // @scene-id node-1782135463523-ahfzf
    const sceneFocusPath23 = sceneFocusPath({
        "path": addSceneChildren19.childPaths,
        "scene": sceneMergeSubtrees20.scene,
      })

    // @scene-id node-1782135463523-6w2wa
    const scenePassthrough24 = scenePassthrough({
        "scene": sceneFocusPath21.scene,
      })

    // @scene-id node-1782135463523-wvmgc
    const scenePassthrough25 = scenePassthrough({
        "scene": sceneFocusPath23.scene,
      })

    // @scene-id node-1782135463523-08aob
    const stringValue26 = stringValue({
        "value": addSceneChildren15.childPaths,
      })

    // @scene-id node-1782135463523-p2nef
    const stringValue27 = stringValue({
        "value": addSceneChildren19.childPaths,
      })
    return {
      output0: scenePassthrough22.scene,
      lake: scenePassthrough24.scene,
      rest: scenePassthrough25.scene,
      lakePath: stringValue26.value,
      restPath: stringValue27.value,
    }
  },
)

// @scene-id definition:batteries.groups.test-terrain.group-node.group-node.nested.3
const groupNodeMultiNames = defineGroup(
  {
    id: "scene.group.test-terrain.group-node.group-node.nested.3",
    version: "1.0.0",
    inputs: {
      input0: { type: StringValue, runtimeType: "string", runtimePort: "in_0", access: "tree", hidden: true },
      count: { type: NumberValue, runtimeType: "number", runtimePort: "in_1", access: "tree", labelEn: "Count" },
      input2: { type: NumberValue, runtimeType: "number", runtimePort: "in_2", access: "item", hidden: true },
      prefix: { type: StringValue, runtimeType: "string", runtimePort: "in_3", access: "tree", labelEn: "Prefix" },
    },
    outputs: {
      output0: { type: NumberList, runtimeType: "number", runtimePort: "out_0", access: "list", hidden: true },
      names: { type: StringList, runtimeType: "string", runtimePort: "out_1", access: "list", labelEn: "Names" },
      output2: { type: NumberValue, runtimeType: "number", runtimePort: "out_2", access: "item" },
    },
  },
  ({ input0, count, input2, prefix }) => {
    // @scene-id node-1782135463523-q1h49
    const numberValue1 = numberValue({})

    // @scene-id node-1782135463523-qkar2
    const numberValue2 = numberValue({
        "$params": {"value":1},
      })

    // @scene-id node-1782135463523-ybc44
    const typeNumber3 = typeNumber({
        "value": count,
      })

    // @scene-id node-1782135463523-lk7ww
    const basicMathOp4 = basicMathOp({
        "$params": {"op":"-"},
        "op": input0,
        "b": numberValue2.value,
        "a": typeNumber3.value,
      })

    // @scene-id node-1782135463523-tbm44
    const stringValue5 = stringValue({
        "value": prefix,
      })

    // @scene-id node-1782135463523-8w3v3
    const rangeList6 = rangeList({
        "step": input2,
        "start": numberValue1.value,
        "end": basicMathOp4.result,
        "prefix": stringValue5.value,
      })
    return {
      output0: rangeList6.list,
      names: rangeList6.stringList,
      output2: rangeList6.count,
    }
  },
)

// @scene-id definition:batteries.groups.test-terrain.group-node.group-node.nested.4
const groupNodeTileAssetName2 = defineGroup(
  {
    id: "scene.group.test-terrain.group-node.group-node.nested.4",
    version: "1.0.0",
    inputs: {
      input0: { type: Scene, runtimeType: "scene", runtimePort: "in_0", access: "item" },
      input1: { type: StringValue, runtimeType: "string", runtimePort: "in_1", access: "tree" },
    },
    outputs: {
      output0: { type: Scene, runtimeType: "scene", runtimePort: "out_0", access: "item" },
    },
  },
  ({ input0, input1 }) => {
    // @scene-id node-1782135463523-jfqvu
    const textPanel1 = textPanel({
        "$params": {"text":"asset_name","_nodeWidth":180,"_nodeHeight":67},
      })

    // @scene-id node-1782135463523-3gnj4
    const textPanel2 = textPanel({
        "$params": {"text":"asset_type","_nodeWidth":181,"_nodeHeight":60},
      })

    // @scene-id node-1782135463523-p0uhb
    const textPanel3 = textPanel({
        "$params": {"text":"tile","_nodeWidth":181,"_nodeHeight":60},
      })

    // @scene-id node-1782135463523-zm46r
    const stringValue4 = stringValue({
        "value": input1,
      })

    // @scene-id node-1782135463523-tj16p
    const sceneSetAttribute5 = sceneSetAttribute({
        "scene": input0,
        "key": textPanel1.output,
        "value": stringValue4.value,
      })

    // @scene-id node-1782135463523-mnfqg
    const sceneSetAttribute6 = sceneSetAttribute({
        "scene": sceneSetAttribute5.scene,
        "key": textPanel2.output,
        "value": textPanel3.output,
      })
    return {
      output0: sceneSetAttribute6.scene,
    }
  },
)

// @scene-id definition:batteries.groups.test-terrain.group-node.group-node
export const groupNode = defineGroup(
  {
    id: "scene.group.test-terrain.group-node.group-node",
    version: "1.0.0",
    inputs: {
      scene: { type: Scene, runtimeType: "scene", runtimePort: "in_0", label: "scene", labelEn: "Scene" },
      scene1: { type: Scene, runtimeType: "scene", runtimePort: "in_1", label: "scene", labelEn: "scene" },
      seed: { type: NumberValue, runtimeType: "number", runtimePort: "in_3", label: "seed", labelEn: "Seed" },
      layers: { type: NumberValue, runtimeType: "number", runtimePort: "in_4", label: "layers", labelEn: "Layers" },
      splineSmoothness: { type: NumberValue, runtimeType: "number", runtimePort: "in_5", label: "splineSmoothness", labelEn: "SplineSmoothness" },
      scene5: { type: Scene, runtimeType: "scene", runtimePort: "in_2", label: "scene", labelEn: "scene" },
      expectedLakes: { type: NumberValue, runtimeType: "number", runtimePort: "in_6", label: "count", labelEn: "ExpectedLakes" },
      lakeAsset: { type: StringValue, runtimeType: "string", runtimePort: "in_7", label: "value", labelEn: "LakeAsset" },
      seed8: { type: NumberValue, runtimeType: "number", runtimePort: "in_8", label: "seed", labelEn: "Seed" },
    },
    outputs: {
      output0: { type: Any, runtimeType: "voxel_layers", runtimePort: "out_0" },
      output1: { type: Any, runtimeType: "name_list", runtimePort: "out_1" },
      output2: { type: Any, runtimeType: "voxel_layers", runtimePort: "out_2" },
      output3: { type: Any, runtimeType: "name_list", runtimePort: "out_3" },
      output4: { type: Any, runtimeType: "voxel_layers", runtimePort: "out_4" },
      output5: { type: Any, runtimeType: "name_list", runtimePort: "out_5" },
    },
  },
  ({ scene, scene1, seed, layers, splineSmoothness, scene5, expectedLakes, lakeAsset, seed8 }) => {
    // @scene-id node-1782131241396
    const sceneOutput1 = sceneOutput({
        "scene": scene,
      })

    // @scene-id group_1782135463523_tbqyu
    const groupNodeLakeRegions2 = groupNodeLakeRegions({
        "$params": {"__groupSourceCategory":"interests","__groupSourceBatteryName":"LakeRegions","__groupSavedContentHash":"26ayr41e7j4","__groupIsTemplate":true,"__groupSourceGroupId":"group_1781238394903_rz71v"},
        "input0": scene5,
        "expectedLakes": expectedLakes,
        "lakeAsset": lakeAsset,
        "seed": seed8,
      })

    // @scene-id node-1782135468318-8dzak
    const sceneOutput3 = sceneOutput({
        "scene": groupNodeLakeRegions2.output0,
      })

    // @scene-id node-1782135557744-fvwd3
    const textPanel4 = textPanel({
        "$params": {"text":"boundary_forest","_nodeWidth":140,"_nodeHeight":60},
      })

    // @scene-id node-1782135612416-137sl
    const numberValue5 = numberValue({
        "$params": {"value":54,"min":0,"max":200,"precision":0},
      })

    // @scene-id group_1782135422794_mudai
    const groupNodeZoneNesting6 = groupNodeZoneNesting({
        "$params": {"__groupSourceCategory":"structures","__groupSourceBatteryName":"ZoneNesting","__groupSavedContentHash":"ex131exvwv","__groupIsTemplate":true,"__groupSourceGroupId":"group_zonenesting_district"},
        "input0": scene1,
        "seed": seed,
        "layers": layers,
        "splineSmoothness": splineSmoothness,
        "districtName": textPanel4.output,
        "erosionStrength": numberValue5.value,
      })

    // @scene-id node-1782135451937-wvv9t
    const sceneOutput7 = sceneOutput({
        "scene": groupNodeZoneNesting6.output0,
      })
    return {
      output0: sceneOutput1.layers,
      output1: sceneOutput1.names,
      output2: sceneOutput7.layers,
      output3: sceneOutput7.names,
      output4: sceneOutput3.layers,
      output5: sceneOutput3.names,
    }
  },
)
