// Generated by scripts/generate-native-group-definitions.mts.
// JSON parity oracle only: batteries/groups/scene/FarmlandRegions/FarmlandRegions.json
// @scene-id definition:batteries.groups.scene.farmland-regions.farmland-regions.nested.0
const farmlandRegionsMultiNames = defineGroup(
  {
    id: "scene.group.scene.farmland-regions.farmland-regions.nested.0",
    version: "1.0.0",
    inputs: {
      input0: { type: StringValue, runtimeType: "string", runtimePort: "in_0", access: "tree", hidden: true },
      count: { type: NumberValue, runtimeType: "number", runtimePort: "in_1", access: "tree", labelEn: "Count" },
      input2: { type: NumberValue, runtimeType: "number", runtimePort: "in_2", access: "item", hidden: true },
      prefix: { type: StringValue, runtimeType: "string", runtimePort: "in_3", access: "tree", labelEn: "Prefix" },
    },
    outputs: {
      output0: { type: NumberList, runtimeType: "number", runtimePort: "out_0", access: "list", hidden: true },
      names: { type: StringList, runtimeType: "string", runtimePort: "out_1", access: "list", labelEn: "Names" },
      output2: { type: NumberValue, runtimeType: "number", runtimePort: "out_2", access: "item" },
    },
  },
  ({ input0, count, input2, prefix }) => {
    // @scene-id node-1781197652579-0296q
    const numberValue1 = numberValue({})

    // @scene-id node-1781197652579-0lj7k
    const numberValue2 = numberValue({
        "$params": {"value":1},
      })

    // @scene-id node-1781197652579-rpg0h
    const typeNumber3 = typeNumber({
        "value": count,
      })

    // @scene-id node-1781197652579-9l5no
    const basicMathOp4 = basicMathOp({
        "$params": {"op":"-"},
        "op": input0,
        "b": numberValue2.value,
        "a": typeNumber3.value,
      })

    // @scene-id node-1781197652579-iqhju
    const stringValue5 = stringValue({
        "value": prefix,
      })

    // @scene-id node-1781197652579-wupta
    const rangeList6 = rangeList({
        "step": input2,
        "start": numberValue1.value,
        "end": basicMathOp4.result,
        "prefix": stringValue5.value,
      })
    return {
      output0: rangeList6.list,
      names: rangeList6.stringList,
      output2: rangeList6.count,
    }
  },
)

// @scene-id definition:batteries.groups.scene.farmland-regions.farmland-regions.nested.1
const farmlandRegionsTileAssetName = defineGroup(
  {
    id: "scene.group.scene.farmland-regions.farmland-regions.nested.1",
    version: "1.0.0",
    inputs: {
      input0: { type: Scene, runtimeType: "scene", runtimePort: "in_0", access: "item" },
      input1: { type: StringValue, runtimeType: "string", runtimePort: "in_1", access: "tree" },
    },
    outputs: {
      output0: { type: Scene, runtimeType: "scene", runtimePort: "out_0", access: "item" },
    },
  },
  ({ input0, input1 }) => {
    // @scene-id node-1781197652580-fgmz9
    const textPanel1 = textPanel({
        "$params": {"text":"asset_name","_nodeWidth":180,"_nodeHeight":67},
      })

    // @scene-id node-1781197652580-otthw
    const textPanel2 = textPanel({
        "$params": {"text":"asset_type","_nodeWidth":181,"_nodeHeight":60},
      })

    // @scene-id node-1781197652580-s4kze
    const textPanel3 = textPanel({
        "$params": {"text":"tile","_nodeWidth":181,"_nodeHeight":60},
      })

    // @scene-id node-1781197652580-5zp7n
    const stringValue4 = stringValue({
        "value": input1,
      })

    // @scene-id node-1781197652580-qlb1o
    const sceneSetAttribute5 = sceneSetAttribute({
        "scene": input0,
        "key": textPanel1.output,
        "value": stringValue4.value,
      })

    // @scene-id node-1781197652580-joub9
    const sceneSetAttribute6 = sceneSetAttribute({
        "scene": sceneSetAttribute5.scene,
        "key": textPanel2.output,
        "value": textPanel3.output,
      })
    return {
      output0: sceneSetAttribute6.scene,
    }
  },
)

// @scene-id definition:batteries.groups.scene.farmland-regions.farmland-regions.nested.2
const farmlandRegionsMultiNames2 = defineGroup(
  {
    id: "scene.group.scene.farmland-regions.farmland-regions.nested.2",
    version: "1.0.0",
    inputs: {
      input0: { type: StringValue, runtimeType: "string", runtimePort: "in_0", access: "tree", hidden: true },
      count: { type: NumberValue, runtimeType: "number", runtimePort: "in_1", access: "tree", labelEn: "Count" },
      input2: { type: NumberValue, runtimeType: "number", runtimePort: "in_2", access: "item", hidden: true },
      prefix: { type: StringValue, runtimeType: "string", runtimePort: "in_3", access: "tree", labelEn: "Prefix" },
    },
    outputs: {
      output0: { type: NumberList, runtimeType: "number", runtimePort: "out_0", access: "list", hidden: true },
      names: { type: StringList, runtimeType: "string", runtimePort: "out_1", access: "list", labelEn: "Names" },
      output2: { type: NumberValue, runtimeType: "number", runtimePort: "out_2", access: "item" },
    },
  },
  ({ input0, count, input2, prefix }) => {
    // @scene-id node-1781228027586-5q6fd
    const numberValue1 = numberValue({})

    // @scene-id node-1781228027586-k6rb8
    const numberValue2 = numberValue({
        "$params": {"value":1},
      })

    // @scene-id node-1781228027586-tj36h
    const typeNumber3 = typeNumber({
        "value": count,
      })

    // @scene-id node-1781228027586-z6i3e
    const basicMathOp4 = basicMathOp({
        "$params": {"op":"-"},
        "op": input0,
        "b": numberValue2.value,
        "a": typeNumber3.value,
      })

    // @scene-id node-1781228027586-u2z2j
    const stringValue5 = stringValue({
        "value": prefix,
      })

    // @scene-id node-1781228027586-b06qf
    const rangeList6 = rangeList({
        "step": input2,
        "start": numberValue1.value,
        "end": basicMathOp4.result,
        "prefix": stringValue5.value,
      })
    return {
      output0: rangeList6.list,
      names: rangeList6.stringList,
      output2: rangeList6.count,
    }
  },
)

// @scene-id definition:batteries.groups.scene.farmland-regions.farmland-regions.nested.3
const farmlandRegionsObjectAssetName = defineGroup(
  {
    id: "scene.group.scene.farmland-regions.farmland-regions.nested.3",
    version: "1.0.0",
    inputs: {
      input0: { type: Scene, runtimeType: "scene", runtimePort: "in_0", access: "item" },
      input1: { type: StringValue, runtimeType: "string", runtimePort: "in_1", access: "tree" },
    },
    outputs: {
      output0: { type: Scene, runtimeType: "scene", runtimePort: "out_0", access: "item" },
    },
  },
  ({ input0, input1 }) => {
    // @scene-id node-1781228415965-daiv9
    const textPanel1 = textPanel({
        "$params": {"text":"asset_name","_nodeWidth":180,"_nodeHeight":67},
      })

    // @scene-id node-1781228415965-6bydv
    const textPanel2 = textPanel({
        "$params": {"text":"asset_type","_nodeWidth":181,"_nodeHeight":60},
      })

    // @scene-id node-1781228415965-u3fw3
    const textPanel3 = textPanel({
        "$params": {"text":"object","_nodeWidth":181,"_nodeHeight":60},
      })

    // @scene-id node-1781228415965-p9z3l
    const stringValue4 = stringValue({
        "value": input1,
      })

    // @scene-id node-1781228415965-iwnba
    const sceneSetAttribute5 = sceneSetAttribute({
        "scene": input0,
        "key": textPanel1.output,
        "value": stringValue4.value,
      })

    // @scene-id node-1781228415965-flno1
    const sceneSetAttribute6 = sceneSetAttribute({
        "scene": sceneSetAttribute5.scene,
        "key": textPanel2.output,
        "value": textPanel3.output,
      })
    return {
      output0: sceneSetAttribute6.scene,
    }
  },
)

// @scene-id definition:batteries.groups.scene.farmland-regions.farmland-regions
export const farmlandRegions = defineGroup(
  {
    id: "scene.group.scene.farmland-regions.farmland-regions",
    version: "1.0.0",
    inputs: {
      input0: { type: Scene, runtimeType: "scene", runtimePort: "in_0", access: "tree", order: 0 },
      input1: { type: NumberValue, runtimeType: "number", runtimePort: "in_6", access: "item", hidden: true, order: 1 },
      input2: { type: NumberValue, runtimeType: "number", runtimePort: "in_7", access: "item", hidden: true, order: 2 },
      input3: { type: StringValue, runtimeType: "string", runtimePort: "in_8", access: "item", hidden: true, order: 3 },
      input4: { type: StringValue, runtimeType: "string", runtimePort: "in_9", access: "item", hidden: true, order: 4 },
      input5: { type: NumberList, runtimeType: "number", runtimePort: "in_10", access: "list", hidden: true, order: 5 },
      input6: { type: StringValue, runtimeType: "string", runtimePort: "in_11", access: "item", hidden: true, order: 6 },
      input7: { type: StringValue, runtimeType: "string", runtimePort: "in_12", access: "item", hidden: true, order: 7 },
      input8: { type: NumberList, runtimeType: "number", runtimePort: "in_13", access: "list", hidden: true, order: 8 },
      farmlandAsset: { type: StringValue, runtimeType: "string", runtimePort: "in_2", access: "tree", order: 25, labelEn: "FarmlandAsset" },
      input10: { type: NumberValue, runtimeType: "number", runtimePort: "in_14", hidden: true, order: 9 },
      input11: { type: NumberValue, runtimeType: "number", runtimePort: "in_15", hidden: true, order: 10 },
      input12: { type: NumberValue, runtimeType: "number", runtimePort: "in_16", hidden: true, order: 11 },
      input13: { type: NumberValue, runtimeType: "number", runtimePort: "in_17", hidden: true, order: 12 },
      expectedFarmland: { type: NumberValue, runtimeType: "number", runtimePort: "in_1", order: 13, labelEn: "ExpectedFarmland" },
      input15: { type: NumberValue, runtimeType: "number", runtimePort: "in_18", hidden: true, order: 14 },
      input16: { type: NumberValue, runtimeType: "number", runtimePort: "in_19", hidden: true, order: 15 },
      input17: { type: NumberValue, runtimeType: "number", runtimePort: "in_20", hidden: true, order: 16 },
      input18: { type: NumberValue, runtimeType: "number", runtimePort: "in_21", hidden: true, order: 17 },
      input19: { type: Grid, runtimeType: "grid", runtimePort: "in_22", access: "item", hidden: true, order: 18 },
      input20: { type: StringValue, runtimeType: "string", runtimePort: "in_23", hidden: true, order: 19 },
      cropDensity: { type: NumberValue, runtimeType: "number", runtimePort: "in_5", order: 20, labelEn: "CropDensity" },
      input22: { type: NumberValue, runtimeType: "number", runtimePort: "in_24", hidden: true, order: 21 },
      input23: { type: StringValue, runtimeType: "string", runtimePort: "in_25", access: "item", hidden: true, order: 22 },
      input24: { type: StringValue, runtimeType: "string", runtimePort: "in_26", access: "item", hidden: true, order: 23 },
      cropAsset: { type: StringValue, runtimeType: "string", runtimePort: "in_3", access: "tree", order: 24, labelEn: "CropAsset" },
      input26: { type: NumberValue, runtimeType: "number", runtimePort: "in_27", access: "item", hidden: true, order: 26 },
      input27: { type: StringValue, runtimeType: "string", runtimePort: "in_28", access: "item", hidden: true, order: 27 },
      seed: { type: NumberValue, runtimeType: "number", runtimePort: "in_4", access: "tree", order: 28, labelEn: "Seed" },
    },
    outputs: {
      scene: { type: Scene, runtimeType: "scene", runtimePort: "out_0", access: "tree", labelEn: "Scene" },
      farmland: { type: Scene, runtimeType: "scene", runtimePort: "out_2", access: "tree", labelEn: "Farmland" },
      rest: { type: Scene, runtimeType: "scene", runtimePort: "out_1", access: "tree", labelEn: "Rest" },
      farmlandPath: { type: StringValue, runtimeType: "string", runtimePort: "out_3", access: "tree", labelEn: "FarmlandPath" },
      restPath: { type: StringValue, runtimeType: "string", runtimePort: "out_4", access: "tree", labelEn: "RestPath" },
    },
  },
  ({ input0, input1, input2, input3, input4, input5, input6, input7, input8, farmlandAsset, input10, input11, input12, input13, expectedFarmland, input15, input16, input17, input18, input19, input20, cropDensity, input22, input23, input24, cropAsset, input26, input27, seed }) => {
    // @scene-id node-1781197652570-u6l7n
    const scenePassthrough1 = scenePassthrough({
        "scene": input0,
      })

    // @scene-id node-1781197652572-kgyv3
    const nodeExplode2 = nodeExplode({
        "scene": scenePassthrough1.scene,
      })

    // @scene-id node-1781197652573-y8oke
    const rectangularGrid3 = rectangularGrid({
        "fillValue": input1,
        "width": nodeExplode2.width,
        "height": nodeExplode2.height,
      })

    // @scene-id node-1781197652574-u9cy1
    const voxelSlice4 = voxelSlice({
        "z": input2,
        "voxels": nodeExplode2.voxels,
        "grid": rectangularGrid3.grid,
      })

    // @scene-id node-1781197652577-n6ad9
    const textPanel5 = textPanel({
        "$params": {"text":"farmland_","_nodeWidth":172,"_nodeHeight":69},
      })

    // @scene-id node-1781197652589-v0y1l
    const textPanel6 = textPanel({
        "$params": {"text":"rest","_nodeWidth":172,"_nodeHeight":69},
      })

    // @scene-id node-1781227638933
    const numberValue7 = numberValue({
        "$params": {"value":0.5,"min":0,"max":100,"precision":2},
      })

    // @scene-id node-1781228027583-u8w7g
    const textPanel8 = textPanel({
        "$params": {"text":"crop_","_nodeWidth":172,"_nodeHeight":69},
      })

    // @scene-id node-1781229362322-7hjfa
    const numberValue9 = numberValue({
        "$params": {"value":1,"min":0,"max":10,"precision":0},
      })

    // @scene-id node-1781229362325-h19q1
    const numberValue10 = numberValue({
        "$params": {"value":1,"min":0,"max":10,"precision":0},
      })

    // @scene-id node-1781229362327-i1ut9
    const rangeList11 = rangeList({
        "step": input26,
        "prefix": input27,
        "start": numberValue9.value,
        "end": numberValue10.value,
      })

    // @scene-id node-1781238748621
    const multiSeed12 = multiSeed({
        "seed": seed,
        "shape": voxelSlice4.slice,
      })

    // @scene-id node-1781198583820
    const algRandomRectZoneGen13 = algRandomRectZoneGen({
        "targetValue": input13,
        "count": expectedFarmland,
        "minSize": input15,
        "maxSize": input16,
        "minDistance": input17,
        "dispersion": input18,
        "grid": voxelSlice4.slice,
        "seed": multiSeed12.seed,
      })

    // @scene-id node-1781197652590-lsxxr
    const algRegionUnionAll14 = algRegionUnionAll({
        "regions": algRandomRectZoneGen13.outputGridList,
      })

    // @scene-id node-1781197652588-364dv
    const algRegionSubtract15 = algRegionSubtract({
        "a": voxelSlice4.slice,
        "b": algRegionUnionAll14.region,
      })

    // @scene-id node-1781197652588-axqqs
    const gridSceneNode16 = gridSceneNode({
        "schema": input6,
        "token": input7,
        "zRange": input8,
        "grid": algRegionSubtract15.region,
        "name": textPanel6.output,
      })

    // @scene-id group_1781197652579_jo9tg
    const farmlandRegionsMultiNames17 = farmlandRegionsMultiNames({
        "prefix": textPanel5.output,
        "count": algRandomRectZoneGen13.placedCount,
      })

    // @scene-id node-1781197652578-bz059
    const gridSceneNode18 = gridSceneNode({
        "schema": input3,
        "token": input4,
        "zRange": input5,
        "name": farmlandRegionsMultiNames17.names,
        "grid": algRandomRectZoneGen13.outputGridList,
      })

    // @scene-id group_1781197652580_nxnc7
    const farmlandRegionsTileAssetName19 = farmlandRegionsTileAssetName({
        "input1": farmlandAsset,
        "input0": gridSceneNode18.scene,
      })

    // @scene-id node-1781198555148
    const algRegionGridSplit20 = algRegionGridSplit({
        "cellWidth": input10,
        "cellHeight": input11,
        "gapWidth": input12,
        "region": algRandomRectZoneGen13.outputGridList,
        "seed": multiSeed12.seed,
      })

    // @scene-id node-1781198887922
    const algRegionRandomFill21 = algRegionRandomFill({
        "edge": input19,
        "mode": input20,
        "density": cropDensity,
        "count": input22,
        "region": algRegionGridSplit20.partition,
        "seed": multiSeed12.seed,
      })

    // @scene-id node-1781229007269-jdlqo
    const algRegionUnionAll22 = algRegionUnionAll({
        "regions": algRegionRandomFill21.region,
      })

    // @scene-id node-1781227617644
    const algField2points23 = algField2points({
        "threshold": numberValue7.value,
        "field": algRegionUnionAll22.region,
      })

    // @scene-id group_1781228027586_0gs0u
    const farmlandRegionsMultiNames224 = farmlandRegionsMultiNames2({
        "prefix": textPanel8.output,
        "count": algField2points23.count,
      })

    // @scene-id node-1781227700012-i28xi
    const gridSceneNode25 = gridSceneNode({
        "schema": input23,
        "token": input24,
        "name": farmlandRegionsMultiNames224.names,
        "grid": algField2points23.points,
        "zRange": rangeList11.list,
      })

    // @scene-id group_1781228415965_x0mbi
    const farmlandRegionsObjectAssetName26 = farmlandRegionsObjectAssetName({
        "input1": cropAsset,
        "input0": gridSceneNode25.scene,
      })

    // @scene-id node-1781228108726-86fy3
    const addSceneChildren27 = addSceneChildren({
        "scene": farmlandRegionsTileAssetName19.output0,
        "nodes": farmlandRegionsObjectAssetName26.output0,
      })

    // @scene-id node-1781197652582-og2zp
    const addSceneChildren28 = addSceneChildren({
        "scene": scenePassthrough1.scene,
        "nodes": addSceneChildren27.scene,
      })

    // @scene-id node-1781197652585-0anhx
    const addSceneChildren29 = addSceneChildren({
        "scene": addSceneChildren28.scene,
        "nodes": gridSceneNode16.scene,
      })

    // @scene-id node-1781197652583-r88be
    const sceneMergeSubtrees30 = sceneMergeSubtrees({
        "scenes": addSceneChildren29.scene,
      })

    // @scene-id node-1781197652584-epxyg
    const sceneFocusPath31 = sceneFocusPath({
        "path": addSceneChildren28.childPaths,
        "scene": sceneMergeSubtrees30.scene,
      })

    // @scene-id node-1781197652585-59jqr
    const scenePassthrough32 = scenePassthrough({
        "scene": sceneMergeSubtrees30.scene,
      })

    // @scene-id node-1781197652586-g4e8u
    const sceneFocusPath33 = sceneFocusPath({
        "path": addSceneChildren29.childPaths,
        "scene": sceneMergeSubtrees30.scene,
      })

    // @scene-id node-1781197652586-9rr4k
    const scenePassthrough34 = scenePassthrough({
        "scene": sceneFocusPath31.scene,
      })

    // @scene-id node-1781197652587-jxcnx
    const scenePassthrough35 = scenePassthrough({
        "scene": sceneFocusPath33.scene,
      })

    // @scene-id node-1781238938889
    const stringValue36 = stringValue({
        "value": addSceneChildren28.childPaths,
      })

    // @scene-id node-1781238956734-et1ai
    const stringValue37 = stringValue({
        "value": addSceneChildren29.childPaths,
      })
    return {
      scene: scenePassthrough32.scene,
      farmland: scenePassthrough34.scene,
      rest: scenePassthrough35.scene,
      farmlandPath: stringValue36.value,
      restPath: stringValue37.value,
    }
  },
)
