// Generated by scripts/generate-native-group-definitions.mts.
// JSON parity oracle only: batteries/templates/scene/PickOneBuilding/PickOneBuilding.json
// @scene-id definition:batteries.templates.scene.pick-one-building.pick-one-building.nested.0
const pickOneBuildingObjectAssetName = defineGroup(
  {
    id: "scene.template.pick-one-building.nested.0",
    version: "1.0.0",
    inputs: {
      input0: { type: Scene, runtimeType: "scene", runtimePort: "in_0", access: "item" },
      input1: { type: StringValue, runtimeType: "string", runtimePort: "in_1", access: "tree" },
    },
    outputs: {
      output0: { type: Scene, runtimeType: "scene", runtimePort: "out_0", access: "item" },
    },
  },
  ({ input0, input1 }) => {
    // @scene-id node-1781805836833-u0n1m
    const textPanel1 = textPanel({
        "$params": {"text":"asset_name","_nodeWidth":180,"_nodeHeight":67},
      })

    // @scene-id node-1781805836833-h5dc1
    const textPanel2 = textPanel({
        "$params": {"text":"asset_type","_nodeWidth":181,"_nodeHeight":60},
      })

    // @scene-id node-1781805836833-xzhe4
    const textPanel3 = textPanel({
        "$params": {"text":"object","_nodeWidth":181,"_nodeHeight":60},
      })

    // @scene-id node-1781805836833-4mlss
    const stringValue4 = stringValue({
        "value": input1,
      })

    // @scene-id node-1781805836833-3ffrb
    const sceneSetAttribute5 = sceneSetAttribute({
        "scene": input0,
        "key": textPanel1.output,
        "value": stringValue4.value,
      })

    // @scene-id node-1781805836833-g4ali
    const sceneSetAttribute6 = sceneSetAttribute({
        "scene": sceneSetAttribute5.scene,
        "key": textPanel2.output,
        "value": textPanel3.output,
      })
    return {
      output0: sceneSetAttribute6.scene,
    }
  },
)

// @scene-id definition:batteries.templates.scene.pick-one-building.pick-one-building
export const pickOneBuilding = defineGroup(
  {
    id: "scene.template.pick-one-building",
    version: "1.0.0",
    inputs: {
      point: { type: Point2d, runtimeType: "point2d", runtimePort: "in_3", access: "item", order: 1, labelEn: "Point" },
      areaWidth: { type: NumberValue, runtimeType: "number", runtimePort: "in_5", hidden: false, order: 2, labelEn: "AreaWidth" },
      areaHeight: { type: NumberValue, runtimeType: "number", runtimePort: "in_6", hidden: false, order: 3, labelEn: "AreaHeight" },
      scene: { type: Scene, runtimeType: "scene", runtimePort: "in_1", access: "tree", order: 0, labelEn: "Scene" },
      input4: { type: NumberValue, runtimeType: "number", runtimePort: "in_7", access: "item", hidden: true, order: 4 },
      input5: { type: NumberValue, runtimeType: "number", runtimePort: "in_8", access: "item", hidden: true, order: 5 },
      input6: { type: StringValue, runtimeType: "string", runtimePort: "in_9", access: "item", hidden: true, order: 6 },
      input7: { type: StringValue, runtimeType: "string", runtimePort: "in_10", access: "item", hidden: true, order: 7 },
      input8: { type: NumberList, runtimeType: "number", runtimePort: "in_11", access: "list", hidden: true, order: 8 },
      buildingName: { type: StringValue, runtimeType: "string", runtimePort: "in_0", access: "item", order: 10, labelEn: "BuildingName" },
      input10: { type: StringValue, runtimeType: "string", runtimePort: "in_12", access: "item", hidden: true, order: 11 },
      input11: { type: StringValue, runtimeType: "string", runtimePort: "in_13", access: "item", hidden: true, order: 12 },
      buildingAsset: { type: StringValue, runtimeType: "string", runtimePort: "in_4", access: "tree", order: 13, labelEn: "BuildingAsset" },
      input13: { type: StringValue, runtimeType: "string", runtimePort: "in_15", access: "tree", hidden: true, order: 14 },
      buildingHeight: { type: NumberValue, runtimeType: "number", runtimePort: "in_2", access: "tree", order: 9, labelEn: "BuildingHeight" },
      input15: { type: StringValue, runtimeType: "string", runtimePort: "in_16", access: "tree", hidden: true, order: 15 },
      input16: { type: NumberValue, runtimeType: "number", runtimePort: "in_17", access: "item", hidden: true, order: 16 },
      input17: { type: StringValue, runtimeType: "string", runtimePort: "in_18", access: "item", hidden: true, order: 17 },
      input18: { type: NumberValue, runtimeType: "number", runtimePort: "in_14", hidden: true, order: 18 },
    },
    outputs: {
      building: { type: Scene, runtimeType: "scene", runtimePort: "out_1", access: "tree", order: 1, labelEn: "Building" },
      scene: { type: Scene, runtimeType: "scene", runtimePort: "out_0", access: "tree", order: 0, labelEn: "Scene" },
      rest: { type: Scene, runtimeType: "scene", runtimePort: "out_2", access: "tree", order: 3, labelEn: "Rest" },
      buildingPath: { type: StringValue, runtimeType: "string", runtimePort: "out_3", access: "tree", order: 2, labelEn: "BuildingPath" },
      restPath: { type: StringValue, runtimeType: "string", runtimePort: "out_4", access: "tree", order: 4, labelEn: "RestPath" },
    },
  },
  ({ point, areaWidth, areaHeight, scene, input4, input5, input6, input7, input8, buildingName, input10, input11, buildingAsset, input13, buildingHeight, input15, input16, input17, input18 }) => {
    // @scene-id node-1781805836833-fu5ot
    const scenePassthrough1 = scenePassthrough({
        "scene": scene,
      })

    // @scene-id node-1781805836833-iy741
    const nodeExplode2 = nodeExplode({
        "scene": scenePassthrough1.scene,
      })

    // @scene-id node-1781805836833-p7d6q
    const rectangularGrid3 = rectangularGrid({
        "fillValue": input4,
        "width": nodeExplode2.width,
        "height": nodeExplode2.height,
      })

    // @scene-id node-1781805836833-whm0s
    const voxelSlice4 = voxelSlice({
        "z": input5,
        "voxels": nodeExplode2.voxels,
        "grid": rectangularGrid3.grid,
      })

    // @scene-id node-1781805836833-hkup3
    const algPoint2rect5 = algPoint2rect({
        "point": point,
        "width": areaWidth,
        "height": areaHeight,
        "region": voxelSlice4.slice,
      })

    // @scene-id node-1781805836833-c3stp
    const textPanel6 = textPanel({
        "$params": {"text":"rest","_nodeWidth":180,"_nodeHeight":60},
      })

    // @scene-id node-1781805836833-je2sr
    const algRegionBlockyCarve7 = algRegionBlockyCarve({
        "seed": input18,
        "region": algPoint2rect5.outputGrid,
      })

    // @scene-id node-1781805836833-kkd2s
    const algRegionSubtract8 = algRegionSubtract({
        "a": voxelSlice4.slice,
        "b": algRegionBlockyCarve7.region,
      })

    // @scene-id node-1781805836833-svucq
    const gridSceneNode9 = gridSceneNode({
        "schema": input6,
        "token": input7,
        "zRange": input8,
        "grid": algRegionSubtract8.region,
        "name": textPanel6.output,
      })

    // @scene-id node-1781805995994
    const numberValue10 = numberValue({
        "$params": {"value":1},
      })

    // @scene-id node-1781806015145
    const basicMathOp11 = basicMathOp({
        "$params": {"op":"+"},
        "op": input13,
        "b": numberValue10.value,
        "a": voxelSlice4.z,
      })

    // @scene-id node-1781806132314
    const typeNumber12 = typeNumber({
        "value": buildingHeight,
      })

    // @scene-id node-1781806142682
    const basicMathOp13 = basicMathOp({
        "$params": {"op":"+"},
        "op": input15,
        "b": typeNumber12.value,
        "a": voxelSlice4.z,
      })

    // @scene-id node-1781806760754
    const rangeList14 = rangeList({
        "step": input16,
        "prefix": input17,
        "start": basicMathOp11.result,
        "end": basicMathOp13.result,
      })

    // @scene-id node-1781805836833-foby6
    const gridSceneNode15 = gridSceneNode({
        "name": buildingName,
        "schema": input10,
        "token": input11,
        "grid": algRegionBlockyCarve7.region,
        "zRange": rangeList14.list,
      })

    // @scene-id group_1781805836833_zt08h
    const pickOneBuildingObjectAssetName16 = pickOneBuildingObjectAssetName({
        "input1": buildingAsset,
        "input0": gridSceneNode15.scene,
      })

    // @scene-id node-1781805836833-f33b0
    const addSceneChildren17 = addSceneChildren({
        "nodes": pickOneBuildingObjectAssetName16.output0,
        "scene": scenePassthrough1.scene,
      })

    // @scene-id node-1781805836833-mb7dn
    const addSceneChildren18 = addSceneChildren({
        "scene": addSceneChildren17.scene,
        "nodes": gridSceneNode9.scene,
      })

    // @scene-id node-1781805836833-e7154
    const sceneMergeSubtrees19 = sceneMergeSubtrees({
        "scenes": addSceneChildren18.scene,
      })

    // @scene-id node-1781805836833-4ykoo
    const sceneFocusPath20 = sceneFocusPath({
        "scene": sceneMergeSubtrees19.scene,
        "path": addSceneChildren17.childPaths,
      })

    // @scene-id node-1781805836833-ryf07
    const scenePassthrough21 = scenePassthrough({
        "scene": sceneFocusPath20.scene,
      })

    // @scene-id node-1781805836833-do9u6
    const scenePassthrough22 = scenePassthrough({
        "scene": sceneMergeSubtrees19.scene,
      })

    // @scene-id node-1781805836833-gc0m6
    const sceneFocusPath23 = sceneFocusPath({
        "path": addSceneChildren18.childPaths,
        "scene": sceneMergeSubtrees19.scene,
      })

    // @scene-id node-1781805836833-vvw0b
    const scenePassthrough24 = scenePassthrough({
        "scene": sceneFocusPath23.scene,
      })

    // @scene-id node-1781805836833-94hcq
    const stringValue25 = stringValue({
        "value": addSceneChildren17.childPaths,
      })

    // @scene-id node-1781805836833-iuc47
    const stringValue26 = stringValue({
        "value": addSceneChildren18.childPaths,
      })
    return {
      building: scenePassthrough21.scene,
      scene: scenePassthrough22.scene,
      rest: scenePassthrough24.scene,
      buildingPath: stringValue25.value,
      restPath: stringValue26.value,
    }
  },
)
