import type { AudioNameSource } from './humanSearchTypes.ts';

const CATEGORY_LABELS: Record<string, string> = {
  '1_ui': '界面',
  '1_ui界面': '界面',
  '2_character': '角色',
  '2_character角色': '角色',
  '3_combat': '战斗',
  '3_combat战斗': '战斗',
  '4_magic': '魔法',
  '4_magic魔法': '魔法',
  '5_vehicle': '载具',
  '5_vehicle载具': '载具',
  '6_item': '道具',
  '6_item道具': '道具',
  '7_ambient': '环境',
  '7_ambient环境': '环境',
  '8_casual': '休闲玩法',
  '8_casual休闲': '休闲玩法',
  '9_sports': '体育',
  '9_sports体育': '体育',
  '11_stinger': '提示短音',
  '11_stinger提示短音': '提示短音',
};

const CONTEXT_LABELS: Record<string, string> = {
  ui: '界面',
  btn: '按键',
  casual: '休闲',
  common: '通用',
  fantasy: '奇幻',
  horror: '恐怖',
  hud: '抬头显示',
  scifi: '科幻',
  sci_fi: '科幻',
  character: '角色',
  cloth: '布料',
  footstep: '脚步',
  footsteps: '脚步',
  monster: '怪物',
  voice: '人声',
  combat: '战斗',
  firearms: '枪械',
  melee: '近战',
  scifi_weapon: '科幻武器',
  throwable: '投掷物',
  magic: '魔法',
  buff: '增益',
  debuff: '减益',
  fire: '火焰',
  ice: '冰霜',
  lightning: '雷电',
  teleport: '传送',
  water: '水系',
  wind: '风系',
  vehicle: '载具',
  air: '空中载具',
  land: '陆地载具',
  machinery: '机械',
  item: '道具',
  consumable: '消耗品',
  container: '容器',
  currency: '货币',
  utility: '工具',
  ambient: '环境',
  nature: '自然',
  urban: '城市',
  combo: '连击',
  match: '匹配玩法',
  timer: '计时',
  sports: '体育',
  ball: '球类',
  stadium: '场馆',
  stinger: '提示短音',
  countdown: '倒计时',
  fail: '失败',
  levelup: '升级',
  level_up: '升级',
  loot: '战利品',
  mission: '任务',
  victory: '胜利',
};

const PHRASE_LABELS: Record<string, string> = {
  data_transfer: '数据传输',
  page_turn: '翻页',
  mechanical_joint: '机械关节活动',
  charge_jump: '蓄力跳跃',
  death_scream: '死亡惨叫',
  revive_breath: '复活喘息',
  shell_drop: '弹壳落地',
  shotgun_shell: '霰弹枪弹壳',
  impact_blade: '刀刃命中',
  impact_shield: '护盾受击',
  impact_smash: '重砸命中',
  swing_heavy_weapon: '重型武器挥动',
  swing_long_weapon: '长武器挥动',
  swing_short_weapon: '短武器挥动',
  fire_burst_fire: '枪械连发',
  fire_single: '枪械单发',
  magic_fire_burst: '火焰魔法爆发',
  magic_fire_loop: '火焰魔法循环',
  magic_fire_single: '火焰魔法单发',
  magic_ice_burst: '冰霜魔法爆发',
  magic_ice_loop: '冰霜魔法循环',
  magic_ice_single: '冰霜魔法单发',
  magic_lightning_burst: '雷电魔法爆发',
  magic_lightning_loop: '雷电魔法循环',
  magic_lightning_single: '雷电魔法单发',
  magic_water_burst: '水系魔法爆发',
  magic_water_loop: '水系魔法循环',
  magic_water_single: '水系魔法单发',
  magic_wind_burst: '风系魔法爆发',
  magic_wind_loop: '风系魔法循环',
  magic_wind_single: '风系魔法单发',
  ambient_city_traffic: '城市交通环境',
  ambient_crowd_market: '集市人群环境',
  ambient_forest_day: '白昼森林环境',
  ambient_forest_night: '夜晚森林环境',
  ambient_rain_heavy: '大雨环境',
  ambient_rain_light: '小雨环境',
  ambient_thunder: '雷雨环境',
  ambient_wind_heavy: '强风环境',
  ambient_wind_light: '微风环境',
  ui_confirm: '界面确认',
  ui_cancel: '界面取消',
  ui_error: '界面错误',
  ui_hover: '界面悬停',
  ui_open: '界面打开',
  ui_close: '界面关闭',
  ui_notification: '界面通知',
};

const TOKEN_LABELS: Record<string, string> = {
  ui: '界面',
  hud: '抬头显示',
  button: '按键',
  click: '点击',
  confirm: '确认',
  cancel: '取消',
  accept: '接受',
  decline: '拒绝',
  back: '返回',
  select: '选择',
  submit: '提交',
  error: '错误',
  warning: '警告',
  alert: '警报',
  notification: '通知',
  popup: '弹窗',
  menu: '菜单',
  tab: '页签',
  toggle: '切换',
  switch: '开关',
  slider: '滑块',
  hover: '悬停',
  open: '打开',
  close: '关闭',
  expand: '展开',
  collapse: '收起',
  scroll: '滚动',
  type: '输入',
  typing: '打字',
  text: '文本',
  digital: '数字',
  analog: '模拟',
  data: '数据',
  transfer: '传输',
  loading: '加载',
  progress: '进度',
  acquire: '获得',
  quest: '任务',
  typewriter: '打字机',
  electronic: '电子',
  beep: '提示音',
  hologram: '全息投影',
  success: '成功',
  fail: '失败',
  failed: '失败',
  unlock: '解锁',
  locked: '锁定',
  reward: '奖励',
  achievement: '成就',
  level: '关卡',
  levelup: '升级',
  up: '提升',
  down: '下降',
  character: '角色',
  player: '玩家',
  human: '人物',
  action: '动作',
  creature: '生物',
  monster: '怪物',
  beast: '野兽',
  insect: '昆虫',
  roar: '咆哮',
  slime: '史莱姆',
  snarl: '低吼',
  male: '男性',
  female: '女性',
  child: '儿童',
  cloth: '布料',
  clothing: '衣物',
  leather: '皮革',
  armor: '盔甲',
  breath: '呼吸',
  breathe: '呼吸',
  gasp: '喘气',
  grunt: '闷哼',
  scream: '惨叫',
  shout: '喊叫',
  hurt: '受伤',
  pain: '疼痛',
  death: '死亡',
  revive: '复活',
  climb: '攀爬',
  pant: '喘息',
  exhale: '呼气',
  jump: '跳跃',
  takeoff: '起跳',
  land: '落地',
  landing: '落地',
  walk: '行走',
  walking: '行走',
  run: '跑步',
  running: '跑步',
  sprint: '冲刺',
  dodge: '闪避',
  roll: '翻滚',
  slide: '滑行',
  footstep: '脚步',
  footsteps: '脚步',
  carpet: '地毯',
  floor: '地板',
  tile: '瓷砖',
  combat: '战斗',
  attack: '攻击',
  hit: '命中',
  impact: '命中',
  strike: '打击',
  smash: '重砸',
  punch: '拳击',
  kick: '踢击',
  slap: '拍击',
  swing: '挥动',
  swish: '挥动',
  whoosh: '掠过',
  parry: '格挡',
  block: '格挡',
  shield: '护盾',
  blade: '刀刃',
  sword: '剑',
  knife: '刀',
  axe: '斧',
  spear: '长矛',
  bow: '弓',
  arrow: '箭',
  weapon: '武器',
  heavy: '重型',
  medium: '中型',
  light: '轻型',
  short: '短',
  long: '长',
  fast: '快速',
  slow: '缓慢',
  firearms: '枪械',
  gun: '枪械',
  gunfire: '枪声',
  pistol: '手枪',
  rifle: '步枪',
  shotgun: '霰弹枪',
  sniper: '狙击枪',
  machinegun: '机枪',
  fire: '开火',
  firing: '开火',
  shot: '射击',
  single: '单发',
  burst: '爆发',
  automatic: '自动射击',
  reload: '换弹',
  magazine: '弹匣',
  ammo: '弹药',
  bullet: '子弹',
  shell: '弹壳',
  empty: '空仓',
  drop: '落地',
  laser: '激光',
  plasma: '等离子',
  energy: '能量',
  beam: '光束',
  grenade: '手雷',
  bomb: '炸弹',
  explosion: '爆炸',
  explode: '爆炸',
  blast: '爆破',
  explosive: '炸药',
  firecracker: '爆竹',
  massive: '巨型',
  shockwave: '冲击波',
  throwable: '投掷物',
  shuriken: '手里剑',
  throw: '投掷',
  bounce: '弹跳',
  fuse: '引信',
  magic: '魔法',
  spell: '法术',
  cast: '施法',
  buff: '增益',
  debuff: '减益',
  curse: '诅咒',
  poison: '中毒',
  stun: '眩晕',
  heal: '治疗',
  healing: '治疗',
  power: '力量',
  boost: '强化',
  portal: '传送门',
  teleport: '传送',
  blink: '闪现',
  space: '空间',
  tear: '撕裂',
  summon: '召唤',
  charge: '蓄力',
  loop: '循环',
  start: '启动',
  stop: '停止',
  end: '结束',
  air: '空气',
  airflow: '气流',
  wind: '风',
  water: '水',
  ice: '冰',
  lightning: '雷电',
  electric: '电流',
  electricity: '电流',
  earth: '土地',
  ground: '地面',
  nature: '自然',
  grass: '草地',
  dirt: '泥土',
  soil: '土壤',
  sand: '沙地',
  snow: '雪地',
  stone: '石头',
  rock: '岩石',
  concrete: '混凝土',
  metal: '金属',
  wood: '木材',
  wooden: '木材',
  glass: '玻璃',
  flesh: '肉体',
  fabric: '布料',
  wet: '潮湿',
  mud: '泥地',
  gravel: '碎石',
  vehicle: '载具',
  car: '汽车',
  truck: '卡车',
  tank: '坦克',
  motorcycle: '摩托车',
  bike: '自行车',
  train: '火车',
  ship: '船',
  boat: '小船',
  aircraft: '飞行器',
  airplane: '飞机',
  helicopter: '直升机',
  jet: '喷气式',
  spaceship: '飞船',
  sedan: '轿车',
  brake: '刹车',
  collision: '碰撞',
  accelerate: '加速',
  idle: '怠速',
  pass: '掠过',
  engine: '引擎',
  motor: '马达',
  machinery: '机械',
  machine: '机器',
  mechanical: '机械',
  joint: '关节',
  hydraulic: '液压',
  gear: '齿轮',
  elevator: '电梯',
  item: '道具',
  pickup: '拾取',
  collect: '收集',
  coin: '金币',
  currency: '货币',
  gem: '宝石',
  key: '钥匙',
  potion: '药水',
  bandage: '绷带',
  food: '食物',
  bottle: '瓶子',
  chest: '宝箱',
  box: '箱子',
  bag: '袋子',
  container: '容器',
  battery: '电池',
  insert: '插入',
  map: '地图',
  paper: '纸',
  money: '钞票',
  door: '门',
  break: '破碎',
  broken: '破碎',
  shatter: '碎裂',
  ambient: '环境',
  bubble: '气泡',
  craft: '制作',
  spring: '弹簧',
  xylophone: '木琴',
  feather: '羽毛',
  heartbeat: '心跳',
  noise: '噪声',
  static: '静电噪声',
  piano: '钢琴',
  bass: '低音',
  violin: '小提琴',
  screech: '尖啸',
  forest: '森林',
  desert: '沙漠',
  sandstorm: '沙尘暴',
  rainy: '雨天',
  thunderstorm: '雷暴',
  jungle: '丛林',
  ocean: '海洋',
  river: '河流',
  rain: '雨',
  thunder: '雷声',
  storm: '风暴',
  city: '城市',
  background: '背景',
  distant: '远处',
  siren: '警笛',
  urban: '城区',
  traffic: '交通',
  crowd: '人群',
  market: '集市',
  room: '房间',
  cave: '洞穴',
  drip: '滴水',
  dungeon: '地牢',
  day: '白昼',
  night: '夜晚',
  horror: '恐怖',
  scary: '惊悚',
  ghost: '幽灵',
  casual: '休闲',
  match: '匹配',
  combo: '连击',
  do: '多音',
  re: '来音',
  mi: '咪音',
  fa: '发音',
  so: '索音',
  pop: '弹出',
  clear: '消除',
  timer: '计时',
  countdown: '倒计时',
  tick: '滴答',
  sports: '体育',
  ball: '球',
  basketball: '篮球',
  dribble: '运球',
  tennis: '网球',
  kickball: '踢球',
  bounceball: '球弹跳',
  stadium: '场馆',
  buzzer: '蜂鸣器',
  sneaker: '运动鞋',
  squeak: '摩擦声',
  whistle: '哨声',
  cheer: '欢呼',
  applause: '掌声',
  stinger: '提示短音',
  victory: '胜利',
  defeat: '失败',
  mission: '任务',
  complete: '完成',
  loot: '战利品',
  rare: '稀有',
  epic: '史诗',
  legendary: '传说',
  score: '得分',
  point: '得分',
  perfect: '完美',
  great: '优秀',
  good: '良好',
  miss: '失误',
  boss: '首领',
  small: '小',
  large: '大',
  low: '低',
  high: '高',
  soft: '柔和',
  hard: '强硬',
  bright: '明亮',
  dark: '黑暗',
  clean: '清晰',
  distorted: '失真',
  dry: '干声',
  reverb: '混响',
  tail: '尾响',
};

const NOTE_LABELS: Record<string, string> = {
  a: '拉',
  b: '西',
  c: '多',
  d: '来',
  e: '咪',
  f: '发',
  g: '索',
};

function unique(values: string[]): string[] {
  return [...new Set(values.filter(Boolean))];
}

function normalizedPath(value: string): string {
  let decoded = value;
  try {
    decoded = decodeURIComponent(value);
  } catch {
    // Keep malformed paths readable rather than failing the whole catalog.
  }
  return decoded
    .split(/[?#]/, 1)[0]
    .replace(/\\/g, '/')
    .toLowerCase();
}

function baseStem(value: string): string {
  const filename = normalizedPath(value).split('/').pop() ?? '';
  return filename
    .replace(/\.(wav|mp3|ogg|m4a)$/i, '')
    .replace(/_\d{2,3}$/i, '')
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '');
}

function pathContext(value: string): string[] {
  const segments = normalizedPath(value)
    .split('/')
    .map((segment) => segment.replace(/\.(wav|mp3|ogg|m4a)$/i, ''))
    .filter(Boolean);
  const category = segments.map((segment) => CATEGORY_LABELS[segment]).find(Boolean);
  const subfolderLabels = segments
    .slice(0, -1)
    .map((segment) => CONTEXT_LABELS[segment])
    .filter(Boolean);
  const subfolder = subfolderLabels[subfolderLabels.length - 1];
  return unique([category ?? '', subfolder ?? '']);
}

function instrumentName(stem: string): string | null {
  const match = /^(bianzhong|guqin)_(\d+)_([a-g])(?:\d+)?$/i.exec(stem);
  if (!match) return null;
  const instrument = match[1]?.toLowerCase() === 'bianzhong' ? '编钟' : '古琴';
  const group = match[2] ?? '';
  const note = NOTE_LABELS[match[3]?.toLowerCase() ?? ''] ?? '音符';
  return `${instrument}·第${group}组·${note}音`;
}

function translatedDetail(stem: string): string {
  const instrument = instrumentName(stem);
  if (instrument) return instrument;
  if (PHRASE_LABELS[stem]) return PHRASE_LABELS[stem];

  const combo = /^x(\d+)$/i.exec(stem);
  if (combo) return `连击提示·${combo[1]}倍`;

  const translated = unique(
    stem
      .split('_')
      .map((token) => {
        if (/^\d+$/.test(token)) return token;
        return TOKEN_LABELS[token] ?? '';
      }),
  );
  return translated.join('·') || '未命名音效';
}

function cleanChineseDisplayName(value: string): string {
  return value
    .replace(/EMP/gi, '电磁脉冲')
    .replace(/Boss/gi, '首领')
    .replace(/PERFECT/gi, '完美')
    .replace(/GREAT/gi, '优秀')
    .replace(/GOOD/gi, '良好')
    .replace(/MISS/gi, '失误')
    .replace(/[A-Za-z]+/g, '自定义')
    .replace(/[_/]+/g, '·')
    .replace(/\s*·\s*/g, '·')
    .replace(/·{2,}/g, '·')
    .replace(/^·|·$/g, '')
    .trim();
}

export function localizeSupplierFamilyName(name: string): string {
  return cleanChineseDisplayName(name) || '未命名音效';
}

export function localizeFallbackFamilyName(path: string): string {
  const stem = baseStem(path);
  const detail = translatedDetail(stem);
  const context = pathContext(path);
  return unique([...context, ...detail.split('·')]).join('·') || '未命名音效';
}

export function localizedVariantName(familyName: string, index: number): string {
  return `${familyName}·变体${String(index + 1).padStart(2, '0')}`;
}

export function hasBareLatinName(value: string): boolean {
  return /[A-Za-z]/.test(value);
}

export const AUDIO_NAME_SOURCES: Record<AudioNameSource, string> = {
  supplier: '供应商标准名',
  rule: '自动中文名',
  original: '原始名称',
};
