import { describe, it, expect, beforeAll } from 'vitest'
import { mkdtempSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import type { FastifyInstance } from 'fastify'

// Phase 1 of the texture pipeline: the renderer matching pool (aliases-meta) must
// MERGE project-private (imported / cross-app-published) assets, not just the
// read-only base library — otherwise textures generated by the 2D app can never
// be matched onto scene voxels. Isolate writes in a throwaway project root.
const PNG_1x1 =
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg=='

interface AliasMeta {
  alias: string
  tileType?: string
  widthPx?: number
  heightPx?: number
}

let buildApp: () => Promise<FastifyInstance>

beforeAll(async () => {
  process.env.FORGEAX_PROJECT_ROOT = mkdtempSync(join(tmpdir(), 'wb-pool-'))
  ;({ buildApp } = await import('../src/main.js'))
})

// Import a 1x1 PNG, rename it to a full bracket-field alias, and move it to `raw`.
async function publishRawAlias(app: FastifyInstance, alias: string): Promise<string> {
  const imp = (
    await app.inject({ method: 'POST', url: '/api/v1/library/import', payload: { filename: 'seed.png', dataBase64: PNG_1x1 } })
  ).json()
  await app.inject({ method: 'PATCH', url: `/api/v1/library/private/${imp.id}`, payload: { alias } })
  await app.inject({ method: 'POST', url: `/api/v1/library/private/${imp.id}/move`, payload: { zone: 'raw' } })
  return imp.id as string
}

describe('aliases-meta matching pool merges private assets', () => {
  it('a private TILE alias enters the raw pool and binds to its autotile rule', async () => {
    const app = await buildApp()
    // field[4]=item-name=grassland, field[8]=type=common_16 (a vendored rule).
    const alias = '[]_[]_[]_[]_[grassland]_[]_[]_[]_[common_16]_[]_[]_[]_[].png'
    await publishRawAlias(app, alias)

    const pool = (await app.inject({ method: 'GET', url: '/api/v1/library/aliases-meta?zone=raw' })).json() as AliasMeta[]
    const hit = pool.find((m) => m.alias === alias)
    expect(hit, 'private tile should appear in the renderer matching pool').toBeDefined()
    expect(hit?.tileType).toBe('common_16')
    await app.close()
  })

  it('a private OBJECT alias enters the pool with NO tileType (cutout pool)', async () => {
    const app = await buildApp()
    // field[8]=抠图 (cutout) → object, not a tile, so no rule binding.
    const alias = '[]_[]_[]_[]_[wooden_barrel]_[]_[]_[]_[抠图]_[]_[]_[]_[].png'
    await publishRawAlias(app, alias)

    const pool = (await app.inject({ method: 'GET', url: '/api/v1/library/aliases-meta?zone=raw' })).json() as AliasMeta[]
    const hit = pool.find((m) => m.alias === alias)
    expect(hit, 'private object should appear in the pool').toBeDefined()
    expect(hit?.tileType).toBeUndefined()
    await app.close()
  })

  it('does not drop the base library aliases when merging', async () => {
    const app = await buildApp()
    const pool = (await app.inject({ method: 'GET', url: '/api/v1/library/aliases-meta?zone=raw' })).json() as AliasMeta[]
    // The built-in library ships many raw aliases; the merge must keep them.
    expect(pool.length).toBeGreaterThan(0)
    await app.close()
  })
})
