/** Auto-derived English display names for genre taxonomy (locale=en). */
export const GENRE_NAME_EN: Record<string, string> = {
  "rpg-jrpg": "JRPG",
  "rpg-crpg": "WRPG / CRPG",
  "rpg-arpg": "ARPG",
  "rpg-mmorpg": "MMORPG",
  "rpg-srpg": "SRPG / Tactical RPG",
  "rpg-gacha": "Gacha RPG",
  "rpg-open-world": "Open-world RPG",
  "rpg-roguelike": "Roguelike RPG",
  "rpg-wuxia": "Xianxia / Wuxia RPG",
  "rpg-soulslike": "Souls-like",
  "rpg-idle": "Idle RPG",
  "rpg-dungeon": "Dungeon crawler",
  "rpg-sandbox": "Sandbox RPG",
  "act-linear": "AAA linear action",
  "act-adventure": "Action-adventure",
  "act-2d-platformer": "2D platformer",
  "act-metroidvania": "Metroidvania",
  "act-beatup": "Beat 'em up",
  "act-character": "Character Action",
  "act-stealth": "Stealth action",
  "act-survival": "Survival action",
  "act-immersive-sim": "Immersive Sim",
  "act-musou": "Musou",
  "str-tbs": "Turn-based strategy",
  "str-rts": "RTS",
  "str-slg": "Slg",
  "str-tactics": "Tactics",
  "str-td": "Tower defense",
  "str-4x": "4x",
  "str-autobattle": "Auto battler",
  "str-moba": "MOBA",
  "str-grand": "Grand",
  "adv-vn": "VN",
  "adv-interactive": "Interactive",
  "adv-walking-sim": "Walking sim",
  "adv-text": "Text",
  "adv-pointclick": "Point-and-click adventure",
  "adv-puzzle": "Puzzle adventure",
  "adv-otome": "Otome",
  "adv-horror": "Horror",
  "adv-detective": "Detective",
  "adv-horror-vn": "Horror VN",
  "adv-raising": "Raising",
  "adv-life-sim": "Life Sim",
  "sim-life": "Life sim",
  "sim-tycoon": "Tycoon",
  "sim-raising": "Raising",
  "sim-sandbox": "Sandbox",
  "sim-survival": "Survival",
  "sim-social": "Social",
  "sim-dating": "Dating sim",
  "sim-creature": "Creature",
  "sim-colony": "Colony",
  "fps-story": "Story",
  "fps-tactical": "Tactical",
  "fps-br": "Battle royale",
  "fps-hero": "Hero",
  "tps-adventure": "Adventure",
  "fps-looter": "Looter",
  "stg-bullet": "Bullet",
  "fps-extraction": "Extraction",
  "puz-narrative": "Narrative",
  "puz-escape": "Escape",
  "puz-pure": "Pure",
  "puz-physics": "Physics",
  "puz-match": "Match-3 / Match",
  "spt-sim": "Sim",
  "spt-mgmt": "Mgmt",
  "race-sim": "Sim",
  "race-kart": "Kart",
  "spt-extreme": "Extreme",
  "spt-fighting": "Fighting",
  "card-ccg": "CCG/TCG",
  "card-dbg": "Dbg",
  "card-narrative": "Narrative",
  "card-boardgame": "Boardgame",
  "fgt-traditional": "Traditional",
  "fgt-platform": "Platform",
  "fgt-weapon": "Weapon",
  "fgt-anime": "Anime",
  "rhy-narrative": "Narrative",
  "rhy-idol": "Idol",
  "rhy-pure": "Pure",
  "rhy-action": "Action",
  "hor-survival": "Survival",
  "hor-psychological": "Psychological horror",
  "hor-chase": "Chase",
  "hor-coop": "Coop",
  "hor-cosmic": "Cosmic",
  "cas-party": "Party",
  "cas-puzzle": "Puzzle",
  "cas-hyper": "Hyper-casual",
  "cas-io": "IO",
  "cas-idle": "Idle",
  "cas-cozy": "Cozy",
  "srv-open": "Open",
  "srv-craft": "Craft",
  "srv-space": "Space",
  "srv-creative": "Creative",
  "misc-pokemon": "Pokemon",
  "misc-pinball": "Pinball",
  "misc-edu": "Edu",
  "misc-farm": "Farm",
  "misc-survivor": "Survivor",
  "puz-merge": "Merge / 2048",
  "puz-connect": "Connect",
  "puz-tetris": "Tetris",
  "puz-bubble": "Bubble Shooter",
  "puz-word": "Word",
  "cas-runner": "Runner",
  "cas-snake": "Snake",
  "cas-stack": "Stack",
  "cas-timing": "Timing",
  "cas-sling": "Sling",
  "cas-fishing": "Fishing",
  "cas-action": "Action",
  "cas-spot": "Spot",
};
