// Generated by scripts/generate-native-group-definitions.mts.
// JSON parity oracle only: batteries/templates/structures/indoor/RoomLayoutPlacer/RoomLayoutPlacer.json
// @scene-id definition:batteries.templates.structures.indoor.room-layout-placer.room-layout-placer.nested.0
const roomLayoutPlacerTemplateTileAssetName = defineGroup(
  {
    id: "scene.template.room-layout-placer.nested.0",
    version: "1.0.0",
    inputs: {
      input0: { type: Scene, runtimeType: "scene", runtimePort: "in_0", access: "item" },
      input1: { type: StringValue, runtimeType: "string", runtimePort: "in_1", access: "tree" },
    },
    outputs: {
      output0: { type: Scene, runtimeType: "scene", runtimePort: "out_0", access: "item" },
    },
  },
  ({ input0, input1 }) => {
    // @scene-id node-1790000000011-ptt9f
    const textPanel1 = textPanel({
        "$params": {"text":"asset_name","_nodeWidth":180,"_nodeHeight":67},
      })

    // @scene-id node-1790000000011-rm2fy
    const textPanel2 = textPanel({
        "$params": {"text":"asset_type","_nodeWidth":181,"_nodeHeight":60},
      })

    // @scene-id node-1790000000011-obfmb
    const textPanel3 = textPanel({
        "$params": {"text":"tile","_nodeWidth":181,"_nodeHeight":60},
      })

    // @scene-id node-1790000000011-94gxn
    const stringValue4 = stringValue({
        "value": input1,
      })

    // @scene-id node-1790000000011-4twly
    const sceneSetAttribute5 = sceneSetAttribute({
        "scene": input0,
        "key": textPanel1.output,
        "value": stringValue4.value,
      })

    // @scene-id node-1790000000011-0767k
    const sceneSetAttribute6 = sceneSetAttribute({
        "scene": sceneSetAttribute5.scene,
        "key": textPanel2.output,
        "value": textPanel3.output,
      })
    return {
      output0: sceneSetAttribute6.scene,
    }
  },
)

// @scene-id definition:batteries.templates.structures.indoor.room-layout-placer.room-layout-placer
export const roomLayoutPlacerTemplate = defineGroup(
  {
    id: "scene.template.room-layout-placer",
    version: "1.0.0",
    inputs: {
      scene: { type: Scene, runtimeType: "scene", runtimePort: "in_0", access: "tree", labelEn: "Scene" },
      assetName: { type: StringValue, runtimeType: "string", runtimePort: "in_1", labelEn: "AssetName" },
      seed: { type: NumberValue, runtimeType: "number", runtimePort: "in_2", access: "tree", labelEn: "Seed" },
      doorGrid: { type: Grid, runtimeType: "grid", runtimePort: "in_3", access: "item", labelEn: "DoorGrid" },
      furnitureList: { type: Any, runtimeType: "array", runtimePort: "in_4", access: "item", labelEn: "FurnitureList" },
      layoutMode: { type: StringValue, runtimeType: "string", runtimePort: "in_5", access: "item", labelEn: "LayoutMode" },
      layoutConfig: { type: StringValue, runtimeType: "string", runtimePort: "in_6", access: "item", labelEn: "LayoutConfig" },
      input7: { type: NumberValue, runtimeType: "number", runtimePort: "in_7", access: "item", hidden: true },
      input8: { type: NumberValue, runtimeType: "number", runtimePort: "in_8", access: "item", hidden: true },
      input9: { type: StringValue, runtimeType: "string", runtimePort: "in_9", access: "item", hidden: true },
      input10: { type: StringValue, runtimeType: "string", runtimePort: "in_10", access: "item", hidden: true },
      input11: { type: NumberList, runtimeType: "number", runtimePort: "in_11", access: "list", hidden: true },
    },
    outputs: {
      scene: { type: Scene, runtimeType: "scene", runtimePort: "out_0", access: "tree", order: 0, labelEn: "Scene" },
      furniture: { type: Scene, runtimeType: "scene", runtimePort: "out_1", access: "tree", order: 1, labelEn: "Furniture" },
      rest: { type: Scene, runtimeType: "scene", runtimePort: "out_2", access: "tree", order: 2, labelEn: "Rest" },
      furniturePath: { type: StringValue, runtimeType: "string", runtimePort: "out_3", access: "tree", order: 3, labelEn: "FurniturePath" },
      restPath: { type: StringValue, runtimeType: "string", runtimePort: "out_4", access: "tree", order: 4, labelEn: "RestPath" },
    },
  },
  ({ scene, assetName, seed, doorGrid, furnitureList, layoutMode, layoutConfig, input7, input8, input9, input10, input11 }) => {
    // @scene-id node-1790000000011-c6vfi
    const scenePassthrough1 = scenePassthrough({
        "scene": scene,
      })

    // @scene-id node-1790000000011-du9e8
    const nodeExplode2 = nodeExplode({
        "scene": scenePassthrough1.scene,
      })

    // @scene-id node-1790000000011-6viw4
    const rectangularGrid3 = rectangularGrid({
        "fillValue": input7,
        "width": nodeExplode2.width,
        "height": nodeExplode2.height,
      })

    // @scene-id node-1790000000011-kej41
    const voxelSlice4 = voxelSlice({
        "z": input8,
        "voxels": nodeExplode2.voxels,
        "grid": rectangularGrid3.grid,
      })

    // @scene-id node-1790000000011-k9f8t
    const multiSeed5 = multiSeed({
        "seed": seed,
        "shape": voxelSlice4.slice,
      })

    // @scene-id node-1790000000011-h4vj0
    const roomLayoutPlacer6 = roomLayoutPlacer({
        "doorGrid": doorGrid,
        "furnitureList": furnitureList,
        "layoutMode": layoutMode,
        "layoutConfig": layoutConfig,
        "roomGrid": voxelSlice4.slice,
        "seed": multiSeed5.seed,
      })

    // @scene-id node-1790000000011-slehw
    const gridSplitByValue7 = gridSplitByValue({
        "grid": roomLayoutPlacer6.outputGrid,
      })

    // @scene-id node-1790000000011-i7rtn
    const strToListBranches8 = strToListBranches({
        "str": assetName,
      })

    // @scene-id node-1790000000011-tkeb1
    const gridSceneNode9 = gridSceneNode({
        "schema": input9,
        "token": input10,
        "zRange": input11,
        "grid": gridSplitByValue7.grids,
        "name": strToListBranches8.items,
      })

    // @scene-id group_1790000000011_hg1xq
    const roomLayoutPlacerTemplateTileAssetName10 = roomLayoutPlacerTemplateTileAssetName({
        "input0": gridSceneNode9.scene,
        "input1": strToListBranches8.items,
      })

    // @scene-id node-1790000000011-3eptq
    const addSceneChildren11 = addSceneChildren({
        "nodes": roomLayoutPlacerTemplateTileAssetName10.output0,
        "scene": scenePassthrough1.scene,
      })

    // @scene-id node-1790000000011-7vrak
    const algRegionSubtract12 = algRegionSubtract({
        "a": voxelSlice4.slice,
        "b": roomLayoutPlacer6.outputGrid,
      })

    // @scene-id node-1790000000011-2kmi6
    const textPanel13 = textPanel({
        "$params": {"text":"rest","_nodeWidth":172,"_nodeHeight":69},
      })

    // @scene-id node-1790000000011-6ldzn
    const gridSceneNode14 = gridSceneNode({
        "grid": algRegionSubtract12.region,
        "name": textPanel13.output,
      })

    // @scene-id node-1790000000011-ynr0v
    const addSceneChildren15 = addSceneChildren({
        "scene": addSceneChildren11.scene,
        "nodes": gridSceneNode14.scene,
      })

    // @scene-id node-1790000000011-xykwm
    const sceneMergeSubtrees16 = sceneMergeSubtrees({
        "scenes": addSceneChildren15.scene,
      })

    // @scene-id node-1790000000011-9l2e4
    const sceneFocusPath17 = sceneFocusPath({
        "scene": sceneMergeSubtrees16.scene,
        "path": addSceneChildren11.childPaths,
      })

    // @scene-id node-1790000000011-7hkpo
    const sceneFocusPath18 = sceneFocusPath({
        "scene": sceneMergeSubtrees16.scene,
        "path": addSceneChildren15.childPaths,
      })

    // @scene-id node-1790000000011-g36ob
    const scenePassthrough19 = scenePassthrough({
        "scene": sceneMergeSubtrees16.scene,
      })

    // @scene-id node-1790000000011-xgreg
    const scenePassthrough20 = scenePassthrough({
        "scene": sceneFocusPath17.scene,
      })

    // @scene-id node-1790000000011-o1ju5
    const scenePassthrough21 = scenePassthrough({
        "scene": sceneFocusPath18.scene,
      })

    // @scene-id node-1790000000011-4djdc
    const stringValue22 = stringValue({
        "value": addSceneChildren11.childPaths,
      })

    // @scene-id node-1790000000011-4kbf3
    const stringValue23 = stringValue({
        "value": addSceneChildren15.childPaths,
      })
    return {
      scene: scenePassthrough19.scene,
      furniture: scenePassthrough20.scene,
      rest: scenePassthrough21.scene,
      furniturePath: stringValue22.value,
      restPath: stringValue23.value,
    }
  },
)
