// Generated by scripts/generate-native-group-definitions.mts.
// JSON parity oracle only: batteries/groups/scene/MultiNames/MultiNames.json
// @scene-id definition:batteries.groups.scene.multi-names.multi-names
export const multiNames = defineGroup(
  {
    id: "scene.group.scene.multi-names.multi-names",
    version: "1.0.0",
    inputs: {
      op: { type: StringValue, runtimeType: "string", runtimePort: "in_0", hidden: true, label: "运算", labelEn: "Op" },
      count: { type: NumberValue, runtimeType: "number", runtimePort: "in_1", label: "值", labelEn: "Count" },
      step: { type: NumberValue, runtimeType: "number", runtimePort: "in_2", hidden: true, label: "步长", labelEn: "Step" },
      prefix: { type: StringValue, runtimeType: "string", runtimePort: "in_3", label: "值", labelEn: "Prefix" },
    },
    outputs: {
      list: { type: NumberValue, runtimeType: "number", runtimePort: "out_0", hidden: true, label: "数列", labelEn: "List" },
      names: { type: StringValue, runtimeType: "string", runtimePort: "out_1", label: "文本列", labelEn: "Names" },
      count: { type: NumberValue, runtimeType: "number", runtimePort: "out_2", label: "数量", labelEn: "Count" },
    },
  },
  ({ op, count, step, prefix }) => {
    // @scene-id node-1781159445743
    const numberValue1 = numberValue({})

    // @scene-id node-1781159448560
    const numberValue2 = numberValue({
        "$params": {"value":1},
      })

    // @scene-id node-1781159483455
    const typeNumber3 = typeNumber({
        "value": count,
      })

    // @scene-id node-1781159461947
    const basicMathOp4 = basicMathOp({
        "$params": {"op":"-"},
        "op": op,
        "b": numberValue2.value,
        "a": typeNumber3.value,
      })

    // @scene-id node-1781159526937
    const stringValue5 = stringValue({
        "value": prefix,
      })

    // @scene-id node-1781159514175
    const rangeList6 = rangeList({
        "step": step,
        "start": numberValue1.value,
        "end": basicMathOp4.result,
        "prefix": stringValue5.value,
      })
    return {
      list: rangeList6.list,
      names: rangeList6.stringList,
      count: rangeList6.count,
    }
  },
)
