// Generated by scripts/generate-native-group-definitions.mts.
// JSON parity oracle only: batteries/groups/scene/TileAssetName/TileAssetName.json
// @scene-id definition:batteries.groups.scene.tile-asset-name.tile-asset-name
export const tileAssetName = defineGroup(
  {
    id: "scene.group.scene.tile-asset-name.tile-asset-name",
    version: "1.0.0",
    inputs: {
      scene: { type: Scene, runtimeType: "scene", runtimePort: "in_0", label: "scene", labelEn: "Scene" },
      value: { type: StringValue, runtimeType: "string", runtimePort: "in_1", label: "值", labelEn: "Value" },
    },
    outputs: {
      scene: { type: Scene, runtimeType: "scene", runtimePort: "out_0", label: "scene", labelEn: "Scene" },
    },
  },
  ({ scene, value }) => {
    // @scene-id node-1781094591109
    const textPanel1 = textPanel({
        "$params": {"text":"asset_name","_nodeWidth":180,"_nodeHeight":67},
      })

    // @scene-id node-1781094625955-ysok9
    const textPanel2 = textPanel({
        "$params": {"text":"asset_type","_nodeWidth":181,"_nodeHeight":60},
      })

    // @scene-id node-1781094635614-mu6fs
    const textPanel3 = textPanel({
        "$params": {"text":"tile","_nodeWidth":181,"_nodeHeight":60},
      })

    // @scene-id node-1781159302096
    const stringValue4 = stringValue({
        "value": value,
      })

    // @scene-id node-1781097305549
    const sceneSetAttribute5 = sceneSetAttribute({
        "scene": scene,
        "key": textPanel1.output,
        "value": stringValue4.value,
      })

    // @scene-id node-1781097326596-22xx1
    const sceneSetAttribute6 = sceneSetAttribute({
        "scene": sceneSetAttribute5.scene,
        "key": textPanel2.output,
        "value": textPanel3.output,
      })
    return {
      scene: sceneSetAttribute6.scene,
    }
  },
)
